<?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="'. $this->zoneconfig['conf']['id'] . '"';
?>
<div class="relativeWrap" <?= $id; ?> data-melisKey='<?= $this->melisKey; ?>' style="<?php echo ($this->show) ? "" : "display:none;"; ?> padding-top:50px; padding-bottom: 50px;">
    <?php if(isset($modules)) { ?>
        <!-- TOP BUTTONS HOLDER -->
        <div class="row pull-right" style="margin-top: -40px;margin-right: 1px;">
            <!-- CONDITION -->
                <button type="button" class="btn btn-success extract-selected"><i class="fa fa-check" style="padding-right: 5px;"></i><?= $this->translate('tr_melis_core_gdpr_tabs_extract_selected_button'); ?></button>
                <button type="button" class="btn btn-danger delete-selected"><i class="fa fa-times" style="padding-right: 5px;"></i><?= $this->translate('tr_melis_core_gdpr_tabs_delete_selected_button'); ?></button>
            <!-- END OF CONDITION -->
        </div>
        <!-- END OF TOP BUTTONS HOLDER -->
        <!-- INTERFACE / ZONES -->
        <div class="widget widget-tabs widget-tabs-double widget-regular widget-tabs-vertical row row-merge">
            <!-- Left Side Tab -->
            <!-- Tabs Heading -->
            <div class="widget-head col-md-3">
                <ul>
                    <?php $firstItem = true; ?>
                    <!-- condition start -->
                    <?php if(isset($modules)) { ?>
                        <!-- loop start -->
                        <?php foreach ($modules as $module) { ?>

                            <?php if(isset($module['moduleName']) && isset($module['icon'])) { ?>
                                <li class="<?php echo $firstItem ? 'active' : ''; ?>" style="border-bottom: 1px solid #e5e5e5"><a href="#<?= $module['moduleName'] ?>-tab" id="<?= $module['moduleName'] ?>-left-tab" data-toggle="tab" class="">
                                        <p style="margin-bottom: 0px;margin-top: 5px;"><i class="<?= $module['icon'] ?>" style="margin-left: 20px;margin-right: 12px; width: 22.86px;"></i><?= $module['moduleName'] ?></p></a>
                                </li>
                            <?php } ?>
                            <?php $firstItem = false; ?>

                        <?php } ?>
                        <!-- loop end -->
                    <?php } ?>
                    <!-- condition end -->
                </ul>
            </div>
            <!-- // Tabs Heading END -->
            <div class="widget-body col-md-9">
                <div class="tab-content">
                    <!-- Right Side Tab -->
                    <!-- Tab content -->
                    <?php if(isset($modules)) { ?>

                        <?php foreach($modules as $module) { ?>
                            <?php if(isset($module['moduleName']) && isset($module['icon']) && isset($module['values']['columns']) && isset($module['values']['datas'])) {?>
                                <div class="tab-pane" id="<?= $module['moduleName']; ?>-tab">
                                    <table id="<?= $module['moduleName']; ?>" class="table table-striped table-primary dt-responsive stripe" style="width: 100%;">
                                        <thead>
                                        <tr role="row">
                                            <th>ID</th>
                                            <th class="no-sort sort-all">
                                                <div class="checkbox checkbox-single margin-none">
                                                    <label class="checkbox-custom">
                                                        <i class="fa fa-fw fa-square-o" style="color:white;"></i>
                                                        <input type="checkbox" class="check-all">
                                                    </label>
                                                </div>
                                            </th>
                                            <?php foreach($module['values']['columns'] as $column) { ?>
                                                <th id="<?= $column['id'] ?>" class="no-sort"><?= $this->translate($column['text']) ?></th>
                                            <?php } ?>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php if(isset($module['values']['datas'])) { ?>
                                            <?php foreach($module['values']['datas'] as $dataArrayKey => $dataArrayValue) { ?>
                                                <tr role="row" class="">
                                                    <td><?= $dataArrayKey ?></td>
                                                    <td class="not-included">
                                                        <div class="checkbox checkbox-single margin-none">
                                                            <label class="checkbox-custom">
                                                                <i class="fa fa-fw fa-square-o"></i>
                                                                <input type="checkbox" class="checkRow" value="<?= $dataArrayKey ?>">
                                                            </label>
                                                        </div>
                                                    </td>
                                                    <?php foreach($dataArrayValue as $dataKey => $dataValue ) { ?>
                                                        <?php if (isset($module['values']['columns'][$dataKey]['type'])) { ?>
                                                            <!-- TYPE STATUS -->
                                                            <?php if ($module['values']['columns'][$dataKey]['type'] == 'status') { ?>
                                                                <?php if ($dataValue == 1) { ?>
                                                                    <td><span class="text-success"><i class="fa fa-fw fa-circle"></i></span></td>
                                                                <?php } else if ($dataValue == 0) { ?>
                                                                    <td><span class="text-danger"><i class="fa fa-fw fa-circle"></i></span></td>
                                                                <?php } else { ?>
                                                                    <td></td>
                                                                <?php } ?>
                                                            <?php } ?>
                                                            <!-- END OF TYPE STATUS -->
                                                            <!-- TYPE ADMIN -->
                                                            <?php if ($module['values']['columns'][$dataKey]['type'] == 'admin') { ?>
                                                                <?php if ($dataValue == 1) { ?>
                                                                    <td style="color:#72af46;">Yes</td>
                                                                <?php } else if ($dataValue == 0) { ?>
                                                                    <td style="color:#bd362f;">No</td>
                                                                <?php } else { ?>
                                                                    <td></td>
                                                                <?php } ?>
                                                            <?php } ?>
                                                            <!-- END OF TYPE ADMIN -->
                                                        <?php } else { ?>
                                                        <td><?= $dataValue ?></td>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </tr>
                                            <?php } ?>
                                        <?php } ?>
                                        </tbody>
                                    </table>
                                    <script>
                                        $(document).ready(function() {

                                            //redraw table when tab is shown where the table is located so that the headers will have the right size
                                            $(document).on('shown.bs.tab', 'a[href="<?php echo '#' . $module['moduleName']; ?>-tab"]', function (e) {
                                                if ($("body").find("<?php echo '#' . $module['moduleName']; ?>-tab").find(".dataTables_scroll .dataTables_scrollBody table").height() < 230) {
                                                    $("<?php echo '#' . $module['moduleName']; ?>").closest('.dataTables_scrollBody').css("overflow", "");
                                                } else {
                                                    ;
                                                    $("<?php echo '#' . $module['moduleName']; ?>").closest('.dataTables_scrollBody').css("overflow", "overlay");
                                                }

                                                $("<?php echo '#' . $module['moduleName']; ?>").closest('.dataTables_scrollBody').siblings('.dataTables_scrollHead').css("overflow", "");

                                                $.fn.dataTable.tables({ visible: true, api: true }).columns.adjust();
                                            });

                                            setTimeout(function(){
                                                $("<?php echo '#' . $module['moduleName']; ?>").dataTable({
                                                    "scrollY": '300px',
                                                    "scrollCollapse": true,
                                                    "paging": false,
                                                    "searching": false,
                                                    "ordering": true,
                                                    columnDefs: [{
                                                        orderable: false,
                                                        targets: "no-sort",
                                                    }],
                                                    "drawCallback": function() {
                                                        if ($("body").find("<?php echo '#' . $module['moduleName']; ?>-tab").find(".dataTables_scroll .dataTables_scrollBody table").height() < 230) {
                                                            $("<?php echo '#' . $module['moduleName']; ?>").closest('.dataTables_scrollBody').css("overflow", "");
                                                        } else {
                                                            $("<?php echo '#' . $module['moduleName']; ?>").closest('.dataTables_scrollBody').css("overflow", "overlay");
                                                        }

                                                        $("<?php echo '#' . $module['moduleName']; ?>").closest('.dataTables_scrollBody').siblings('.dataTables_scrollHead').css("overflow", "");
                                                    }
                                                });
                                            }, 1);

                                        });
                                    </script>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                    <!-- // Tab content END -->
                </div>
            </div>
        </div>
        <!-- END OF INTERFACE / ZONES -->
        <div class="row pull-right" style="margin-top: 5px;margin-right: 1px;">
            <!-- CONDITION -->
            <button type="button" class="btn btn-success extract-selected"><i class="fa fa-check" style="padding-right: 5px;"></i><?= $this->translate('tr_melis_core_gdpr_tabs_extract_selected_button'); ?></button>
            <button type="button" class="btn btn-danger delete-selected"><i class="fa fa-times" style="padding-right: 5px;"></i><?= $this->translate('tr_melis_core_gdpr_tabs_delete_selected_button'); ?></button>
            <!-- END OF CONDITION -->
        </div>
    <?php } ?>
    <script>
        var $body = $("body");
        var $tabContent = $("#id_melis_core_gdpr_content_tabs .tab-content");
        var $contentTabs = $("#id_melis_core_gdpr_content_tabs");

        if ($tabContent.length) {
            var countOfRows = 0;
            var moduleName;
            $body.find('#id_melis_core_gdpr_content_tabs .tab-content .tab-pane').each(function() {
                countOfRows = $(this).find('table tbody tr').length;
                moduleName = $(this).find('table').attr('id');
                $(this).closest('.widget-body').siblings('.widget-head').find('ul #' + moduleName + '-left-tab p').append(' (0/' + countOfRows + ')');
            });
        }

        if ($tabContent.length == 0 && $contentTabs.css('display') != 'none') {
            melisHelper.melisKoNotification(
                translations.tr_melis_core_gdpr,
                translations.tr_melis_core_gdpr_notif_no_user_data_found,
            );
        }
    </script>
</div>