<?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="'. $this->zoneconfig['conf']['id'] . '"';
?>

<div class="me-heading bg-white border-bottom" <?= $id; ?> data-melisKey='<?= $this->melisKey; ?>'>
    <div class="row" style="width: 100%;">
        <div class="me-hl col-12 col-md-12">
            <h1 class="content-heading"><?= $this->translate('tr_melis_core_gdpr_header_title'); ?></h1>
            <p><?= $this->translate('tr_melis_core_gdpr_header_description'); ?></p>
        </div>
    </div>
</div> 