<?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="'. $this->zoneconfig['conf']['id'] . '"';
?>
<div <?= $id; ?> data-melisKey='<?= $this->melisKey; ?>'>
    <div class="row">
        <div class="col-md-5">
        <h1 style="margin-left: 6.5%;"><?= $this->translate('tr_melis_core_gdpr_tabs_header_title') ?></h1>
        </div>
    </div>
    </br>
    <div class="row">
        <div class="col-md-5">
            <?php
                $form = clone $this->form;
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->melisFieldCollection($form);
            ?>
            <button type="submit" id="melis-core-gdpr-search-form-submit" class="btn btn-primary" style="margin-left: 16.5%;"><i class="fa fa-search"></i> <?= $this->translate('tr_melis_core_gdpr_view_search_button') ?></button>
            <?php
                echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>
</br>