<?php

	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
		
?>
<div <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="user-profile media innerAll">
	<a href="" class="pull-left" id="img-user-link">
		<img src="/melis/MelisCore/MelisAuth/getProfilePicture?v=<?= time(); ?>" alt="" class="rounded-circle" id="meliscore_left_menu_profile_pic" width="50" height="50">

	</a>
	<div class="media-body">
		<a href="" class="strong" id="user-name-link" data-user-id="<?= $this->userAuthDatas->usr_id; ?>">
			<?php 
			     if (!empty($this->userAuthDatas))
			     {
			?>
			<?= $this->melisTextHelper()->limitedText($this->escapeHtml($this->userAuthDatas->usr_firstname), 20);?> <?= $this->melisTextHelper()->limitedText($this->escapeHtml($this->userAuthDatas->usr_lastname), 20);?>
			<?php 
			     }
			?>
		</a>
		<p class="text-success">
			<i class="fa fa-fw fa-circle"></i> <?= $this->translate('tr_meliscore_common_online'); ?>
		</p>
	</div>
	<ul>
		 
		<li class="active">
    		<a href="#" id="btnUserInfoEdit" title="<?=$this->translate('tr_meliscore_user_profile_profile_text'); ?>">
    			<i class="fa fa-fw fa-user"></i>
    		</a>
		</li> 

		<li><a href="melis/logout" title="<?= $this->translate('tr_meliscore_header_logout'); ?>"><i class="fa fa-fw fa-lock"></i></a></li>  
	</ul> 
</div>