<?php
 $form = $this->meliscore_login;
 $form->prepare();
 $isChecked = $this->isChecked ? 'checked="checked"' : '';
?>



<div id="content loginContent">
 	<h4 class="innerAll margin-none border-bottom text-center"><i class="fa fa-lock"></i> <?= $this->translate('tr_meliscore_login_header'); ?></h4>
    <div class="login spacing-x2">
     	<div class="placeholder main-login-page text-center">
     	
     		<div class="business-logo-container">
     			<img class="melis-services-img" alt="melis technologies services" src="/MelisCore/images/login/melis-box.png">
     		</div>
     		
     	</div>
     	<div class="container">
             <div class="row">
                 <div class="col-sm-6 col-sm-offset-3">
                      <div class="panel panel-default">
                           <div class="panel-body innerAll">
								<div id="loginprompt"></div>
                                <?= $this->form()->openTag($form); ?>
                                    <?php 
                                     echo $this->melisFieldCollection($form);
                                    ?>
                                  <div class="checkbox cb-cont">
                                       <label class="remember-me-cont">
                                            <span class="cbmask-outer">
                                            	<span  class="cbmask-inner"></span>
                                           	</span>
                                            <input type="hidden" name="remember" value="0" >
                                            <input type="checkbox" name="remember" value="1" <?= $isChecked; ?>> <?= $this->translate('tr_meliscore_login_remember_me'); ?>
                                       </label>
                                   	   <span class="pull-right"><a href="/melis/lost-password"><?= $this->translate('tr_meliscore_forgot_password'); ?></a></span>
                                  </div>
                                <?= $this->form()->closeTag(); ?>
                    
                             </div>
                      </div>
                 </div>
             </div>
     	</div>
    </div>
</div>