<?php
 $form = $this->meliscore_login;
 $form->prepare();
 $isChecked = $this->isChecked ? 'checked="checked"' : '';

$schemes         = $this->layout()->schemes;
$loginLogo       = $this->login_logo;

if($schemes) {
    if(!empty($schemes->getLoginBackground())) {
        $loginLogo = $schemes->getLoginLogo();
    }
}
?>



<div id="content loginContent" class="content-login">
 	<h4 class="innerAll margin-none border-bottom text-center"><i class="fa fa-lock"></i> <?= $this->translate('tr_meliscore_login_header'); ?></h4>
    <div class="login spacing-x2">
     	<div class="placeholder main-login-page text-center">    	
     		<div class="business-logo-container">
     			<img class="melis-services-img" alt="melis technologies services" src="<?= $loginLogo ?>">
     		</div>
     	</div>
     	<div class="container-fluid">
            <div class="card-wrapper mx-auto">
                <div class="card">
                    <div class="card-body innerAll">
                        <div id="loginprompt"></div>
                            <?= $this->form()->openTag($form); ?>
                            <?php 
                                echo $this->melisFieldCollection($form);
                            ?>
                            <div class="checkbox cb-cont d-flex justify-content-between">
                                <label class="remember-me-cont">
                                    <span class="cbmask-outer">
                                        <span  class="cbmask-inner"></span>
                                    </span>
                                    <input type="hidden" name="remember" value="0" >
                                    <input type="checkbox" name="remember" value="1" <?= $isChecked; ?>> <?= $this->translate('tr_meliscore_login_remember_me'); ?>
                                </label>
                                <span class="forgot-password"><a href="/melis/lost-password"><?= $this->translate('tr_meliscore_forgot_password'); ?></a></span>
                            </div>
                            <?= $this->form()->closeTag(); ?>
                        </div>
                </div>
            </div>
     	</div>
    </div>
</div>
<div class="hidden">
	<script type="text/javascript">
		<!--//--><![CDATA[//><!--

			if ( document.images ) {
				img1 = new Image();

				img1.src = "/MelisCore/assets/images/page-loader.gif";
			}

		//--><!]]>
	</script>
</div>