<div id="add-edit-config" class="custom-accordion-heading">
    <div class="button-right">
        <button class="btn btn-success float-right" style="margin:20px 30px 0 0">
            <i class="fa fa-save"></i> Save
        </button>
    </div>
    <a data-toggle="collapse" data-target="#add-edit-config-content" aria-expanded="true" aria-controls="add-edit-config-content" class="accordion-heading-add-delete">
        <h3 class="accordion-heading-title">Add configuration</h3>
    </a>
</div>