<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
}
?>
<div <?= $id; ?> data-melisKey='<?= $this->melisKey ?>' style="padding:0 22px 0 40px" class="gdpr-auto-delete-multi-tabs">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-2">
                    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                        <?php
                            if(!empty($this->zoneconfig['interface'])) {
                                foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) { ?>
                                    <a class="nav-link active" id="<?= $menuConfig['conf']['id'] ?? null ?>" data-toggle="pill" href="#<?= $menuConfig['conf']['id'] ?? null ?>" role="tab" aria-controls="<?= $menuConfig['conf']['id'] ?? null ?>" aria-selected="true"><?= $menuConfig['conf']['name'] ?? null ?></a>
                                <?php }
                            }
                        ?>
                    </div>
                </div>
                <div class="col-md-10">
                    <div class="tab-content" id="v-pills-tabContent">
                        <?php
                            if(!empty($this->zoneconfig['interface'])) {
                                foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                                    echo $this->$keyConfig;
                                }
                            }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
