<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
}
?>

<div id="add-edit-config" class="custom-accordion-heading">
    <div class="button-right">
        <?php
        if(!empty($this->zoneconfig['interface'])) {
            foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
        ?>
    </div>
    <a data-bs-toggle="collapse" data-bs-target="#add-edit-config-content" role="button" aria-expanded="true" aria-controls="add-edit-config-content" class="accordion-heading-add-delete arrow-indication-down" style="border-top:1px solid #eee">
        <h3 class="accordion-heading-title" id="add-edit-main-heading">
            <?= ($this->configId) ? $this->translate('tr_melis_core_gdpr_autodelete_label_edit_accordion_heading') : $this->translate('tr_melis_core_gdpr_autodelete_label_add_accordion_heading')?>
            <p class='accordion-subtitle' id="add-edit-config-sub-heading">
                <?= ($this->configId) ? $this->translate('tr_melis_core_gdpr_autodelete_label_edit_accordion_sub_heading') : $this->translate('tr_melis_core_gdpr_autodelete_label_add_accordion_sub_heading')?>
            </p>
        </h3>
    </a>
</div>
