<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
}
?>
<div <?= $id; ?> data-melisKey='<?= $this->melisKey ?>'>
    <div id="accordion">
        <div class="card default-card" style="border:none;">
            <?php
                if(!empty($this->zoneconfig['interface'])) {
                    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                        echo $this->$keyConfig;
                    }
                }
            ?>
        </div>
    </div>
</div>
