<div id="list-config" class="custom-accordion-heading">
    <div class="button-right">
        <button class="btn btn-success float-right" id="add-auto-delete-config">
            <i class="fa fa-plus"></i> Add new config
        </button>
    </div>
    <a data-toggle="collapse" data-target="#list-config-content" aria-expanded="true" aria-controls="list-config-content" class="accordion-heading">
        <h3 class="accordion-heading-title">List of Auto Delete Configuration
            <span class="accordion-subtitle">Manage here your auto delete configurations.</span>
        </h3>
    </a>
</div>