<div id="content" class="transition3ms">
	<div class="innerAll px2">
		<!-- Tabs -->
		<div class="relativeWrap full-width">
			<!-- Melis content loader -->
			<div class="tab-content" id="melis-id-body-content-load">
				<?php 
					if (!empty($this->zoneconfig['interface'])) 
					{
						$cpt = 0;
						foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig)
						{
							echo $this->$keyConfig;
							$cpt++;
						}
					}
				?>		
			</div>
			<!-- // Melis content loader -->
		</div>
		<!-- // Tabs END -->
	</div>
	<!-- // Content END -->
	<div class="clearfix"></div>
	<!-- // Sidebar menu & content wrapper END -->
</div>
<!-- // Main Container Fluid END -->