
<!-- START melis user tabs -->
<li class="dropdown notification" style="margin-right: -1px;">
    <a href="#" class="dropdown-toggle menu-icon dropdown-hover" id="close-all-tab" title="<?= $this->translate('tr_melis_user_tabs_close_all_open_tabs'); ?>" style="display:none;">
        <i class="fa fa-fw fa-times" style="font-size: 1.142rem;"></i>
        <span class="badge badge-success hidden">0</span>
        <span class="title-text"><?= $this->translate('tr_melis_user_tabs_close_all_open_tabs'); ?></span>
    </a>
</li>