<?php

	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
		
?>
<div <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="hidden-print transition3ms">
	<div class="copy footer container">
		<a href="http://www.melistechnology.com/" target="_blank"><?php echo $this->translate('tr_meliscore_footer_2015 by Melis Technology') ?></a>
		- <?php echo $this->translate('tr_meliscore_footer_all rights reserved') ?> 
		<a href="https://www.melistechnology.com/melistechnology/resources/download-documentation/id/17" target="_blank">
			<?php echo $this->translate('tr_meliscore_header Title') ?>
		</a>
		- <?php echo $this->translate('tr_meliscore_footer_Version') ?>: <?= $this->platformVersion; ?>
        <?php if($this->netConn){?>
            <iframe class="marketplaceUpdate" src="about:blank" width="1px" height="1px" style="border-color: transparent; background: transparent;"></iframe>
        <?php }?>
	</div>
</div>