<div id="menu">
    <?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
    ?>

    <div<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="sidebar sidebar-inverse transition3ms">

        <?php

        if (!empty($this->zoneconfig['interface']['meliscore_leftmenu_identity']))
            echo $this->meliscore_leftmenu_identity;
        ?>

        <div class="sidebarMenuWrapper hasNiceScroll">

            <ul class="list-unstyled sideMenu">

                <?php
                if (!empty($this->zoneconfig['interface'])) {
                    foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                        if ($keyConfig == 'meliscore_leftmenu_dashboard') {
                            echo $this->$keyConfig;
                        }
                    }
                }
                ?>

                <?php
                if (!empty($this->zoneconfig['interface'])) {
                    echo $this->meliscore_toolstree_section;
                }
                ?>

                <li id="toolstree_meliscms" class="hasSubmenu" data-meliskey="toolstre_meliscms">
                    <a data-target="#meliscms_tools" data-toggle="collapse" class="" aria-expanded="true">
                        <div class="melis-svg-icon pull-left">
                            <?= $this->melisCmsIcon() ?>
                        </div>
                        <label class="toolstree-label"><?= $this->translate('MelisCms') ?></label>
                        <div class="clearfix"></div>
                    </a>
                    <ul class="collapse" id="meliscms_tools" aria-expanded="false">
                        <?php
                        if (!empty($this->zoneconfig['interface'])) {
                            echo $this->meliscms_sitetree;
                            echo $this->meliscms_toolstree_section;
                        }
                        ?>
                    </ul>
                </li>

                <?php
                if (!empty($this->zoneconfig['interface'])) {
                    echo $this->melismarketing_toolstree_section;
                }
                ?>

                <?php
                if (!empty($this->zoneconfig['interface'])) {
                    echo $this->meliscommerce_toolstree_section;
                }
                ?>

                <?php
                if (!empty($this->zoneconfig['interface'])) {
                    echo $this->melisothers_toolstree_section;
                }
                ?>

                <?php
                if (!empty($this->zoneconfig['interface'])) {
                    echo $this->meliscustom_toolstree_section;
                }
                ?>
            </ul>
        </div>
        <?php
        if (!empty($this->zoneconfig['interface']['meliscore_footer']))
            echo $this->meliscore_footer;
        ?>
    </div>
</div>
