<div id="menu">
    <?php
    
    	$id = '';
    	if (!empty($this->zoneconfig['conf']['id']))
    		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
    	$data_melisKey = $this->melisKey;
    	
    ?>

    <div<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="sidebar sidebar-inverse transition3ms">
     
      
      	
    	<?php 
    	
    		if (!empty($this->zoneconfig['interface']['meliscore_leftmenu_identity']))
    			echo $this->meliscore_leftmenu_identity;
    	
    	?>

        <div class="sidebarMenuWrapper hasNiceScroll">
        
            <ul class="list-unstyled sideMenu">

            	<?php 
        	    	if (!empty($this->zoneconfig['interface']))
        	    	{


//        	    	    print '<pre>';
//        	    	    print_r($this->zoneconfig['interface']);
//        	    	    print '</pre>';
//        	    	    die;
                        // MelisCore

        	    		foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig)
        	    		{
        	    			if ($keyConfig != 'meliscore_leftmenu_identity' && $keyConfig != 'meliscore_footer')
        	    			{
//        	    				echo $this->$keyConfig;
        	    			}
//                            if ($keyConfig == 'meliscore_leftmenu_dashboard')
//                            {
//                                echo $this->$keyConfig;
//                            }
        	    		}
        	    	}
        	 	?>

                <li id="toolstre_meliscore" class="toolstree hasSubmenu" data-meliskey="toolstre_meliscore">
                    <a data-target="#meliscore_tools" data-toggle="collapse" class="" aria-expanded="true">
                        <div class="melis-svg-icon pull-left">
                            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
                                <g>
                                    <rect class="bg-color" y="0.1" fill="#ee6622" width="29.9" height="29.9"></rect>
                                    <rect class="light-color" x="14.6" y="2.7" fill="#f7962d" width="12.7" height="24.6"></rect>
                                    <g>
                                        <path fill="#FFFFFF" d="M7.4,21.1V9.5H22v11.7h-2.9v-8.8h-2.9v8.8h-2.9v-8.8h-2.9v8.8H7.4z"></path>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <label class="toolstree-label"><?= $this->translate('MelisCore') ?></label>
                        <div class="clearfix"></div>
                    </a>
                    <ul class="collapse" id="meliscore_tools" aria-expanded="false">

                        <?php
                        if (!empty($this->zoneconfig['interface']))
                        {
                            foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig)
                            {
                                if ($keyConfig != 'meliscore_leftmenu_identity' && $keyConfig != 'meliscore_footer')
                                {
        	    				    echo $this->$keyConfig;
                                }

                            }
                        }
                        ?>
                    </ul>
                </li>

                <li class="toolstree_meliscms" id="toolstre_meliscms" class="hasSubmenu" data-meliskey="toolstre_meliscms">
                    <a data-target="#meliscms_tools" data-toggle="collapse" class="" aria-expanded="true">
                        <div class="melis-svg-icon pull-left">
                            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
                                <g>
                                    <rect class="bg-color" y="0.1" fill="#69b344" width="29.9" height="29.9"></rect>
                                    <rect class="light-color" x="14.6" y="2.7" fill="#85c555" width="12.7" height="24.6"></rect>
                                    <g>
                                        <path fill="#FFFFFF" d="M7.4,21.1V9.5H22v11.7h-2.9v-8.8h-2.9v8.8h-2.9v-8.8h-2.9v8.8H7.4z"></path>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <label class="toolstree-label"><?= $this->translate('MelisCms') ?></label>
                        <div class="clearfix"></div>
                    </a>
                </li>

                <li class="toolstree_marketing" id="toolstre_melismarketing" class="hasSubmenu" data-meliskey="toolstre_melismarketing">
                    <a data-target="#marketing_tools" data-toggle="collapse" class="" aria-expanded="true">
                        <div class="melis-svg-icon pull-left">
                            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
                                <g>
                                    <rect class="bg-color" y="0.1" fill="#70469c" width="29.9" height="29.9"></rect>
                                    <rect class="light-color" x="14.6" y="2.7" fill="#8965ad" width="12.7" height="24.6"></rect>
                                    <g>
                                        <path fill="#FFFFFF" d="M7.4,21.1V9.5H22v11.7h-2.9v-8.8h-2.9v8.8h-2.9v-8.8h-2.9v8.8H7.4z"></path>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <label class="toolstree-label"><?= $this->translate('MelisMarketing') ?></label>
                        <div class="clearfix"></div>
                    </a>
                </li>

                <li class="toolstree_meliscommerce" id="toolstre_meliscommerce" class="hasSubmenu" data-meliskey="toolstre_meliscommerce">
                    <a data-target="#meliscommerce_tools" data-toggle="collapse" class="" aria-expanded="true">
                        <div class="melis-svg-icon pull-left">
                            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
                                <g>
                                    <rect class="bg-color" y="0.1" fill="#3997d4" width="29.9" height="29.9"></rect>
                                    <rect class="light-color" x="14.6" y="2.7" fill="#2780c4" width="12.7" height="24.6"></rect>
                                    <g>
                                        <path fill="#FFFFFF" d="M7.4,21.1V9.5H22v11.7h-2.9v-8.8h-2.9v8.8h-2.9v-8.8h-2.9v8.8H7.4z"></path>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <label class="toolstree-label"><?= $this->translate('MelisCommerce') ?></label>
                        <div class="clearfix"></div>
                    </a>
                </li>

                <li class="toolstree_others" id="toolstre_others" class="hasSubmenu" data-meliskey="toolstre_others">
                    <a data-target="#tools_others" data-toggle="collapse" aria-expanded="true">
                        <div class="melis-svg-icon pull-left">
                            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
                                <g>
                                    <rect class="bg-color" y="0.1" fill="#C52127" width="29.9" height="29.9"></rect>
                                    <rect class="light-color" x="14.6" y="2.7" fill="#E71E26" width="12.7" height="24.6"></rect>
                                    <g>
                                        <path fill="#FFFFFF" d="M7.4,21.1V9.5H22v11.7h-2.9v-8.8h-2.9v8.8h-2.9v-8.8h-2.9v8.8H7.4z"></path>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <label class="toolstree-label"><?= $this->translate('Others') ?></label>
                        <div class="clearfix"></div>
                    </a>
                </li>

                <li class="toolstree" id="id_meliscore_menu_toolstree" class="hasSubmenu" data-meliskey="meliscore_menu_toolstree">
                    <a data-target="#tools" data-toggle="collapse" class="" aria-expanded="true">
                        <div class="melis-svg-icon pull-left">
                            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
                                <g>
                                    <rect class="bg-color" y="0.1" fill="#676767" width="29.9" height="29.9"></rect>
                                    <rect class="light-color" x="14.6" y="2.7" fill="#777777" width="12.7" height="24.6"></rect>
                                    <g>
                                        <path fill="#FFFFFF" d="M7.4,21.1V9.5H22v11.7h-2.9v-8.8h-2.9v8.8h-2.9v-8.8h-2.9v8.8H7.4z"></path>
                                    </g>
                                </g>
                            </svg>
                        </div>
                        <label class="toolstree-label"><?= $this->translate('Custom / Projects') ?></label>
                        <div class="clearfix"></div>
                    </a>
                </li>

            </ul>
        </div>
        	
            <?php       
            	if (!empty($this->zoneconfig['interface']['meliscore_footer']))
            		echo $this->meliscore_footer;
            ?>    
           
      
    </div>
</div>