<div id="menu" class="d-print-none">
    <?php
        $id = '';
        if (!empty($this->zoneconfig['conf']['id']))
            $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
        $data_melisKey = $this->melisKey;
    ?>
    <div <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="sidebar sidebar-inverse transition3ms">
        <?php
            if (!empty($this->zoneconfig['interface']['meliscore_leftmenu_identity']))
                echo $this->meliscore_leftmenu_identity;
        ?>
        <div class="sidebarMenuWrapper hasNiceScroll">
            <ul class="list-unstyled sideMenu">
                <!-- <div id="disable-left-menu-overlay"></div> -->
                <?php
                    if (!empty($this->zoneconfig['interface'])) {
                        foreach ($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                            if ($keyConfig == 'meliscore_leftmenu_dashboard') {
                                echo $this->$keyConfig;
                            }
                        }
                    }

                    if (!empty($this->zoneconfig['interface'])) {
                        echo $this->meliscore_toolstree_section;
                    }

                    if (!empty($this->zoneconfig['interface'])) {
                        echo "<div id='site-tree-cont' class='hidden'>$this->meliscms_sitetree</div>";
                        echo "<div id='documentation-tree-cont' class='hidden'>$this->meliscmsdocumentation_tree</div>";
                        echo $this->meliscms_toolstree_section;
                    }

                    if (!empty($this->zoneconfig['interface'])) {
                        echo $this->melismarketing_toolstree_section;
                    }

                    if (!empty($this->zoneconfig['interface'])) {
                        echo $this->meliscommerce_toolstree_section;
                    }

                    if (!empty($this->zoneconfig['interface'])) {
                        echo $this->melisothers_toolstree_section;
                    }

                    if (!empty($this->zoneconfig['interface'])) {
                        echo $this->meliscustom_toolstree_section;
                    }

                    if (!empty($this->zoneconfig['interface'])) {
                        echo $this->melismarketplace_toolstree_section;
                    }
                ?>
            </ul>
        </div>
        <?php
            if (!empty($this->zoneconfig['interface']['meliscore_footer']))
                echo $this->meliscore_footer;
        ?>
    </div>
</div>