<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->boeId.'_'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>

<div <?php echo $id.' '.$data_melisKey; ?>>
	<div class="spacing-x2 innerAll">
		<div class="row">
    		<div class="col-xs-12 col-md-2">
    			<!-- Tab Nav  -->
    			<?php echo $this->meliscore_tool_emails_mngt_generic_from_content_tab_nav ?>
    		</div>
    		
    		<div class="col-xs-12 col-md-5">
    			<!-- Tab Content  -->
    			<?php echo $this->meliscore_tool_emails_mngt_generic_from_content_tab_content ?>
    		</div>
		</div>
	</div>
</div>
