<div class="product-text-tab-container">
	<ul class="nav nav-tabs product-text-tab">
		<li class="nav-item active">
			<a class="nav-link clearfix" data-bs-toggle="tab" href="#<?php echo $this->codename ?>_general_properties" aria-expanded="true">
				<span><?php echo $this->translate('tr_meliscore_tool_emails_mngt_general_properties')?></span>
			</a>
		</li>
		<?php 
		    for ($i = 0; $i<count($this->coreLangDatas); $i++){
    		    echo '<li class="nav-item">
            			<a class="nav-link clearfix" data-bs-toggle="tab" href="#'.$this->codename.'_'.$this->coreLangDatas[$i]['lang_locale'].'" aria-expanded="false">
            				<span>'.$this->coreLangDatas[$i]['lang_name'].'</span>
            			</a>
            		</li>';
		    }
		?>
	</ul>
</div>