<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->codename.'_'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>

<div <?php echo $id.' '.$data_melisKey; ?> class="tab-pane container-level-a" data-editor-count="1">
	<?php 
		if($this->noAccessPrompt){
		    if(!empty($this->zoneconfig['interface'])) {
		        foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
		            echo $this->$keyConfig;
		        }
		    }
		}else{
            echo '<h4>'.$this->noAccessPrompt.'</h4>';
        }
	?>
</div>
 