<div class="tab-content">
	<div id="<?php echo $this->codename ?>_general_properties" class="tab-pane product-text-tab-content active">
		<div class="me-heading bg-white border-bottom">
			<h3 class=""><?php echo $this->translate('tr_meliscore_tool_emails_mngt_general_properties')?></h3>
		</div>
		<div class="product-text-tab-form-content">
			<?php
            	$form = $this->meliscore_emails_mngt_tool_general_properties_form;
            	$form->setAttribute('id',$this->codename.'_generalPropertiesform');
            	$form->get('boe_tag_accepted_list')->setAttribute('id',$this->codename.'_boe_tag_accepted_list');
            	$form->get('boe_content_layout_logo')->setAttribute('data-file-value', $form->get('boe_content_layout_logo')->getValue());
            	$form->get('boe_content_layout_ftr_info')->setAttribute('id', $this->codename.'_boe_content_layout_ftr_info');

            	if (!empty($this->layout)) {
                    // Update Form's layout status
                    $layoutOptions = $form->get('boe_content_layout')->getOptions();
                    if (!empty($layoutOptions['label'])) {
                        $layoutOptions['label'] = '<span class="melis-core-layout-status text-'.($layout['status']? 'success' : 'danger').'">
                        <i class="fa fa-fw fa-circle" data-toggle="tooltip" data-placement="top" title="" data-original-title="'. $layout['msg'] .'"></i></span>'
                            . $layoutOptions['label'];
                        $form->get('boe_content_layout')->setOptions($layoutOptions);
                    }
                }

            	$form->prepare();
            	echo $this->form()->openTag($form); 
            	echo $this->melisFieldCollection($form);
            	echo $this->form()->closeTag(); 
            ?>
        </div>
	</div>
	<?php for ($i = 0; $i<count($this->coreLangDatas); $i++){ ?>
    	<div id="<?php echo $this->codename.'_'.$this->coreLangDatas[$i]['lang_locale'] ?>" class="tab-pane product-text-tab-content">
    		<div class="me-heading bg-white border-bottom">
    			<h3 class=""><i class="fa fa-language" aria-hidden="true"></i> <?php echo $this->coreLangDatas[$i]['lang_name'] ?></h3>
    		</div>
    		<div class="product-text-tab-form-content">
    			<?php
                	$form = clone $this->meliscore_emails_mngt_tool_emails_details_form;
                	
                	$form->setAttribute('id',$this->codename.'_'.$this->coreLangDatas[$i]['lang_id'].'_emailLangForm');
                	$form->get('boed_html')->setAttribute('id',$this->codename.'_'.$this->coreLangDatas[$i]['lang_id'].'_boed_html');
                	$form->get('boed_text')->setAttribute('id',$this->codename.'_'.$this->coreLangDatas[$i]['lang_id'].'_boed_text');
                	$form->add(array(
                	            'name' => 'boed_lang_id',
                                'attributes' => array(
                                    'type'  => 'text',
                                    'class' => 'boed_lang_id boed_lang_id_'.$this->codename.' hidden',
                                    'value' => $this->coreLangDatas[$i]['lang_id'],
                                    'data-locale' => $this->coreLangDatas[$i]['lang_locale'],
                                    'data-codename' => $this->codename
                                )
                            ));
                	
                	if (!empty($this->emailsDetailsDatas)&&isset($this->emailsDetailsDatas[$i])){
                	    $emailsDetailsDatas = $this->emailsDetailsDatas[$i];
                	    unset($emailsDetailsDatas['boed_email_id']);
                	    
                	    foreach ($emailsDetailsDatas As $key => $val){
                	        $form->get($key)->setAttribute('value',$val);
                	    }
                	}
                	
                	$form->prepare();
                	echo $this->form()->openTag($form); 
                	echo $this->melisFieldCollection($form);
                	echo $this->form()->closeTag(); 
                ?>
    		</div>
    	</div>
	<?php } ?>
</div>
<script type="text/javascript">initEmailsEditors();</script>