<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = ' id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    
    $name = '';
    if (!empty($this->zoneconfig['conf']['name'])){
        $name = $this->zoneconfig['conf']['name'];
    }
    
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>
<button class="btn btn-default btnMelisCoreEmailMngtCancel" <?php echo $id.' '.$data_melisKey; ?> data-codename="<?php echo $this->codename ?>"><?php echo $this->translate($name)?></button>