<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id'])){
        $id = 'id="'.$this->zoneconfig['conf']['id'] .'"';
    }
    $data_melisKey = 'data-melisKey="'.$this->melisKey.'"';
?>

<div <?php echo $id.' '.$data_melisKey; ?> class="tab-pane container-level-a">
	
	<?php 
		if($this->noAccessPrompt){
		    if(!empty($this->zoneconfig['interface'])) {
		        echo $this->meliscore_tool_emails_mngt_header;
		        echo $this->meliscore_tool_emails_mngt_content;
		    }
		}else{
            echo '<h4>'.$this->noAccessPrompt.'</h4>';
        }
	?>
</div>
 