<div class="filter-bar">
	<div class="row">
		<div class="fb-dt-left col-xs-12 col-md-4"></div>
		<div class="fb-dt-center col-xs-12 col-md-4"></div>
		<div class="fb-dt-right col-xs-12 col-md-4">
        	<div class="meliscore_tool_tool_emails_mngt_table_refresh">
        		<a class='btn btn-default melis-refreshTable' data-toggle="tab" aria-expanded="true" title="<?php echo $this->translate('tr_meliscms_common_refresh')?>"><i class="fa fa-refresh"></i></a> 
        	</div>
        </div>
	</div>
</div>
