<div class="panel-3d melis-dashboard-bubble-plugin">
    <div class="front">

        <div class="widget text-center">
            <div class="widget-body padding-none">
                <div>
                    <div class="bg-info innerAll">
                        <p class="lead strong margin-none text-white"><i class="fa fa-fw fa-comment"></i><br/><span id="dashboard-bubble-chat-plugin-counter">0</span> <?= $this->translate('tr_meliscore_dashboard_bubble_plugins_messages') ?></p>
                    </div>
                    <div id="dashboard-bubble-chat-back-btn-container" class="innerAll" style="height: 85px;"></div>
                </div>
            </div>
        </div>

    </div>
    <div class="back">

        <div class="widget widget-inverse widget-scroll" data-scroll-height="165px">
            <div class="widget-head">
                <button class="btn btn-xs btn-default float-right"><i class="fa fa-times"></i></button>
                <h4 class="heading"><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_messages') ?></h4>
            </div>
            <div class="widget-body padding-none">

                <div id="dashboard-bubble-chat-plugin-list" class="back-container">
                </div>

            </div>
        </div>
    </div>
</div>