<div class="row" style="padding:0 11px 0 11px;">
    <div class="col-12">
        <?php if ($this->showBubblePlugins) : ?>
            <button id="btn-hide-bubble-plugins" class="btn btn-info btn-regular pull-right">Hide</button>
        <?php else : ?>
            <button id="btn-show-bubble-plugins" class="btn btn-info btn-regular pull-right">Show</button>
        <?php endif; ?>
    </div>
</div>
<div id="dashboard-bubble-plugins-zone" class="row <?= (! $this->showBubblePlugins) ? 'hidden' : '' ?>" style="padding:0 10px 0 10px;">
    <?= $this->htmlPlugins ?>
</div>