<div class="panel-3d melis-dashboard-bubble-plugin melis-dashboard-bubble-updates-plugin" style="">
    <div class="front">

        <div class="widget text-center">
            <div class="widget-body padding-none">
                <div>
                    <div class="innerAll bg-default">
                        <p class="lead strong margin-none">
                            <i class="fa fa-fw fa-download"></i>
                            <br/>
                            <span class="dashboard-bubble-updates-counter">0</span>
                            <?= $this->translate('tr_meliscore_dashboard_bubble_plugins_updates') ?>
                        </p>
                    </div>
                    <div class="innerAll dashboard-bubble-updates-back-btn-container" style="height: 85px;"></div>
                </div>
            </div>
        </div>

    </div>
    <div class="back">

        <div class="widget widget-inverse widget-scroll" data-scroll-height="165px">
            <div class="widget-head">
                <button class="btn btn-xs btn-default float-right"><i class="fa fa-times"></i></button>
                <h4 class="heading"><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_updates') ?></h4>
            </div>
            <div class="widget-body padding-none">

                <div class="back-container">
                    <table class="table table-condensed">
                        <!-- Table body -->
                        <tbody class="dashboard-bubble-updates-list">

                        <!-- Table row -->
                        <tr>
                            <td class="center"><strong><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_updates_module') ?></strong></td>
                            <td class="center"><strong><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_updates_current_version') ?></strong></td>
                            <td class="center"><strong><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_updates_newest_version') ?></strong></td>
                        </tr>
                        <!-- // Table row END -->
                        </tbody>
                        <!-- // Table body END -->

                    </table>
                    <!-- // Table END -->

                </div>

            </div>
        </div>
    </div>
</div>