<div class="col-md-3 col-sm-6">
    <div class="panel-3d melis-dashboard-bubble-plugin melis-dashboard-bubble-news-melis-plugin">
        <div class="front">

            <div class="widget text-center">
                <div class="widget-body padding-none">
                    <div>
                        <div class="innerAll bg-inverse">
                            <p class="lead text-white strong margin-none"><i class="fa fa-list-alt"></i><br/><span id="melis-news-bubble-plugin-counter">0</span> Melis News</p>
                        </div>
                        <div id="dashboard-bubble-news-back-btn-container" class="innerAll" style="height: 85px;">
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="back">

            <div class="widget widget-inverse widget-scroll" data-scroll-height="165px">
                <div class="widget-head">
                    <button class="btn btn-xs btn-default float-right"><i class="fa fa-times"></i></button>
                    <h4 class="heading">Melis News</h4>
                </div>
                <div class="widget-body padding-none">
                    <div id="melis-news-bubble-plugin-news-list">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>