<div class="panel-3d melis-dashboard-bubble-plugin melis-dashboard-bubble-chat-plugin" style="">
    <div class="front">

        <div class="widget text-center">
            <div class="widget-body padding-none">
                <div>
                    <div class="bg-info innerAll">
                        <p class="lead strong margin-none text-white">
                            <i class="fa fa-fw fa-comment"></i>
                            <br/>
                            <span class="dashboard-bubble-chat-plugin-counter">0</span>
                            <span class="dashboard-bubble-chat-plugin-text"><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_message') ?></span>
                        </p>
                    </div>
                    <div class="innerAll dashboard-bubble-chat-back-btn-container" style="height: 85px;"></div>
                </div>
            </div>
        </div>

    </div>
    <div class="back">

        <div class="widget widget-inverse widget-scroll" data-scroll-height="165px">
            <div class="widget-head">
                <button class="btn btn-xs btn-default float-right"><i class="fa fa-times"></i></button>
                <h4 class="heading"><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_messages') ?></h4>
            </div>
            <div class="widget-body padding-none">

                <div class="back-container dashboard-bubble-chat-plugin-list">
                </div>

            </div>
        </div>
    </div>
</div>