<div class="panel-3d melis-dashboard-bubble-plugin melis-dashboard-bubble-news-melis-plugin" style=""">
    <div class="front">
        <div class="widget text-center">
            <div class="widget-body padding-none">
                <div class="front-content">
                    <div class="innerAll bg-inverse">
                        <p class="lead text-white strong margin-none">
                            <i class="fa fa-list-alt"></i>
                            <br/>
                            <span class="melis-news-bubble-plugin-counter">0</span>
                            <span class="melis-news-bubble-plugin-text"><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_melis_news') ?></span>
                        </p>
                    </div>
                    <div class="innerAll dashboard-bubble-news-back-btn-container" style="height: 85px;"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="back">
        <div class="widget widget-inverse widget-scroll" data-scroll-height="165px">
            <div class="widget-head">
                <button class="btn btn-xs btn-default float-right"><i class="fa fa-times"></i></button>
                <h4 class="heading"><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_melis_news') ?></h4>
            </div>
            <div class="widget-body padding-none">
                <div class="back-container melis-news-bubble-plugin-news-list"></div>
            </div>
        </div>
    </div>
</div>