<div class="panel-3d melis-dashboard-bubble-plugin">
    <div class="front">

        <div class="widget text-center">
            <div class="widget-body padding-none">
                <div>
                    <div class="innerAll bg-success">
                        <p class="lead strong margin-none text-white"><i class="fa fa-fw fa-bell"></i><br/><span id="bubble-notification-plugin-counter">0</span> <?= $this->translate('tr_meliscore_dashboard_bubble_plugins_notifications') ?></p>
                    </div>
                    <div id="dashboard-bubble-notifications-back-btn-container" class="innerAll" style="height: 85px;"></div>
                </div>
            </div>
        </div>

    </div>
    <div class="back">
        <div class="widget widget-inverse widget-scroll" data-scroll-height="165px">
            <div class="widget-head">
                <button class="btn btn-xs btn-default float-right"><i class="fa fa-times"></i></button>
                <h4 class="heading"><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_notifications') ?></h4>
            </div>
            <div class="widget-body padding-none">
                <div class="back-container">
                    <table class="table table-condensed">
                        <!-- Table body -->
                        <tbody id="bubble-notifications-list"></tbody>
                        <!-- // Table body END -->
                    </table>
                    <!-- // Table END -->
                </div>
            </div>
        </div>
    </div>
</div>