<?php
	$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$melisKey = 'data-melisKey="'.$this->zoneconfig['conf']['melisKey'].'"';
?>

<div class="melis-core-dashboard-dnd-box" <?= $melisKey.' '.$id; ?>>
    <div class="melis-core-dashboard-dnd-fix-menu">
        <div class="melis-core-dashboard-dnd-title"><?php echo $this->translate('tr_melisore_Plugins')?></div>
        <div class="melis-core-dashboard-plugin-filter-box">
            <?php if(!empty($this->plugins)) { ?>
                <?php foreach ($this->plugins As $module => $plugins){ ?>
                    <div class="melis-core-dashboard-ps-box">
                        <span class="melis-core-dashboard-filter-btn"><?php echo $this->translate('tr_PluginSection_'.strtolower($module)) ?><i class="fa fa-angle-down"></i></span>
                        <div class="melis-core-dashboard-plugin-snippets-box">
                            <?php foreach ($plugins As $plugin => $pluginDetails){ ?>
                                <div class="melis-core-dashboard-plugin-snippets" title="<?php echo $this->translate($pluginDetails['description'])?>">
                                    <div class="hidden plugin-json-config"><?php echo $pluginDetails['pluginRaw'] ?></div>
                                    <img src="<?php echo $pluginDetails['thumbnail']?>" alt="" width="194px">
                                    <span class="melis-core-dashboard-plugin-title"><?php echo $this->translate($pluginDetails['name'])?></span>
                                </div>
                            <?php }?>
                        </div>
                    </div>
                <?php }?>
            <?php } else { ?>
                <div class="no-plugin-on-menu">
                    <span><?= $this->translate('tr_melisdashboardplugin_plugin_no_plugin_on_menu'); ?></span>
                </div>
            <?php } ?>
        </div>
        <div class="melis-core-dashboard-plugin-delete-all">
            <button class='btn btn-primary btn-md' id='dashboard-plugin-delete-all'><?= $this->translate('tr_melisore_remove_all_plugins');?></button>
        </div>
    </div>
    <div id="melisDashBoardPluginBtn" title="Dashboard Plugins">
        <span class="melis-dashboard-new-plugin hidden">NEW</span>
        <i class="fa fa-plug fa-lg"></i>
    </div>
</div>