<?php
	$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$melisKey = 'data-melisKey="'.$this->zoneconfig['conf']['melisKey'].'"';
    $ctrNewPlugins = 0;
    $newPluginNotif = $this->newPluginNotification;

?>

<div class="melis-core-dashboard-dnd-box" <?= $melisKey.' '.$id; ?>>
    <div class="melis-core-dashboard-dnd-fix-menu">
        <div id="dashboardPluginsMenuLoader">

        </div>
        <div id="dashboardMenuContent">
            <!-- loads content here -->
        </div>
    </div>
    <div id="melisDashBoardPluginBtn" title="Dashboard Plugins">
        <?php if ($ctrNewPlugins > 0 ) {?>
            <?php
                // latesplugin installed
                $latestPlugin = $this->latestPluginInstalled;
                $latestPluginDatetime = $latestPlugin['latest_plugin_datetime'];
                // duration of new icon on menu handler
                $dateTimeElapse = date('Y-m-d h:i:s',strtotime("+$newPluginNotif day",strtotime($latestPluginDatetime)));
                $dateToday      = date('Y-m-d h:i:s');
            ?>
            <?php if ($dateToday < $dateTimeElapse) {?>
                <span class="melis-dashboard-new-plugin">
                    <span class="new-plugin-indicator">NEW!</span>
                </span>
            <?php }?>
        <?php }?>
        <i class="fa fa-plug fa-lg"></i>
    </div>
</div>