<!-- <div class="grid-stack" > -->
<div class="grid-stack" data-dashboard-id="<?php echo $this->dashboardId?>">
	<?php echo $this->htmlPlugins ?>
	<div class="grid-stack-item grid-stack-animate ui-draggable ui-resizable ui-resizable-autohide" data-gs-id="RecentUserActivity_1537962319" data-gs-x="6" data-gs-y="0" data-gs-width="6" data-gs-height="4" data-gs-no-move="yes" data-gs-no-resize="yes">
	    
	</div>
</div>