<div class="grid-stack-item  grid-stack-animate"
     data-gs-id="<?php echo $this->pluginConfig['datas']['plugin_id']?>"
     data-gs-x="<?php echo $this->pluginConfig['datas']['x-axis']?>"
     data-gs-y="<?php echo $this->pluginConfig['datas']['y-axis']?>"
     data-gs-width="<?php echo $this->pluginConfig['datas']['width']?>"
     data-gs-height="<?php echo $this->pluginConfig['datas']['height']?>">
    <div class="grid-stack-item-content">
        <div class="widget widget-inverse">
            <div class="widget-parent">
                <div class="widget-head">
                    <div class="btn-group pull-right btn-group-xs">
                    	<a class="btn btn-default dashboard-plugin-delete" <?php echo !empty($this->deleteCallBack) ? 'data-callback="' . $this->deleteCallBack . '"' : '' ?>><i class="fa fa-trash"></i></a>
                        <a class="btn btn-default dashboard-plugin-refresh"><i class="fa fa-refresh"></i></a>
                    </div>
                    <h3 class="heading"><i class="<?php echo $this->translate($this->pluginConfig['datas']['icon']); ?>"></i> <?php echo $this->translate($this->pluginConfig['datas']['name']); ?></h3>
                </div>
                <div class="widget-body padding-none">
                	<?php echo $this->pluginView ?>
                	<div class="hidden dashboard-plugin-json-config">
                		<?php 
                		    /**
                		     * Plugin config hidden, this plugin congif
                		     * used to generate plugin by using this to a POST/GET request
                		     * in generating plugin
                		     */
                		    echo $this->jsonPluginConfig
        		        ?>
                	</div>
                </div>
            </div>
        </div>
    </div>
</div>