<div class="grid-stack-item  grid-stack-animate"
     data-gs-id="Dashboard"
     data-gs-x="0" data-gs-y="0"
     data-gs-width="6"
     data-gs-height="6">
    <div class="grid-stack-item-content">
        <div class="widget widget-inverse">
            <div class="widget-parent">
                <div class="widget-head">
                    <div class="btn-group pull-right btn-group-xs">
                        <a class="btn btn-default"><i class="fa fa-refresh"></i></a>
                        <a class="btn btn-default"><i class="fa fa-info-circle"></i></a>
                        <a class="btn btn-default"><i class="fa fa-arrows"></i></a>
                    </div>
                    <h3 class="heading"><i class="<?php echo $this->translate($this->pluginConfig['icon']); ?>"></i> <?php echo $this->translate($this->pluginConfig['name']); ?></h3>
                </div>
                <div class="widget-body padding-none">
                    <!--<div class="alert alert-warning">
                        <h3>Plugin container</h3>
                    </div>-->
                    <pre><?php //print_r($this->pluginConfig)?></pre>
                    <?php echo $this->pluginView ?>
                </div>
            </div>
        </div>
    </div
</div>