<div id="<?= $this->zoneconfig['conf']['id'] ?>" data-melisKey="<?= $this->zoneconfig['conf']['melisKey'] ?>" class="tab-pane container-level-a">
    <div class="tab-pane page-loaded include-content-xhr active innerAll spacing-x2">
        <div id="bubble-plugin" class="mb-20px">
            <div class="bubble-plugin-show-hide-button">
                <?php if ($this->showBubblePlugins) : ?>
                    <button id="btn-hide-bubble-plugins" class="btn btn-info btn-regular">Hide plugin info <i class="fa fa-arrow-up"></i><!-- $this->translate('tr_meliscore_dashboard_bubble_plugins_hide') --></button>
                <?php else : ?>
                    <button id="btn-show-bubble-plugins" class="btn btn-info btn-regular">Display plugin info <i class="fa fa-arrow-down"></i><!-- $this->translate('tr_meliscore_dashboard_bubble_plugins_show') --></button>
                <?php endif; ?>
            </div>
            <div class="bubble-plugin-flip-cards <?= (! $this->showBubblePlugins) ? 'hidden' : '' ?>">
                <?= $this->MelisCoreDashboardBubblePlugin() ?>
            </div>
        </div>
    </div>
</div>