<div class="dashboard-page-head-container">
    <div class="bg-white innerAll">
        <div class="bg-white" id="<?= $this->zoneconfig['conf']['id'] ?>" data-meliskey="<?= $this->zoneconfig['conf']['melisKey'] ?>">
            <div class="row">
                <div class="me-hl col-12 col-sm-5 col-md-6">
                    <?php if ($this->showBubblePlugins) : ?>
                        <button id="btn-hide-bubble-plugins" class="btn btn-info btn-regular float-right"><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_hide') ?></button>
                    <?php else : ?>
                        <button id="btn-show-bubble-plugins" class="btn btn-info btn-regular float-right"><?= $this->translate('tr_meliscore_dashboard_bubble_plugins_show') ?></button>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
