<div id="<?= $this->dashboardId ?>" data-melisKey="<?= $this->melisKey ?>"
     class="tab-pane container-level-a tab-panel-dashboard">
    <div class="tab-pane page-loaded include-content-xhr full-width active innerAll spacing-x2 melis-dashboard-plugins">
        <?php
        $plugins = $this->MelisDashboardDragDropZone($this->dashboardId);
        if ($this->hasPlugins):
            /** Number of plugins loaded inside the dashboard's last saved state */
            $pluginCount = substr_count($plugins, "data-gs-id");

            if ($pluginCount === 0):
                /** Show dashboard message & dashboard plugin menu */?>
                <i class="fa fa-location-arrow location-arrow" aria-hidden="true"></i>
                <div id="melis-core-dashboard-msg">
                    <div class="alert alert-warning no-plugins" role="alert">
                        <p><?= $this->translate('tr_meliscore_melis_dashboard_no_plugins_to_load'); ?></p>
                    </div>
                    <script type="text/javascript">
                        (function () {
                            // Waits for jQuery to be available before executing the function
                            waitForJquery(showDashboardPluginMenu);

                            function waitForJquery(method) {
                                if (window.jQuery && typeof melisDashBoardDragnDrop.$body !== "undefined") {
                                    method();
                                } else {
                                    setTimeout(function () {
                                        waitForJquery(method)
                                    }, 50);
                                }
                            }

                            /**
                             * Automatically open plugin menu when dashboard is empty &
                             * there is an available plugin
                             */
                            function showDashboardPluginMenu() {
                                let pluginMenu = melisDashBoardDragnDrop.$body.find("#id_meliscore_center_dashboard_menu");
                                if (pluginMenu.length > 0) {
                                    pluginMenu.addClass("shown");
                                }
                            }
                        }());
                    </script>
                </div>
            <?php endif;
        else: ?>
            <div class="alert alert-warning no-dashboard-access" role="alert">
                <p><?= $this->translate('tr_meliscore_melis_dashboard_no_access'); ?></p>
            </div>
            <?php
        endif;
        echo $plugins; ?>
    </div>
</div>