<div id="<?= $this->dashboardId ?>" data-melisKey="<?= $this->melisKey ?>"
     class="tab-pane container-level-a tab-panel-dashboard">
    <div class="tab-pane page-loaded include-content-xhr full-width active innerAll spacing-x2 melis-dashboard-plugins">
        <div id="melis-core-dashboard-msg" style="display:none;" data-active-mods="<?= $this->activeMods; ?>">
            <div class="alert alert-info no-plugins" role="alert">
                <p><?= $this->translate('tr_meliscore_melis_dashboard_no_plugins_to_load'); ?></p>
            </div>
        </div>
        <?php
        $plugins = $this->MelisDashboardDragDropZone($this->dashboardId);
        if ($this->hasPlugins):
            /** Number of plugins loaded inside the dashboard's last saved state */
            $pluginCount = substr_count($plugins, "data-gs-id");

            if ($pluginCount === 0):?>
                <script type="text/javascript">
                    (function () {
                        // Waits for jQuery to be available before executing the function
                        waitForJquery(showDashboardPluginMenu);

                        function waitForJquery(method) {
                            if (window.jQuery && typeof melisDashBoardDragnDrop !== "undefined") {
                                method();
                            } else {
                                setTimeout(function () {
                                    waitForJquery(method)
                                }, 50);
                            }
                        }

                        /**
                         * Automatically open plugin menu when dashboard is empty &
                         * there is an available plugin
                         */
                        function showDashboardPluginMenu() {
                            $("#melis-core-dashboard-msg").show();
                            var pluginMenu = $("body").find("#id_meliscore_center_dashboard_menu");
                            if (pluginMenu.length > 0) {
                                if ( ! pluginMenu.hasClass("shown") ) {
                                    //pluginMenu.addClass("shown");
                                    //melisCore.showToggleDashboardPluginMenu();
                                    $("#melisDashBoardPluginBtn").trigger("click");
                                }
                            }
                        }
                    }());
                </script>
            <?php endif;
        else: ?>
            <div class="alert alert-warning no-dashboard-access" role="alert">
                <p><?= $this->translate('tr_meliscore_melis_dashboard_no_access'); ?></p>
            </div>
            <?php
        endif;
        echo $plugins; ?>
    </div>
</div>