UPDATE `melis_core_platform_scheme` SET `pscheme_form_elements` = '{   
    "melis_core_platform_theme_form_bg_color": "#fff",
    "melis_core_platform_theme_form_text_color": "#686868",
    "melis_core_platform_theme_form_select_option_bg_color": "#fff",
    "melis_core_platform_theme_form_select_option_text_color": "#686868",
    "melis_core_platform_theme_form_input_elements_border_radius": "0",
    "melis_core_platform_theme_form_input_elements_text_color": "#444",
    "melis_core_platform_theme_form_input_elements_border_width": "0",
    "melis_core_platform_theme_form_input_elements_border_color": "#dee2e6",
    "melis_core_platform_theme_form_input_elements_bg_color": "#fff",
    "melis_core_platform_theme_form_input_text_disable_readonly_bg_color": "#e9ecef",
    "melis_core_platform_theme_form_input_text_disable_readonly_border_color": "#dee2e6",
    "melis_core_platform_theme_form_input_text_disable_readonly_text_color": "#dee2e6",
    "melis_core_platform_theme_form_button_submit_bg_color": "#fff",
    "melis_core_platform_theme_form_button_submit_text_color": "#444",
    "melis_core_platform_theme_form_button_submit_border_radius": "0",
    "melis_core_platform_theme_form_button_submit_border_width": "0",
    "melis_core_platform_theme_form_button_submit_border_color": "#444",
    "melis_core_platform_theme_form_button_submit_hover_bg_color": "#72af46",
    "melis_core_platform_theme_form_button_submit_hover_border_color": "#72af46",
    "melis_core_platform_theme_form_button_submit_hover_text_icon_color": "#fff",
    "melis_core_platform_theme_form_button_cancel_bg_color": "#fff",
    "melis_core_platform_theme_form_button_cancel_text_icon_color":"#bd362f",
    "melis_core_platform_theme_form_button_cancel_border_radius_size":"0",
    "melis_core_platform_theme_form_button_cancel_border_width":"0",
    "melis_core_platform_theme_form_button_cancel_border_color":"#bd362f",
    "melis_core_platform_theme_form_button_cancel_hover_bg_color":"#bd362f",
    "melis_core_platform_theme_form_button_cancel_hover_border_color" : "#bd362f",
    "melis_core_platform_theme_form_button_cancel_hover_text_icon_color" : "#fff"
}'
WHERE `melis_core_platform_scheme`.`pscheme_id` IN (1,2);