ALTER TABLE `melis_core_platform_scheme` ADD `pscheme_drag_drop` TEXT NULL AFTER `pscheme_datepicker`;

UPDATE `melis_core_platform_scheme` SET `pscheme_drag_drop` = '{"melis_core_platform_theme_dnd_plugins_box_bg_color": "#373737", 
        "melis_core_platform_theme_dnd_plugins_box_border_width": "12", 
        "melis_core_platform_theme_dnd_plugins_box_border_bottom_and_left_color": "#e61c23", 
        "melis_core_platform_theme_dnd_plugins_box_title_bg_color": "#e61c23", 
        "melis_core_platform_theme_dnd_plugins_box_title_text_color": "#fff", 
        "melis_core_platform_theme_dnd_plugins_box_title_line_height": "12", 
        "melis_core_platform_theme_dnd_plugins_box_title_text_font_styles": "", 
        "melis_core_platform_theme_dnd_plugins_box_title_letter_spacing": "0", 
        "melis_core_platform_theme_dnd_plugins_box_title_text_align": "center", 
        "melis_core_platform_theme_dnd_plugins_box_btn_bg_color": "#e61c23",
        "melis_core_platform_theme_dnd_plugins_box_btn_border_radius": "",
        "melis_core_platform_theme_dnd_plugins_box_btn_icon_color": "#fff",
        "melis_core_platform_theme_dnd_plugins_box_btn_icon_font_size": "12",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_bg_color": "#e61c23",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_border_bottom_width": "",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_border_bottom_color": "#2c2c2c",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_text_color": "#fff",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_font_size": "12",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_letter_spacing": "12",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_cms_filter_text_indent": "12",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_hover_bg_color": "#2c2c2c",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_hover_border_color": "#2c2c2c",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_text_align": "center",
        "melis_core_platform_theme_dnd_plugins_box_category_btn_text_opacity": "12",
        "melis_core_platform_theme_dnd_plugins_box_cms_category_button_active_bg_color": "#e61c23",
        "melis_core_platform_theme_dnd_plugins_box_cms_category_button_active_border_color": "#e61c23",
        "melis_core_platform_theme_dnd_plugins_box_cms_category_box_border_bottom_color": "#e61c23",
        "melis_core_platform_theme_dnd_zone_plugin_outline_hover_color": "#e61c23",
        "melis_core_platform_theme_dnd_zone_plugin_box_shadow_color": "#e61c23",
        "melis_core_platform_theme_dnd_plugin_sub_tools_bg_color": "#e61c23",
        "melis_core_platform_theme_dnd_layout_column_button_bg_color": "#e61c23",
        "melis_core_platform_theme_dnd_layout_column_button_border_color": "#e61c23",
        "melis_core_platform_theme_dnd_layout_column_button_hover_color": "#fff",
        "melis_core_platform_theme_dnd_layout_wrapper_outline_color": "#e61c23",
        "melis_core_platform_theme_dnd_layout_buttons_bg_color": "#e61c23",
        "melis_core_platform_theme_dnd_layout_column_button_bg_red_color": "#e61c23",
        "melis_core_platform_theme_dnd_layout_column_button_bg_red_border_color": "#e61c23",
        "melis_core_platform_theme_dnd_plugin_box_module_plugin_title_text_color": "#fff",
        "melis_core_platform_theme_dnd_plugin_box_module_title_opacity": "1",
        "melis_core_platform_theme_dnd_no_content_before_after_pseudo_element_color": "#ce5459",
        "melis_core_platform_theme_dnd_zone_hover_outline_color": "#ce5459",
        "melis_core_platform_theme_dnd_zone_hover_shadow_color": "#ce5459",
        "melis_core_platform_theme_dnd_zone_icons_color": "#fff"
}'
WHERE `melis_core_platform_scheme`.`pscheme_id` IN (1,2);
