<?php
    $id = $this->zoneconfig['conf']['id'];
    $melisKey = $this->zoneconfig['conf']['melisKey'];
?>
<div id="<?php echo $id ?>" data-melisKey="<?php echo $melisKey; ?>" class="tab-pane container-level-a">
    <?php
        if(!empty($this->zoneconfig['interface']))
        {
            foreach($this->zoneconfig['interface'] as $keyConfig => $val)
            {
                echo $this->$keyConfig;
            }
        }
    ?>
</div>