<?php 
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>

<div <?= $id; ?> data-melisKey="<?= $data_melisKey; ?>">
	<div class="spacing-x2 innerAll">
        <?php
        if(!empty($this->warningLogs)) {
            ?>
            <div class="alert alert-danger">
                <h4><i class="fa fa-warning"></i> Warning</h4>
                <?php
                foreach($this->warningLogs as $log) {
                    echo '<li>' . $log . '</li>';
                }
                ?>
            </div>
            <?php
        }
        ?>
		<?php 
		$this->melisGenericTable()->setTable(array(
		    'id' => 'tableLanguages',
		    'class' => 'table table-striped table-primary dt-responsive nowrap',
		    'cellspacing' => '0',
		    'width' => '100%'
		));
		
		$columns = array();
		$columnStyle = array();
		
		foreach($this->tableColumns as $columnText)
		{
		    $columns[] = $columnText['text'];
		}

		// set table columns
		$this->MelisGenericTable()->setColumns($columns);

		echo $this->melisGenericTable()->renderTable();
		
		?>
		<script type="text/javascript">
		// render table to DataTable plugin
		$(document).ready(function() {
			<?= $this->getToolDataTableConfig; ?>
			$(document).on("init.dt", function(e, settings) {
				$('#tableLanguages td:nth-child(3):contains("en_EN")').parent().find('.btnLangUpdate').hide();
				$('#tableLanguages tbody tr').each(function(){
					var tableRow = $(this);
					var applyButton = tableRow.find('.btnLangApply');
					var langName = tableRow.find('td:nth-child(2)').text();
					
					applyButton.attr('title', applyButton.attr('title') + langName);
					
				});
			});
		});
		</script>

		
		
		
	</div> 
</div>