<div class="timeline-navigation innerAll announcement-pagination">
    <nav>
        <ul class="pagination float-right margin-none">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="page-item">
                    <a data-next="<?= $this->previous;?>" href="#" class="page-link">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <a href="#" class="page-link">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php
                // To limit the number of pagination before and after the current page
                if ($page >= ($this->current - $this->nbPageBeforeAfter) && $page <= ($this->current + $this->nbPageBeforeAfter)):
                    ?>
                    <?php if ($page != $this->current): ?>
                    <li class="page-item">
                        <a class="page-link" data-next="<?= $page; ?>" href="#">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="page-item active">
                        <a class="page-link" href="#"><span ><?php echo $page; ?></span></a>
                    </li>
                <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Previous page link -->
            <?php if (isset($this->next)): ?>
                <li class="page-item">
                    <a class="page-link" data-next="<?= $this->next;?>"  href="#">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
</div>