-- MySQL Script generated by MySQL Workbench
-- 05/25/16 11:04:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melisv2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `melis_core_lang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_core_lang` ;

CREATE TABLE IF NOT EXISTS `melis_core_lang` (
  `lang_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `lang_locale` VARCHAR(10) NOT NULL DEFAULT 'en_EN' COMMENT '',
  `lang_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`lang_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'Languages available';


-- -----------------------------------------------------
-- Table `melis_core_platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_core_platform` ;

CREATE TABLE IF NOT EXISTS `melis_core_platform` (
  `plf_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `plf_name` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`plf_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'Defines environement used for the project';


-- -----------------------------------------------------
-- Table `melis_core_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_core_user_role` ;

CREATE TABLE IF NOT EXISTS `melis_core_user_role` (
  `urole_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `urole_name` VARCHAR(255) NOT NULL COMMENT '',
  `urole_rights` TEXT NULL DEFAULT NULL COMMENT '',
  `urole_creation_date` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`urole_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Melis Users\' roles';


-- -----------------------------------------------------
-- Table `melis_core_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `melis_core_user` ;

CREATE TABLE IF NOT EXISTS `melis_core_user` (
  `usr_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `usr_status` INT(11) NOT NULL DEFAULT '1' COMMENT '',
  `usr_login` VARCHAR(255) NOT NULL COMMENT '',
  `usr_email` VARCHAR(255) NOT NULL COMMENT '',
  `usr_password` VARCHAR(255) NOT NULL COMMENT '',
  `usr_firstname` VARCHAR(255) NOT NULL COMMENT '',
  `usr_lastname` VARCHAR(255) NOT NULL COMMENT '',
  `usr_lang_id` INT(11) NOT NULL DEFAULT 1 COMMENT '',
  `usr_role_id` INT(11) NOT NULL DEFAULT 1 COMMENT '',
  `usr_rights` TEXT NULL DEFAULT NULL COMMENT '',
  `usr_image` MEDIUMBLOB NULL DEFAULT NULL COMMENT '',
  `usr_creation_date` DATETIME NOT NULL COMMENT '',
  `usr_last_login_date` DATETIME NULL COMMENT '',
  PRIMARY KEY (`usr_id`)  COMMENT '',
  INDEX `roleId_idx` (`usr_role_id` ASC)  COMMENT '',
  INDEX `langId_idx` (`usr_lang_id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = 'Melis users';


--
-- Table structure for table `melis_core_lost_password`
--

CREATE TABLE IF NOT EXISTS `melis_core_lost_password` (
`rh_id` int(11) NOT NULL,
  `rh_login` varchar(255) NOT NULL,
  `rh_email` varchar(255) NOT NULL,
  `rh_hash` varchar(255) NOT NULL,
  `rh_date` datetime NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=9 ;


-- -----------------------------------------------------
-- Table `melis_core_bo_emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_core_bo_emails` (
  `boe_id` INT(11) NOT NULL AUTO_INCREMENT,
  `boe_name` VARCHAR(255) NOT NULL,
  `boe_code_name` VARCHAR(255) NOT NULL,
  `boe_from_name` VARCHAR(255) NOT NULL,
  `boe_from_email` VARCHAR(255) NOT NULL,
  `boe_reply_to` VARCHAR(255) NULL,
  `boe_tag_accepted_list` TEXT NULL,
  `boe_content_layout` VARCHAR(255) NULL,
  `boe_last_edit_date` DATETIME NOT NULL,
  `boe_last_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`boe_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `melis_core_bo_emails_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melis_core_bo_emails_details` (
  `boed_id` INT(11) NOT NULL AUTO_INCREMENT,
  `boed_email_id` INT(11) NOT NULL,
  `boed_lang_id` INT(11) NOT NULL,
  `boed_subject` VARCHAR(255) NOT NULL,
  `boed_html` LONGTEXT NOT NULL,
  `boed_text` TEXT NOT NULL,
  PRIMARY KEY (`boed_id`),
  INDEX `fk_melis_core_bo_emails_details_melis_core_bo_emails1_idx` (`boed_email_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

--
-- Indexes for dumped tables
--

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


