-- MySQL Script generated by MySQL Workbench
-- 05/25/16 11:10:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Data for table `melis_core_lang`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_core_lang` (`lang_id`, `lang_locale`, `lang_name`) VALUES (1, 'en_EN', 'English');
INSERT INTO `melis_core_lang` (`lang_id`, `lang_locale`, `lang_name`) VALUES (2, 'fr_FR', 'Français');
COMMIT;


-- -----------------------------------------------------
-- Data for table `melis_core_user_role`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `melis_core_user_role` (`urole_id`, `urole_name`, `urole_rights`, `urole_creation_date`) VALUES (1, 'Custom', NULL, NOW());

COMMIT;

