<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
        $data_melisKey = $this->melisKey;
?>

<div <?php echo $id; ?> data-melisKey="<?php echo $data_melisKey; ?>">
	<?php 
    	$this->melisGenericTable()->setTable(array(
    	    'id' => 'tableMelisLogs',
    	    'class' => 'table table-striped table-primary dt-responsive nowrap',
    	    'cellspacing' => '0',
    	    'width' => '100%'
    	));
    	
    	$columns = array();
    	$columnStyle = array();
    	
    	foreach($this->tableColumns as $columnText)
    	{
    	    $columns[] = $columnText['text'];
    	}
    	
    	// set table columns
    	$this->MelisGenericTable()->setColumns($columns);
    	echo $this->melisGenericTable()->renderTable();
	?>
	<script type="text/javascript">
		<?php echo $this->getToolDataTableConfig; ?>
	</script>
</div>