<?php 
    $id = '';
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
        $data_melisKey = $this->melisKey;
?>

<div <?php echo $id; ?> data-melisKey="<?php echo $data_melisKey; ?>">
	<?php 
    	$this->melisGenericTable()->setTable(array(
    	    'id' => 'tableMelisLogs',
    	    'class' => 'table table-striped table-primary dt-responsive nowrap',
    	    'cellspacing' => '0',
    	    'width' => '100%'
    	));
    	
    	$columns = array();
    	$columnStyle = array();
    	
    	foreach($this->tableColumns as $columnText)
    	{
    	    $columns[] = $columnText['text'];
    	}
    	
    	// set table columns
    	$this->MelisGenericTable()->setColumns($columns);
    	echo $this->melisGenericTable()->renderTable();
	?>
	<script type="text/javascript">
		<?php echo $this->getToolDataTableConfig; ?>
		(function () {
			var $paginate = $(".dataTables_paginate"),
				$page_item = $paginate.find(".pagination li"),
				$page_link = $page_item.find("a");

				$page_item.addClass("page-item");
				$page_link.addClass("page-link");
		})();
	</script>
</div>