<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = $this->zoneconfig['conf']['id'];
    $data_melisKey = $this->melisKey;

    ?>

<div class="modal-content">
	<div class="modal-body padding-none">
		<div class="wizard">
			<div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                	<ul class="nav nav-tabs">
                		<li class="nav-item active">
                            <a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="nav-link glyphicons notes" data-bs-toggle="tab" aria-expanded="true"><i></i><?php echo $this->translate($this->title); ?>
                            </a>
                        </li>
            		</ul>
        		</div>
        		<div class="widget-body innerAll inner-2x">
        			<div class="tab-content">
        				<div class="tab-pane active" id="<?= $id ?>">
                            <?php
                            echo $this->form()->openTag($this->form);
                            echo $this->melisFieldCollection($this->form);
                            ?>

                            <div class="footer-modal d-flex flex-row justify-content-between">
                                <button type="button" data-bs-dismiss="modal" id="btn-export-logs-cancel" class="btn btn-danger float-left"><i class="fa fa-times"></i> <?php echo $this->translate('tr_meliscore_logs_cancel')?></button>
                                <button type="submit" class="btn btn-success" id="btn-export-logs"><i class="fa fa-file-text-o"></i>  <?php echo $this->translate('tr_meliscore_log_export_export_btn') ?></button>
                            </div>
                            <div class="clearfix"></div>

                            <?php echo $this->form()->closeTag();?>
                            <a href="#" id="exportNewTab" target="_blank" ></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function(){
        $("body").find("#log_user").select2({
            ajax: {
                type: 'POST',
                url: "/melis/MelisCore/ToolUser/getUsers",
                dataType: 'json',
                delay: 500,
                data: function (params) {
                    return {
                        'search': params.term, // search term
                        'page': params.page || 1, // pagination,
                        'length': 5 // results shown per page,
                    };
                },
                cache: true
            },
            width: '100%',
            disabled: false,
            language : {
                noResults:function() {
                    return translations.tr_melis_cms_user_selection_empty;
                },
                searching: function () {
                    return translations.tr_melis_cms_user_searching;
                }
            },
            allowClear : true,
            placeholder: translations.tr_meliscore_common_all,
        }).
        // These following events were added to prevent select2 from opening when clearing
        on('select2:unselecting', function() {
            $(this).data('unselecting', true);
        }).on('select2:opening', function(e) {
            if ($(this).data('unselecting')) {
                $(this).removeData('unselecting');
                e.preventDefault();
            }
        });

        $("#logExportForm .form-group:nth-child(3) label").addClass("d-flex flex-row justify-content-between");
    });
</script>