<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
}
?>
<div data-melisKey='<?= $this->melisKey ?>' class="tab-pane fade" id="<?= $this->zoneconfig['conf']['id']?>" role="tabpanel" aria-labelledby="<?= $this->zoneconfig['conf']['id'] ?>">
    <?php
    $id = '';
    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
    ?>

    <div <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
        <div class="">
            <?php

            $this->melisGenericTable()->setTable(array(
                'id' => 'tableGdprAutoDeleteLogs',
                'class' => 'table table-striped table-primary dt-responsive nowrap',
                'cellspacing' => '0',
                'width' => '100%'
            ));
            $columns = array();
            $columnStyle = array();
            foreach($this->tableColumns as $columnText)
            {
                $columns[] = $columnText['text'];
            }
            $this->melisGenericTable()->setColumns($columns);

            echo $this->melisGenericTable()->renderTable();
            ?>
            <script type="text/javascript">
                $(document).ready(function() {
                    <?= $this->toolDataTableConfig; ?>
                });
            </script>
        </div>
    </div>
</div>
