<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id'])) {
    $id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
}
?>

<div data-melisKey='<?= $this->melisKey ?>' class="tab-pane show active" id="<?= $this->zoneconfig['conf']['id']?>" role="tabpanel" aria-labelledby="<?= $this->zoneconfig['conf']['id'] ?>">
    <div id="accordion-cron-configuration">
        <div class="card" style="border: none;">
            <div id="cron-configuration" >
                <a data-toggle="collapse" data-target="#cron-configuration-content" aria-expanded="true" aria-controls="cron-configuration" >
                    <h5 class="accordion-heading-title">Cron Config</h5>
                </a>
            </div>
            <div id="cron-configuration-content" class="collapse show accordion-content-bg" aria-labelledby="cron-configuration-content" data-parent="#accordion-cron-configuration">
                <div class="row">
                    <div class="col-md-6">
                        <?php
                            $this->formCronConfig->prepare();
                            echo $this->form()->openTag($this->formCronConfig);
                            echo $this->melisFieldCollection($this->formCronConfig);
                            echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="accordion-email-setup">
        <div class="card" style="border: none;">
            <div id="email-setup" >
                <a data-toggle="collapse" data-target="#email-setup-content" aria-expanded="true" aria-controls="email-setup" >
                    <h5 class="accordion-heading-title">Email Setup</h5>
                </a>
            </div>
            <div id="email-setup-content" class="collapse show accordion-content-bg" aria-labelledby="email-setup-content" data-parent="#accordion-email-setup">
                <div class="row">
                    <div class="col-md-6">
                        <?php
                            $this->formEmailSetup->prepare();
                            echo $this->form()->openTag($this->formEmailSetup);
                            echo $this->melisFieldCollection($this->formEmailSetup);
                            echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
