<?php
    // use default colors if platform scheme table is empty
    $primaryColor   = $this->melis_core_platform_color_primary_color   ?: '#981a1f';
    $secondaryColor = $this->melis_core_platform_color_secondary_color ?: '#ad6565';
?>
/* =============== Primary Color =============== */
.datepicker .table-condensed tr td.active, 
.datepicker .table-condensed tr td.active:hover, 
.datepicker .table-condensed tr td.active.disabled, 
.datepicker .table-condensed tr td.active.disabled:hover,
.datepicker table tr td span.active, 
.datepicker table tr td span.active:hover, 
.datepicker table tr td span.active.disabled, 
.datepicker table tr td span.active.disabled:hover {
    background: <?= $primaryColor; ?> !important;
}

.tabsbar ul.order-checkout-steps li a i:before {
    color: <?= $primaryColor; ?>;
}
.bootstrap-datetimepicker-widget table td span.active,
.bootstrap-datetimepicker-widget table td i.active,
.bootstrap-datetimepicker-widget table td.active,
.bootstrap-datetimepicker-widget table td.active:hover {
    background-color: <?= $primaryColor; ?> !important;
    color: #fff;
}
#convo-content #chat-container .my-msg {
    background-color: <?= $primaryColor; ?>;
}

#convo-content .chat-contact-name {
    color: <?= $primaryColor; ?>;
}

.media-msgrBody .text-danger {
    color: <?= $primaryColor; ?> !important;
}

#tableProductList .toolTipHoverEvent {
    color: <?= $primaryColor; ?> !important;
}

.btn-primary:not(:disabled):not(.disabled).active,
.btn-primary:not(:disabled):not(.disabled):active,
.show>.btn-primary.dropdown-toggle {
    background-color: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}

.footer a,
a:hover {
    color: <?= $primaryColor; ?>;
}

.jstree-proton .jstree-hovered,
.jstree-proton .jstree-anchor:hover,
.jstree-proton .jstree-clicked,
body .navbar.main.navbar-primary {
    background-color: <?= $primaryColor; ?>;
}

#melis-navtabs-container-outer {
    background: <?= $primaryColor; ?>;
}

#melis-id-nav-bar-tabs {
    background: <?= $primaryColor; ?>;
}

.navbar.main.navbar-primary .nav > li.active > .dropdown-toggle,
.navbar.main.navbar-primary .nav > li.active .dropdown-toggle .fa,
.navbar.main.navbar-primary .nav > li.active .dropdown-toggle:hover,
.navbar.main.navbar-primary .nav > li.active .dropdown-toggle:hover .fa,
.navbar.main.navbar-primary .nav > li .dropdown-toggle:hover,
.navbar.main.navbar-primary .nav > li .dropdown-toggle:hover .fa {
    color: <?= $primaryColor; ?> !important;
}

.navbar.main.navbar-primary .nav > li > a:hover > i {
    color: <?= $primaryColor; ?> !important;
}

.nav-tabs.product-text-tab li.active a,
.nav-tabs.product-text-tab li.active:focus a,
.nav-tabs.product-text-tab li.active:active a,
.nav-tabs.product-text-tab li a:hover {
    background: <?= $primaryColor; ?>;
}

.navbar.main.navbar-primary .left-menu {
    background: <?= $primaryColor; ?>;
}

.navbar.main .nav.navbar-right {
    background: <?= $primaryColor; ?>;
}

.navbar.main .nav.navbar-right li:first-child {
    border-left: 1px solid <?= $secondaryColor; ?>;
}

.navbar.main .nav.navbar-right li {
    border-bottom: 1px solid <?= $secondaryColor; ?>;
}

.sidebar.sidebar-inverse .user-profile ul li.active,
.sidebar.sidebar-inverse .user-profile ul li.active:hover {
    border-color: <?= $primaryColor; ?>;
}

.sidebar.sidebar-inverse .user-profile ul li.active a,
.sidebar.sidebar-inverse .user-profile ul li.active:hover a {
    background: <?= $primaryColor; ?>;
}

.sidebar.sidebar-inverse > .sidebarMenuWrapper > ul li.active-menu.hasSubmenu > a[data-toggle="collapse"] {
    background-color: <?= $primaryColor; ?>;
}

/* Widgets */
.widget.widget-tabs>.widget-head ul li.active a.glyphicons,
.widget.widget-tabs>.widget-head ul li.active a.glyphicons i:before {
    color: <?= $primaryColor; ?>;
}

.widget.widget-tabs-icons-only-2>.widget-head ul li a.glyphicons:hover i:before {
    color: <?= $primaryColor; ?>;
}

.widget.widget-tabs-double-2>.widget-head ul li:hover a {
    color: <?= $primaryColor; ?>;
}

.widget.widget-tabs-double-2>.widget-head ul li:hover a i:before {
    color: <?= $primaryColor; ?>;
}

.wizard .widget.widget-tabs-double>.widget-head ul li a.glyphicons:hover {
    color: <?= $primaryColor; ?>;
}

.wizard .widget.widget-tabs-double>.widget-head ul li a.glyphicons:hover i:before,
.wizard .widget.widget-tabs-double>.widget-head ul li.active a.glyphicons:hover i:before {
    color: <?= $primaryColor; ?>;
}

.wizard .widget.widget-tabs-double>.widget-head ul li a.glyphicons:hover,
.wizard .widget.widget-tabs-double>.widget-head ul li.active a.glyphicons:hover {
    color: <?= $primaryColor; ?>;
}

.wizard.wizard-design .widget.widget-tabs-double>.widget-head ul li.active a.glyphicons,
.wizard.wizard-design .widget.widget-tabs-double>.widget-head ul li.active a.glyphicons i:before {
    color: <?= $primaryColor; ?>;
}

.navbar.main .nav.navbar-right .dropdown-menu li.active a,
.dropdown-menu li.active a,
.dropdown-menu li.active:hover a {
    background-color: <?= $primaryColor; ?>;
}

.widget.widget-tabs>.widget-head ul li.active a, 
.widget.widget-tabs-double>.widget-head ul li a .fa:before, 
.widget.widget-tabs>.widget-head ul li.active a .fa:before,
.mccom-dashboard-latest-heading .widget-head ul li.active > a i:before,
.navbar.main .nav.navbar-right .dropdown-menu li.active:hover a {
    color: <?= $primaryColor; ?>;
}


#id_meliscore_header_flash_messenger {
    border-left: 1px solid <?= $secondaryColor; ?> !important;
}

#tab-arrow-top {
    background-color: <?= $primaryColor; ?>;
}

.text-primary {
    color: <?= $primaryColor; ?> !important;
}

.ra-username {
    color: <?= $primaryColor; ?>;
}

/* Dashboard */
.bg-primary {
    background: <?= $primaryColor; ?> !important;
}

.overlay-loader {
    background: <?= $primaryColor; ?>;
}

.datepicker thead th.dow {
    background: <?= $primaryColor; ?> !important;
}

.table-primary thead th {
    border-color: <?= $primaryColor; ?>;
    background-color: <?= $primaryColor; ?>;
}

.pagination > li.active > a,
.pagination > li.active > a:focus,
.pagination > li.active > a:hover {
    background: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}

.pagination>li>a:hover,
.pagination>li.primary>a {
    background: <?= $primaryColor; ?>;
}

.pagination > .page-item.active > .page-link, 
.pagination > .page-item.active > .page-link:focus, 
.pagination > .page-item.active > .page-link:hover {
    background-color: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}

.bs-tooltip-auto[x-placement^=left] .arrow::before, 
.bs-tooltip-left .arrow::before {
    border-left-color: <?= $secondaryColor; ?>;
}

/* Buttons */
.btn-primary {
    background: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}
.btn-primary:active:hover,
.btn-primary[disabled]:hover {
    color: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
    background: #fff;
}



.btn-group.open .btn-primary.dropdown-toggle,
.btn-primary.disabled,
.btn-primary[disabled],
.btn-primary:hover,
.btn-primary:focus,
.btn-primary:active,
.btn-primary.active {
    color: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}

.btn-primary.btn-stroke {
    color: <?= $primaryColor; ?>;
}

.btn-primary.btn-stroke:hover,
.btn-primary.btn-stroke:focus,
.btn-primary.btn-stroke:active,
.btn-primary.btn-stroke.active {
    background: <?= $primaryColor; ?>;
}

/* Modal */
.modal-content .widget .widget-head {
    background: <?= $primaryColor; ?>;
}

/* Nav Tabs */
.tabsbar .nav-group-dropdown li .tab-element {
    background: <?= $primaryColor; ?>;
}
.tabsbar .nav-group-dropdown li:hover > .tab-element > i:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar .nav-group-dropdown li.active > a.tab-element > i:before {
    color: <?= $primaryColor; ?>;
}

.navbar.main.navbar-primary .tabsbar li:hover > .tab-element {
    color: <?= $primaryColor; ?>;
}

.tabsbar .nav-group-dropdown li.active > a.tab-element {
    color: <?= $primaryColor; ?> !important;
}

.tabsbar .has-sub.active > .tab-element i:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar .has-sub:hover > .tab-element:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar .has-sub.active-parent.on > .tab-element i:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar .has-sub.active-parent.on > .tab-element:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar .has-sub.active-parent.on > .tab-element {
    color: <?= $primaryColor; ?> !important;
}

.tabsbar .has-sub.active > .tab-element:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar.tabsbar-2 ul li.active {
    background: <?= $primaryColor; ?>;
}

.tabsbar ul li.active a {
    background: <?= $primaryColor; ?>;
}

.tabsbar.tabsbar-2 ul li:not(.active):hover a {
    color: <?= $primaryColor; ?>;
}

.tabsbar.tabsbar-2 ul li:not(.active):hover a i:before {
    color: <?= $primaryColor; ?>;
}

/* Accordion */
.tab-pane a.btn.a-accordion.collapsed:hover,
.tab-pane a.btn.a-accordion {
    border-color: <?= $primaryColor; ?>;
    background: <?= $primaryColor; ?>;
}

.tab-pane a.btn.a-accordion.collapsed {
    background: <?= $primaryColor; ?>;
}

.commerce-toggle .card-header,
.commerce-toggle .panel-heading {
    background-color: <?= $primaryColor; ?>;
}

.commerce-toggle .accordion-toggle,
.commerce-toggle .accordion-toggle {
    background-color: <?= $primaryColor; ?> !important;
}

.ranges li {
    color: <?= $primaryColor; ?>;
}

.ranges li.active {
    background: <?= $primaryColor; ?>;
    border: 1px solid <?= $primaryColor; ?>;
}

.ranges li:hover {
    background: <?= $primaryColor; ?>;
    border: 1px solid <?= $primaryColor; ?>;
}

textarea:focus,
input[type="text"]:focus,
input[type="password"]:focus,
input[type="datetime"]:focus,
input[type="datetime-local"]:focus,
input[type="date"]:focus,
input[type="month"]:focus,
input[type="time"]:focus,
input[type="week"]:focus,
input[type="number"]:focus,
input[type="email"]:focus,
input[type="url"]:focus,
input[type="search"]:focus,
input[type="tel"]:focus,
input[type="color"]:focus,
.uneditable-input:focus {
    border-left: 1px solid <?= $primaryColor; ?>;
}

.content-cont .nav-tabs.product-text-tab li.active a,
.content-cont .nav-tabs.product-text-tab li.active:focus a,
.content-cont .nav-tabs.product-text-tab li.active:active a,
.content-cont .nav-tabs.product-text-tab li a:hover {
    background: <?= $primaryColor; ?>;
}

.orderPaymentCouponLink {
    color: <?= $primaryColor; ?>;
}

/* Media Queries */
@media (min-width: 768px) {
    .navbar #melis-id-nav-bar-tabs > li {
        background: <?= $primaryColor; ?>;
    }

    .navbar #melis-id-nav-bar-tabs > li:hover > a {
        color: <?= $primaryColor; ?> !important;
    }

    .navbar #melis-id-nav-bar-tabs > li:hover > a > i {
        color: <?= $primaryColor; ?>;
    }

    .navbar #melis-id-nav-bar-tabs > li > a.close:hover:before {
        color: <?= $primaryColor; ?>;
    }

    .melis-tabprev,
    .melis-tabnext {
        background: <?= $primaryColor; ?>;
    }

    .melis-tabprev:hover,
    .melis-tabnext:hover {
        color: <?= $primaryColor; ?>;
    }
}

/* MarketPlace */
.melis-store .post-info a {
    color: <?= $primaryColor; ?>;
}

/* Modules */
.module-settings .ms-heading {
    background: <?= $primaryColor; ?>;
}

/* DragnDrop */
.melis-cms-dnd-box {
    border-bottom: 4px solid <?= $primaryColor;?>!important;
    border-left: 4px solid <?= $primaryColor;?>!important;
}
.melis-cms-dnd-title {
    background: <?= $primaryColor; ?>!important;
}
.m-plugin-sub-tools {
    background: <?= $primaryColor; ?>!important;
}
.module-display-heading .ms-heading {
    background: <?= $primaryColor; ?>!important;
}
.melis-cms-filter-btn-sub-category.active,
.melis-cms-ps-box .melis-cms-filter-btn.active, .melis-cms-category-btn.active {
    background: <?= $primaryColor; ?>!important;
    border-color: <?= $primaryColor; ?>!important;
}
.melis-ui-outlined:hover {
    outline: 1px solid <?= $primaryColor; ?>!important;
    box-shadow: 0 0 0 1px <?= $primaryColor; ?>!important;
    -webkit-box-shadow: 0 0 0 1px <?= $primaryColor; ?>!important;
    -moz-box-shadow: 0 0 0 1px <?= $primaryColor; ?>!important;
    -ms-box-shadow: 0 0 0 1px <?= $primaryColor; ?>!important;
    z-index: 9999996 !important;
}
.melis-cms-category-plugins-box {
    border-bottom-color: <?= $secondaryColor; ?> !important;
}

/* Commerce */
.red-box-panel h3 {
    border-bottom: 1px solid <?= $primaryColor; ?>;
    background: <?= $primaryColor; ?>;
}

.progress .progress-bar.progress-bar-danger {
    background: <?= $primaryColor; ?>;
}

.client-contact-address .default-card>.card-header,
.client-contact-address .panel-default>.panel-heading {
    background-color: <?= $primaryColor; ?>;
}

.widget-red {
    background: <?= $primaryColor; ?> !important;
}


.meliscms-search-box.sidebar-treeview-search .sbox-icon:hover {
    background: <?= $primaryColor; ?>;
}

.progress .progress-bar.progress-bar-primary {
    background:  <?= $primaryColor; ?>;
}

.rating span.star.active:before, .rating span.star.active~span.star:before {
    color: <?= $primaryColor; ?>;
}

.page-elements .innerAll.spacing-x2 .widget.widget-primary {
    background: <?= $primaryColor; ?>;
}

.resume-documents li a i {
    color: <?= $primaryColor; ?>;
}

.timeline-activity li.active i.list-icon {
    background-color: <?= $primaryColor; ?>;
    border: 2px solid <?= $primaryColor; ?>;
}

.timeline-activity li:hover i.list-icon,
.timeline-activity li.active:hover i.list-icon {
    border-color: <?= $primaryColor; ?>;
    color: <?= $primaryColor; ?>;
}

.select2-container--default .select2-results__option--highlighted[aria-selected] {
    background-color: <?= $primaryColor; ?>;
}

.table-pricing-2 th {
    background: <?= $primaryColor; ?>;
}

.list-group-1>li.active, .list-group-1>li.active:hover {
    background: <?= $primaryColor; ?>;
}

.table-primary tbody td.important {
    color: <?= $primaryColor; ?>;
}

.table-pricing-3>ul>li.active .body {
    border-color: <?= $secondaryColor; ?>;
    background-color: <?= $primaryColor; ?>;
}

.innerAll.bg-primary .media {
    background: <?= $primaryColor; ?>;
}

.layout-timeline ul.timeline > li.active::before {
    background: <?= $primaryColor; ?> none repeat scroll 0 0 !important;
}

.layout-timeline ul.timeline > li.active .type::before,
.layout-timeline ul.timeline > li.active .type::after {
    background: <?= $primaryColor; ?> none repeat scroll 0 0 !important;
}

.layout-timeline ul.timeline > li.active .type i::before {
    color: <?= $primaryColor; ?> !important;
}

.layout-timeline ul.timeline > li.active .type {
    color: <?= $primaryColor; ?> !important;
}

.pricing-table.primary .list-group {
    background: <?= $primaryColor; ?>;
}

.pricing-table.primary .caret {
    border-top-color: <?= $primaryColor; ?>;
}

.bwizard-steps li.active {
    background: <?= $primaryColor; ?>;
}

.bwizard-steps li.active:after {
    border-left-color: <?= $primaryColor; ?>;
}

.slider-nav .slick-track .slick-slide {
    background:  <?= $primaryColor; ?>;
}

.slider-nav .slick-track .slick-slide:before {
    border-top: 1px solid <?= $primaryColor; ?>;
    border-bottom: 1px solid <?= $primaryColor; ?>;
}

.fc-event, .fc-event:hover {
    background: <?= $primaryColor; ?>;
}

.event-icon {
    background: <?= $primaryColor; ?>;
}

.update-event:hover {
    background: <?= $primaryColor; ?>;
}

::-webkit-scrollbar-thumb {
    background: <?= $primaryColor; ?>;
}

.nicescroll-cursors {
    background: <?= $primaryColor; ?> !important;
}

.content-cont .widget.widget-tabs-double-2>.widget-head ul li a:hover {
color: <?= $primaryColor; ?>;
}

#external-events li {
    background: <?= $primaryColor; ?>;
}


.notyfy_wrapper.notyfy_primary {
    background: <?= $primaryColor; ?>;
}

div.glyphicons.glyphicon-primary i:before,
div.glyphicons-social.glyphicon-primary i:before {
    color: <?= $primaryColor; ?>;
}

.nav-pills.nav-timeline>li>a {
    background: <?= $primaryColor; ?>;
}

.widget.widget-wizard-pills .widget-head ul li.primary a {
    background: <?= $primaryColor; ?>;
}

.wizard-design .pagination > li.next > a:focus {
    background: <?= $primaryColor; ?>;
}

.activity-line .icon.primary {
    background: <?= $primaryColor; ?>;
}

.activity-line .color-widget.primary {
    background: <?= $primaryColor; ?>;
}
/* User Profile */
.profile-photo .image-tool-tip {
    background: <?= $primaryColor; ?>;
}

.profile-photo:hover .photo-overlay {
    background: <?= $primaryColor; ?>;
    opacity: 0.5;
}

.u-username {
    color: <?= $primaryColor; ?>;
}

.u-lists .fa {
    color: <?= $primaryColor; ?>;
}
.
/* Language */
.language-list .site i {
    color: <?= $primaryColor; ?>;
}
.open-page-from-lan-tab[data-opentab]:hover {
    color: <?= $primaryColor; ?>;
}
.open-page-from-lan-tab[data-opentab]:hover .site {
    color: <?= $primaryColor; ?>;
}
.login-page .navbar.main .nav.navbar-right {
    background: <?= $primaryColor; ?>;
}
/* =============== Secondary Color =============== */
.reponsive-menu-tabs:hover span, .reponsive-menu-tabs:hover .fa {
    color:  <?= $secondaryColor; ?>;
}
.navbar #melis-id-nav-bar-tabs > li {
    border-bottom: 1px solid <?= $secondaryColor; ?>;
}

.cb-cont .cbmask-outer {
    border: 2px solid <?= $secondaryColor; ?>;
}

.cb-cont .cbmask-inner.cb-active {
    background: <?= $secondaryColor; ?>;
}

.navbar.main.navbar-primary .navbar-brand {
    border-bottom: 1px solid <?= $secondaryColor; ?>;
}
#newplugin-cont .nav .open > a, #newplugin-cont .nav > li > a:focus, #newplugin-cont .nav .open > a:focus, #newplugin-cont .nav > li > a:hover, #newplugin-cont .nav .open > a:hover {
    background-color: <?= $secondaryColor; ?>;
}
#res-page-cont {
    border-bottom: 1px solid <?= $secondaryColor; ?>;
}
.widget.widget-body-primary>.widget-body {
    background-color: <?= $secondaryColor; ?>;
}

.form-group i.fa-info-circle + .tooltip .tooltip-inner {
    background-color: <?= $secondaryColor; ?>;
}

.tooltip .tooltip-inner {
    background-color: <?= $secondaryColor; ?>;
}

.tooltip.bs-tooltip-left .arrow {
    border-left-color: <?= $secondaryColor; ?>;
}
.tooltip.left .tooltip-arrow {
    border-left-color: <?= $secondaryColor; ?>;
}



.tickets li .media-heading {
    color: <?= $secondaryColor; ?>;
}

.checkbox-custom i.checked {
    color: <?= $secondaryColor; ?>;
}

#events-carousel.owl-theme .owl-controls .owl-page span {
    background: <?= $secondaryColor; ?>;
}

#events-speakers.owl-theme .owl-controls .owl-page span {
    background: <?= $secondaryColor; ?>;
}

.carousel.carousel-1 .carousel-indicators li.active {
    background: <?= $secondaryColor; ?>;
}

.carousel.carousel-1 .carousel-indicators li {
    background: <?= $secondaryColor; ?>;
}

.nav-timeline>li.active>a {
    background: <?= $secondaryColor; ?>;
}
.nav-pills.nav-timeline>li>a:hover {
    background: <?= $secondaryColor; ?>;
}

.nav-tabs>li>a:hover, .nav-pills>li>a, .nav-pills>li>a:hover {
    color: <?= $secondaryColor; ?>;
}

.list-group-1>li:hover>a>[class*="fa-"] {
    color: <?= $secondaryColor; ?>;
}

.navbar.main.navbar-primary .toggle-button i {
    color: <?= $secondaryColor; ?>;
}

.module-settings .ms-heading .tooltip .tooltip-inner {
    background: <?= $secondaryColor; ?>;
}
.pagination>li>a, .pagination>li>span {
    color: <?= $secondaryColor; ?>;
}

.calendar-highlight {
    background: <?= $secondaryColor; ?>;
}

.datepicker .table-condensed tr td.active,
.datepicker .table-condensed tr td.active:hover,
.datepicker .table-condensed tr td.active.disabled,
.datepicker .table-condensed tr td.active.disabled:hover {
    background: <?= $secondaryColor; ?> !important;
}


/* Plug-in Dashboard Right Sidebar */
.melis-core-dashboard-dnd-title {
    background-color: <?= $primaryColor; ?>;
}
.melis-core-dashboard-dnd-box {
    border-color: <?= $primaryColor; ?>;
}
.melis-core-dashboard-dnd-box #melisDashBoardPluginBtn {
    background-color: <?= $primaryColor; ?>;
}
.melis-core-dashboard-plugin-delete-all #dashboard-plugin-delete-all {
    background-color: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}
#dashboard-plugin-delete-all:hover {
    background-color: <?= $secondaryColor; ?>;
    border-color: <?= $secondaryColor; ?>;
}

.melis-core-dashboard-ps-box .melis-core-dashboard-filter-btn.active, .melis-core-dashboard-category-btn.active {
    background-color: <?= $primaryColor; ?>;
    border-color: <?= $secondaryColor; ?>;
}
.melis-core-dashboard-plugin-snippets:hover {
    background-color: <?= $primaryColor; ?>;
}

/* Plug-in Page Edition Right Sidebar */
.melis-cms-dnd-box #melisPluginBtn {
    background-color: <?= $primaryColor; ?> !important;
}
.melis-cms-plugin-snippets:hover {
    background-color: <?= $primaryColor; ?> !important;
}
.melis-cms-ps-box .melis-cms-filter-btn.active, .melis-cms-category-btn.active {
    background-color: <?= $primaryColor; ?> !important;
}

/* Workflow Page Edition Modal */
.workflow-modal-cont .pw-title {
    background-color: <?= $primaryColor; ?>;
}
.workflow-modal-content .wmc-content.wmc-header > span{
    background-color: <?= $primaryColor; ?>;
}
.modal .modal-header .modal-title {
    color : #fff;
}

.workflow-modal-content .wmc-header span {
    border-right: 1px solid <?= $secondaryColor; ?> !important;
}
.workflow-modal-content .wmc-header {
    background: <?= $primaryColor; ?>;
}

/* Page Edition */
.melis-plugin-indicator {
    background-color: <?= $primaryColor; ?>!important;
}
.melis-plugin-tools-box {
    background-color: <?= $primaryColor; ?>!important;
}

/* Bootstrap Modal */
.bootstrap-dialog.type-danger .modal-header {
    background-color: <?= $primaryColor; ?>;
}

/* Media Queries */
@media (max-width: 768px) {
     .login-page .navbar.main .nav>li .dropdown-menu li {
        border-color: <?= $secondaryColor; ?>;
    }
}
@media (min-width: 768px) {
    .navbar #melis-id-nav-bar-tabs > li {
        border-right: 1px solid <?= $secondaryColor; ?>;
    }

    .navbar.main.navbar-primary .navbar-brand {
        border-right: 1px solid <?= $secondaryColor; ?>;
    }

    .navbar.main .nav.navbar-right > li {
        border-left-color: <?= $secondaryColor; ?>;
    }

    .navbar.main .nav.navbar-right > li {
        border-right: 1px solid <?= $secondaryColor; ?>;
    }

    .container-level-a  .tooltabmodal .widget.widget-tabs.widget-tabs-responsive > .widget-head ul li {
        border-right: 1px solid <?= $secondaryColor; ?>;
    }
}

/* Melis Default Color */
.melis-primary-txt {
    color: <?= $secondaryColor; ?> !important;
}

.melis-primary-bg {
    background: <?= $primaryColor; ?> !important;
}
