<?php
    // use default colors if platform scheme table is empty
    $primaryColor   = $this->melis_core_platform_color_primary_color   ?: '#981a1f';
    $secondaryColor = $this->melis_core_platform_color_secondary_color ?: '#ad6565';
    $sidebarBGColor = $this->melis_core_platform_color_sidebar_bg_color ?: '#373737';
    $loginLinkColor = $this->melis_core_platform_color_login_link_color ?: '#E61C23';

    //logo
    $toggleBtnColor         = $this->melis_core_platform_theme_toggle_btn_color;
    $toggleBtnHoverColor    = $this->melis_core_platform_theme_toggle_btn_hover_color;
    $logoBgColor            = $this->melis_core_platform_theme_logo_bg_color;
    $logoTxtColor           = $this->melis_core_platform_theme_logo_text_color;
    $logoTxtFontSize        = $this->melis_core_platform_theme_logo_text_font_size;

    //User profile
    $userProfileBgColor             = $this->melis_core_platform_theme_user_profile_bg_color;
    $userProfileImgBorderColor      = $this->melis_core_platform_theme_user_profile_img_border_color;
    $userProfileImgBorderRadius     = $this->melis_core_platform_theme_user_profile_img_border_radius;
    $userProfileNameTextColor       = $this->melis_core_platform_theme_user_profile_name_text_color;
    $userProfileStatusTextIconColor = $this->melis_core_platform_theme_user_profile_status_text_icon_color;
    //$userProfEditBtnBgColor
    //$userProfEditBtnHoverBgColor
    //$userProfEditBtnTextColor
    //$userProfEditBtnHoverTextColor
    //$userProfLogoutBtnBgColor
    //$userProfLogoutBtnHoverBgColor
    //$userProfLogoutBtnTextColor
    //$userProfLogoutBtnHoverTextColor

    //Menu
    $menuBgColor                = $this->melis_core_platform_theme_menu_bg_color;
    $menuHoverColor             = $this->melis_core_platform_theme_menu_hover_color;
    $menuFocusColor             = $this->melis_core_platform_theme_menu_focus_color;
    $menuBorderBottomColor      = $this->melis_core_platform_theme_menu_border_bottom_color;
    $menuTextIconColor          = $this->melis_core_platform_theme_menu_text_icon_color;

    $submenuBgColor             = $this->melis_core_platform_theme_submenu_bg_color;
    $submenuTextIconColor       = $this->melis_core_platform_theme_submenu_text_icon_color;
    $submenuTextIconHoverColor  = $this->melis_core_platform_theme_submenu_text_icon_hover_color;
    $submenuHoverActiveBgColor  = $this->melis_core_platform_theme_submenu_hover_active_bg_color;

    //Footer
    $loginPagefooterTextColor   = $this->melis_core_platform_theme_login_page_footer_text_color;
    $footerTextFontSize         = $this->melis_core_platform_theme_footer_text_fontsize;
    $footerLinkTextColor        = $this->melis_core_platform_theme_footer_link_text_color;
    $footerTextColor            = $this->melis_core_platform_theme_footer_text_color;

    //Header
    $headerTextIconColor        = $this->melis_core_platform_theme_header_text_icon_color;
    $headerTextIconActiveColor  = $this->melis_core_platform_theme_header_text_icon_active_color;
    $headerBgColor              = $this->melis_core_platform_theme_header_bg_color;
    $headerBgActiveColor        = $this->melis_core_platform_theme_header_bg_active_color;

    //Bubble Plugin
    $bubblePluginHideBtnTextIconColor               = $this->melis_core_platform_theme_bubble_plugin_hide_btn_text_icon_color;
    $bubblePluginHideBtnTextIconHoverColor          = $this->melis_core_platform_theme_bubble_plugin_hide_btn_text_icon_hover_color;
    $bubblePluginHideBtnBgBorderColor               = $this->melis_core_platform_theme_bubble_plugin_hide_btn_bg_border_color;
    $bubblePluginHideBtnBgHoverColor                = $this->melis_core_platform_theme_bubble_plugin_hide_btn_bg_hover_color;
    $bubblePluginHideBtnFontSize                    = $this->melis_core_platform_theme_bubble_plugin_hide_btn_text_font_size;

    $bubblePluginWidgetBgColor                      = $this->melis_core_platform_theme_bubble_plugin_widget_bg_color;
    $bubblePluginWidgetBtnBgColor                   = $this->melis_core_platform_theme_bubble_plugin_widget_btn_bg_color;
    $bubblePluginWidgetBtnTextHoverColor            = $this->melis_core_platform_theme_bubble_plugin_widget_btn_text_hover_color; // themed hover for all cards
    $bubblePluginWidgetHeaderTextIconColor          = $this->melis_core_platform_theme_bubble_plugin_widget_header_text_icon_color;
    $bubblePluginWidgetHeaderTextIconFontSize       = $this->melis_core_platform_theme_bubble_plugin_widget_header_text_icon_font_size;
    $bubblePluginWidgetFrontTextFontSize            = $this->melis_core_platform_theme_bubble_plugin_widget_front_text_font_size; // added by junry 02/18/2025

    $bubblePluginUpdatesHeaderTextIconColor         = $this->melis_core_platform_theme_bubble_plugin_updates_header_text_icon_color;
    $bubblePluginUpdatesHeaderBgColor               = $this->melis_core_platform_theme_bubble_plugin_updates_header_bg_color;
    $bubblePluginUpdatesBtnTextHoverColor           = $this->melis_core_platform_theme_bubble_plugin_updates_btn_text_hover_color;

    $bubblePluginNotifHeaderBgColor                 = $this->melis_core_platform_theme_bubble_plugin_notif_header_bg_color;
    $bubblePluginNotifBtnBorderTextColor            = $this->melis_core_platform_theme_bubble_plugin_notif_btn_border_text_color;
    
    $bubblePluginNewsHeaderBgColor                  = $this->melis_core_platform_theme_bubble_plugin_news_header_bg_color;
    $bubblePluginNewsBtnBorderTextColor             = $this->melis_core_platform_theme_bubble_plugin_news_btn_border_text_color;
    $bubblePluginNewsBtnBorderColor                 = $this->melis_core_platform_theme_bubble_plugin_news_btn_border_color;
    $bubblePluginNewsBtnBgHoverColor                = $this->melis_core_platform_theme_bubble_plugin_news_btn_bg_hover_color;

    $bubblePluginMsgHeaderBgColor                   = $this->melis_core_platform_theme_bubble_plugin_msg_header_bg_color;
    $bubblePluginMsgBtnBorderTextColor              = $this->melis_core_platform_theme_bubble_plugin_msg_btn_border_text_color;
    
    $bubblePluginWidgetBackHeaderBgColor            = $this->melis_core_platform_theme_bubble_plugin_widget_back_header_bg_color;
    $bubblePluginWidgetBackHeaderTextColor          = $this->melis_core_platform_theme_bubble_plugin_widget_back_header_text_color;
    $bubblePluginWidgetBackHeaderTextFontSize       = $this->melis_core_platform_theme_bubble_plugin_widget_back_header_text_font_size;
    $bubblePluginWidgetBackHeaderBtnTextFontSize    = $this->melis_core_platform_theme_bubble_plugin_widget_header_btn_txt_font_size;
    $bubblePluginWidgetBackHeaderCloseBtnBgColor    = $this->melis_core_platform_theme_bubble_plugin_widget_back_header_close_btn_bg_color;
    $bubblePluginWidgetBackHeaderCloseBtnIconColor  = $this->melis_core_platform_theme_bubble_plugin_widget_back_header_close_btn_icon_color;
    $bubblePluginWidgetBackContentHeaderTextColor   = $this->melis_core_platform_theme_bubble_plugin_widget_back_content_header_text_color;
    $bubblePluginWidgetBackContentDetailsTextColor  = $this->melis_core_platform_theme_bubble_plugin_widget_back_content_details_text_color;

    //Dashboard Plugin
    $dashboardPluginBorderRadius                        = $this->melis_core_platform_theme_dashboard_plugin_border_radius;
    $dashboardPluginNoPluginAlertBgColor                = $this->melis_core_platform_theme_dashboard_plugin_no_plugin_alert_bg_color;
    $dashboardPluginNoPluginAlertBorderColor            = $this->melis_core_platform_theme_dashboard_plugin_no_plugin_alert_border_color;
    $dashboardPluginNoPluginAlertColor                  = $this->melis_core_platform_theme_dashboard_plugin_no_plugin_alert_color;
    $dashboardPluginNoPluginAlertTextFontSize           = $this->melis_core_platform_theme_dashboard_plugin_no_plugin_alert_text_font_size;
    $dashboardPluginNoPluginAlertTextFontStyle          = $this->melis_core_platform_theme_dashboard_plugin_no_plugin_alert_text_font_style;

    $dashboardPluginPluginHeaderBgColor                 = $this->melis_core_platform_theme_dashboard_plugin_plugin_header_bg_color;
    $dashboardPluginPluginHeaderTextColor               = $this->melis_core_platform_theme_dashboard_plugin_plugin_header_text_color;
    $dashboardPluginPluginHeaderTextFontSize            = $this->melis_core_platform_theme_dashboard_plugin_plugin_header_text_font_size;
    $dashboardPluginPluginHeaderBtnsBgColor             = $this->melis_core_platform_theme_dashboard_plugin_plugin_header_btns_bg_color;
    $dashboardPluginPluginHeaderBtnsBorderColor         = $this->melis_core_platform_theme_dashboard_plugin_plugin_header_btns_border_color;
    $dashboardPluginPluginHeaderBtnsIconColor           = $this->melis_core_platform_theme_dashboard_plugin_plugin_header_btns_icon_color;
    $dashboardPluginPluginHeaderBtnsBgHoverColor        = $this->melis_core_platform_theme_dashboard_plugin_plugin_header_btns_bg_hover_color;
    $dashboardPluginPluginHeaderBtnsBorderHoverColor    = $this->melis_core_platform_theme_dashboard_plugin_plugin_header_btns_border_hover_color;

    $dashboardPluginPluginBodyBgColor                   = $this->melis_core_platform_theme_dashboard_plugin_plugin_body_bg_color;
    $dashboardPluginPluginBodyBorderColor               = $this->melis_core_platform_theme_dashboard_plugin_plugin_body_border_color;

    // //Dashboard Plugin Menu
    $dashboardPluginMenuBoxBgColor                      = $this->melis_core_platform_theme_dashboard_plugin_menu_box_bg_color;
    $dashboardPluginMenuBoxBorderColor                  = $this->melis_core_platform_theme_dashboard_plugin_menu_box_border_color;
    $dashboardPluginMenuBoxBorderWidth                  = $this->melis_core_platform_theme_dashboard_plugin_menu_box_border_width;
    $dashboardPluginMenuBoxTitleBgColor                   = $this->melis_core_platform_theme_dashboard_plugin_menu_box_title_bg_color; // added by junry 02/19/2025
    $dashboardPluginMenuBoxTitleColor                   = $this->melis_core_platform_theme_dashboard_plugin_menu_box_title_color;
    $dashboardPluginMenuBoxTitleFontSize                = $this->melis_core_platform_theme_dashboard_plugin_menu_box_title_font_size;
    $dashboardPluginMenuBoxTitleFontStyle               = $this->melis_core_platform_theme_dashboard_plugin_menu_box_title_font_style;
    $dashboardPluginMenuBoxFilterBoxBorderTopColor      = $this->melis_core_platform_theme_dashboard_plugin_menu_box_filter_box_border_top_color;
    $dashboardPluginMenuBoxFilterBoxBtnBgColor          = $this->melis_core_platform_theme_dashboard_plugin_menu_box_filter_box_btn_bg_color;
    $dashboardPluginMenuBoxFilterBoxBtnBorderColor      = $this->melis_core_platform_theme_dashboard_plugin_menu_box_filter_box_btn_border_color;
    $dashboardPluginMenuBoxFilterBoxBtnTextColor        = $this->melis_core_platform_theme_dashboard_plugin_menu_box_filter_box_btn_text_color;
    $dashboardPluginMenuBoxFilterBoxBtnTextFontSize     = $this->melis_core_platform_theme_dashboard_plugin_menu_box_filter_box_btn_text_font_size;

    $dashboardPluginMenuNewPluginIndicatorColor         = $this->melis_core_platform_theme_dashboard_plugin_menu_new_plugin_indicator_color;
    $dashboardPluginMenuNewPluginIndicatorTextFontSize  = $this->melis_core_platform_theme_dashboard_plugin_menu_new_plugin_indicator_text_font_size;

    $dashboardPluginMenuCategoryBtnTextColor            = $this->melis_core_platform_theme_dashboard_plugin_menu_category_btn_text_color;
    $dashboardPluginMenuCategoryBtnTextFontSize         = $this->melis_core_platform_theme_dashboard_plugin_menu_category_btn_text_font_size;

    $dashboardPluginMenuPluginTitleTextColor            = $this->melis_core_platform_theme_dashboard_plugin_menu_plugin_title_text_color;
    $dashboardPluginMenuPluginTitleTextFontSize         = $this->melis_core_platform_theme_dashboard_plugin_menu_plugin_title_text_font_size;

    $dashboardPluginMenuDeleteAllBtnColor               = $this->melis_core_platform_theme_dashboard_plugin_menu_delete_all_btn_color;
    $dashboardPluginMenuDeleteAllBtnBorderColor         = $this->melis_core_platform_theme_dashboard_plugin_menu_delete_all_btn_border_color;
    $dashboardPluginMenuDeleteAllBtnTextColor           = $this->melis_core_platform_theme_dashboard_plugin_menu_delete_all_btn_text_color;
    $dashboardPluginMenuDeleteAllBtnTextFontSize        = $this->melis_core_platform_theme_dashboard_plugin_menu_delete_all_btn_text_font_size;

    //Modal
    $modalBgColor                       = $this->melis_core_platform_theme_modal_bg_color;
    $modalBorderColor                   = $this->melis_core_platform_theme_modal_border_color;
    $modalBorderRadiusSize              = $this->melis_core_platform_theme_modal_border_radius_size;
    // $modalBorderWidth                   = $this->melis_core_platform_theme_modal_border_width; // to be added later

    $modalNavTabsBgColor                = $this->melis_core_platform_theme_modal_nav_tabs_bg_color;
    $modalNavTabsActiveBgColor          = $this->melis_core_platform_theme_modal_nav_tabs_active_bg_color;
    $modalNavTabsTextIconColor          = $this->melis_core_platform_theme_modal_nav_tabs_text_icon_color;
    $modalNavTabsTextIconHoverColor     = $this->melis_core_platform_theme_modal_nav_tabs_text_icon_hover_color;
    $modalNavTabsTextIconFontSize       = $this->melis_core_platform_theme_modal_nav_tabs_text_icon_font_size;
    $modalNavTabsBorderRightColor       = $this->melis_core_platform_theme_modal_nav_tabs_border_right_color;
    $modalNavTabsBorderRightWidth       = $this->melis_core_platform_theme_modal_nav_tabs_border_right_width;

    $modalContentTextColor              = $this->melis_core_platform_theme_modal_content_text_color;
    $modalContentTextFontSize           = $this->melis_core_platform_theme_modal_content_text_font_size;
    $modalContentTextFontStyles         = $this->melis_core_platform_theme_modal_content_text_font_styles;

    $modalContentCloseBtnBgColor        = $this->melis_core_platform_theme_modal_content_close_btn_bg_color;
    $modalContentCloseBtnHoverBgColor   = $this->melis_core_platform_theme_modal_content_close_btn_hover_bg_color;
    $modalContentCloseBtnBorderColor    = $this->melis_core_platform_theme_modal_content_close_btn_border_color;
    $modalContentCloseBtnTextColor      = $this->melis_core_platform_theme_modal_content_close_btn_text_color;
    $modalContentCloseBtnHoverTextColor = $this->melis_core_platform_theme_modal_content_close_btn_hover_text_color;

    $modalContentSaveBtnBgColor         = $this->melis_core_platform_theme_modal_content_save_btn_bg_color;
    $modalContentSaveBtnHoverBgColor    = $this->melis_core_platform_theme_modal_content_save_btn_hover_bg_color;
    $modalContentSaveBtnBorderColor     = $this->melis_core_platform_theme_modal_content_save_btn_border_color;
    $modalContentSaveBtnTextColor       = $this->melis_core_platform_theme_modal_content_save_btn_text_color;
    $modalContentSaveBtnHoverTextColor  = $this->melis_core_platform_theme_modal_content_save_btn_hover_text_color;

    //Dialog
    $dialogContentHeaderBgColor         = $this->melis_core_platform_theme_dialog_content_header_bg_color;
    $dialogContentHeaderTitleColor      = $this->melis_core_platform_theme_dialog_content_header_title_color;
    $dialogContentHeaderTitleFontSize   = $this->melis_core_platform_theme_dialog_content_header_title_font_size;

    $dialogCloseButtonColor             = $this->melis_core_platform_theme_dialog_close_button_color;
    $dialogCloseButtonFontSize          = $this->melis_core_platform_theme_dialog_close_button_font_size;

    $dialogContentBgColor               = $this->melis_core_platform_theme_dialog_content_bg_color;
    $dialogContentBorderColor           = $this->melis_core_platform_theme_dialog_content_border_color;
    $dialogContentTextColor             = $this->melis_core_platform_theme_dialog_content_text_color;
    $dialogContentTextFontSize          = $this->melis_core_platform_theme_dialog_content_text_font_size;

    $dialogNoBtnBgColor                 = $this->melis_core_platform_theme_dialog_no_btn_bg_color;
    $dialogNoBtnBgHoverColor            = $this->melis_core_platform_theme_dialog_no_btn_bg_hover_color;
    $dialogNoBtnBorderColor             = $this->melis_core_platform_theme_dialog_no_btn_border_color;
    $dialogNoBtnBorderHoverColor        = $this->melis_core_platform_theme_dialog_no_btn_border_hover_color;
    $dialogNoBtnTextColor               = $this->melis_core_platform_theme_dialog_no_btn_text_color;
    $dialogNoBtnTextHoverColor          = $this->melis_core_platform_theme_dialog_no_btn_text_hover_color;

    $dialogYesBtnBgColor                = $this->melis_core_platform_theme_dialog_yes_btn_bg_color;
    $dialogYesBtnBgHoverColor           = $this->melis_core_platform_theme_dialog_yes_btn_bg_hover_color;
    $dialogYesBtnBorderColor            = $this->melis_core_platform_theme_dialog_yes_btn_border_color;
    $dialogYesBtnBorderHoverColor       = $this->melis_core_platform_theme_dialog_yes_btn_border_hover_color;
    $dialogYesBtnTextColor              = $this->melis_core_platform_theme_dialog_yes_btn_text_color;
    $dialogYesBtnTextHoverColor         = $this->melis_core_platform_theme_dialog_yes_btn_text_hover_color;

    $dialogBtnTextFontSize              = $this->melis_core_platform_theme_dialog_btn_text_font_size;

    //Form Elements
    $formBgColor                                = $this->melis_core_platform_theme_form_bg_color;
    $formTextColor                              = $this->melis_core_platform_theme_form_text_color;

    $formSelectOptionBgColor                    = $this->melis_core_platform_theme_form_select_option_bg_color;
    $formSelectOptionTextColor                  = $this->melis_core_platform_theme_form_select_option_text_color;

    $formInputElementsBorderRadius              = $this->melis_core_platform_theme_form_input_elements_border_radius;
    $formInputElementsTextColor                 = $this->melis_core_platform_theme_form_input_elements_text_color;
    $formInputElementsBorderWidth               = $this->melis_core_platform_theme_form_input_elements_border_width;
    $formInputElementsBorderColor               = $this->melis_core_platform_theme_form_input_elements_border_color;
    $formInputElementsBgColor                   = $this->melis_core_platform_theme_form_input_elements_bg_color;

    $formInputTextDisableReadonlyBgColor        = $this->melis_core_platform_theme_form_input_text_disable_readonly_bg_color;
    $formInputTextDisableReadonlyBorderColor    = $this->melis_core_platform_theme_form_input_text_disable_readonly_border_color;
    $formInputTextDisableReadonlyTextColor      = $this->melis_core_platform_theme_form_input_text_disable_readonly_text_color;

    $formButtonSubmitBgColor                    = $this->melis_core_platform_theme_form_button_submit_bg_color;
    $formButtonSubmitTextColor                  = $this->melis_core_platform_theme_form_button_submit_text_color;
    $formButtonSubmitBorderRadius               = $this->melis_core_platform_theme_form_button_submit_border_radius;
    $formButtonSubmitBorderWidth                = $this->melis_core_platform_theme_form_button_submit_border_width;
    $formButtonSubmitBorderColor                = $this->melis_core_platform_theme_form_button_submit_border_color;
    //$formButtonSubmitBgHoverColor                = $this->melis_core_platform_theme_form_button_submit_bg_hover_color;
    //$formButtonSubmitHoverBorderColor            = $this->melis_core_platform_theme_form_button_submit_hover_border_color;
    //$formButtonSubmitHoverTextColor              = $this->melis_core_platform_theme_form_button_submit_hover_text_color;

    //Tab
    $tabWidgetHeadBgColor               = $this->melis_core_platform_theme_tab_widget_head_bg_color;
    $tabWidgetHeadBorderWidth           = $this->melis_core_platform_theme_tab_widget_head_border_width;
    $tabWidgetHeadBorderColor           = $this->melis_core_platform_theme_tab_widget_head_border_color;
    $tabWidgetHeadNavItemAndLinkHeight  = $this->melis_core_platform_theme_tab_widget_head_nav_item_and_link_height;
    $tabWidgetNavItemBorderRightWidth   = $this->melis_core_platform_theme_tab_widget_nav_item_border_right_width;
    $tabWidgetNavItemBorderRightColor   = $this->melis_core_platform_theme_tab_widget_nav_item_border_right_color;
    $tabWidgetNavLinkTextColor          = $this->melis_core_platform_theme_tab_widget_nav_link_text_color;
    $tabWidgetNavLinkTextFontSize       = $this->melis_core_platform_theme_tab_widget_nav_link_text_font_size;
    $tabWidgetNavLinkMinWidth           = $this->melis_core_platform_theme_tab_widget_nav_link_min_width;
    $tabWidgetNavLinkTextAlign          = $this->melis_core_platform_theme_tab_widget_nav_link_text_align;
    $tabWidgetNavLinkIconHeight         = $this->melis_core_platform_theme_tab_widget_nav_link_icon_height;
    $tabWidgetLinkIconColor             = $this->melis_core_platform_theme_tab_widget_link_icon_color;
    $tabWidgetLinkIconFontSize          = $this->melis_core_platform_theme_tab_widget_link_icon_font_size;

    //Datepicker
    /* $datepickerBgColor = $this->melis_core_platform_theme_datepicker_bg_color;
    $datepickerTextColor = $this->melis_core_platform_theme_datepicker_text_color;
    $datepickerBorderWidth = $this->melis_core_platform_theme_datepicker_border_width;
    $datepickerBorderColor = $this->melis_core_platform_theme_datepicker_border_color;
    $datepickerBorderRadius = $this->melis_core_platform_theme_datepicker_border_radius;
    $datepickerPrevNextDataActionButtonTextAlign = $this->melis_core_platform_theme_datepicker_prev_next_data_action_button_text_align;
    $datepickerPrevNextDataActionBtnBorderRadius = $this->melis_core_platform_theme_datepicker_prev_next_data_action_btn_border_radius;
    $datepickerPrevNextDataActionButtonTextColor = $this->melis_core_platform_theme_datepicker_prev_next_data_action_button_text_color;
    $datepickerPrevNextDataActionButtonHoverBgColor = $this->melis_core_platform_theme_datepicker_prev_next_data_action_button_hover_bg_color;
    $datepickerDowBgColor = $this->melis_core_platform_theme_datepicker_dow_bg_color;
    $datepickerDowTextColor = $this->melis_core_platform_theme_datepicker_dow_text_color;
    $datepickerTableThTdTextAlign = $this->melis_core_platform_theme_datepicker_table_th_td_text_align;
    $datepickerDayTextColor = $this->melis_core_platform_theme_datepicker_day_text_color;
    $datepickerDayTextHoverBgColor = $this->melis_core_platform_theme_datepicker_day_text_hover_bg_color;
    $datepickerDayOldWeekendTextColor = $this->melis_core_platform_theme_datepicker_day_old_weekend_text_color;
    $datepickerDayActiveBgColor = $this->melis_core_platform_theme_datepicker_day_active_bg_color;
    $datepickerDayActiveTextColor = $this->melis_core_platform_theme_datepicker_day_active_text_color;

    $datepickerTimepickerBtnBgColor = $this->melis_core_platform_theme_datepicker_timepicker_btn_bg_color;
    $datepickerTimepickerBtnIconColor = $this->melis_core_platform_theme_datepicker_timepicker_btn_icon_color;
    $datepickerTimepickerBtnHoverBgColor = $this->melis_core_platform_theme_datepicker_timepicker_btn_hover_bg_color;
    $datepickerTimepickerArrowBtnBgColor = $this->melis_core_platform_theme_datepicker_timepicker_arrow_btn_bg_color;
    $datepickerTimepickerArrowBtnHoverBgColor = $this->melis_core_platform_theme_datepicker_timepicker_arrow_btn_hover_bg_color;
    $datepickerTimepickerTimeBgColor = $this->melis_core_platform_theme_datepicker_timepicker_time_bg_color;
    $datepickerTimepickerTimeTextColor = $this->melis_core_platform_theme_datepicker_timepicker_time_text_color;

    $daterangepickerBgColor = $this->melis_core_platform_theme_daterangepicker_bg_color;
    $daterangepickerTextColor = $this->melis_core_platform_theme_daterangepicker_text_color;
    $daterangepickerBorderWidth = $this->melis_core_platform_theme_daterangepicker_border_width;
    $daterangepickerBorderColor = $this->melis_core_platform_theme_daterangepicker_border_color;
    $daterangepickerBorderRadius = $this->melis_core_platform_theme_daterangepicker_border_radius;
    $daterangepickerButtonBgColor = $this->melis_core_platform_theme_daterangepicker_button_bg_color;
    $daterangepickerButtonTextColor = $this->melis_core_platform_theme_daterangepicker_button_text_color;
    $daterangepickerButtonTextFontSize = $this->melis_core_platform_theme_daterangepicker_button_text_font_size;
    $daterangepickerButtonBorderRadius = $this->melis_core_platform_theme_daterangepicker_button_border_radius;
    $daterangepickerButtonBorderWidth = $this->melis_core_platform_theme_daterangepicker_button_border_width;
    $daterangepickerButtonBorderColor = $this->melis_core_platform_theme_daterangepicker_button_border_color;
    $daterangepickerButtonBorderBottomColor = $this->melis_core_platform_theme_daterangepicker_button_border_bottom_color;
    $daterangepickerButtonBgHoverColor = $this->melis_core_platform_theme_daterangepicker_button_bg_hover_color;
    $daterangepickerButtonTextHoverColor = $this->melis_core_platform_theme_daterangepicker_button_text_hover_color;
    $daterangepickerButtonHoverBorderColor = $this->melis_core_platform_theme_daterangepicker_button_hover_border_color;
    $daterangepickerDayActiveBgColor = $this->melis_core_platform_theme_daterangepicker_day_active_bg_color;
    $daterangepickerDayActiveTextColor = $this->melis_core_platform_theme_daterangepicker_day_active_text_color;
    $daterangepickerDayActiveBorderColor = $this->melis_core_platform_theme_daterangepicker_day_active_border_color;
    $daterangepickerDayActiveInRangeBgColor = $this->melis_core_platform_theme_daterangepicker_day_active_in_range_bg_color;
    $daterangepickerDayActiveInRangeBorderColor = $this->melis_core_platform_theme_daterangepicker_day_active_in_range_border_color;
    $daterangepickerDayActiveInRangeTextColor = $this->melis_core_platform_theme_daterangepicker_day_active_in_range_text_color;
    $daterangepickerDayActiveInRangeBorderWidth = $this->melis_core_platform_theme_daterangepicker_day_active_in_range_border_width;
    $daterangepickerInRangeStartDateBorderTopLeftRadius = $this->melis_core_platform_theme_daterangepicker_in_range_start_date_border_top_left_radius;
    $daterangepickerInRangeStartDateBorderTopRightRadius = $this->melis_core_platform_theme_daterangepicker_in_range_start_date_border_top_right_radius;
    $daterangepickerInRangeStartDateBorderBottomLeftRadius = $this->melis_core_platform_theme_daterangepicker_in_range_start_date_border_bottom_left_radius;
    $daterangepickerInRangeStartDateBorderBottomRightRadius = $this->melis_core_platform_theme_daterangepicker_in_range_start_date_border_bottom_right_radius;
    $daterangepickerInRangeEndDateBorderTopLeftRadius = $this->melis_core_platform_theme_daterangepicker_in_range_end_date_border_top_left_radius;
    $daterangepickerInRangeEndDateBorderTopRightRadius = $this->melis_core_platform_theme_daterangepicker_in_range_end_date_border_top_right_radius;
    $daterangepickerInRangeEndDateBorderBottomLeftRadius = $this->melis_core_platform_theme_daterangepicker_in_range_end_date_border_bottom_left_radius;
    $daterangepickerInRangeEndDateBorderBottomRightRadius = $this->melis_core_platform_theme_daterangepicker_in_range_end_date_border_bottom_right_radius;
    $daterangepickerDayAvailableTextColor = $this->melis_core_platform_theme_daterangepicker_day_available_text_color;
    $daterangepickerDayAvailableHoverBgColor = $this->melis_core_platform_theme_daterangepicker_day_available_hover_bg_color;
    $daterangepickerDayAvailableHoverBorderColor = $this->melis_core_platform_theme_daterangepicker_day_available_hover_border_color;
    $daterangepickerDayAvailableBorderWidth = $this->melis_core_platform_theme_daterangepicker_day_available_border_width;
    $daterangepickerDayAvailableBorderColor = $this->melis_core_platform_theme_daterangepicker_day_available_border_color;
    $daterangepickerDayAvailableBorderRadius = $this->melis_core_platform_theme_daterangepicker_day_available_border_radius;
    $daterangepickerDayTextFontSize = $this->melis_core_platform_theme_daterangepicker_day_text_font_size;
    $daterangepickerDayTextAlign = $this->melis_core_platform_theme_daterangepicker_day_text_align;
    $daterangepickerDayOffBgColor = $this->melis_core_platform_theme_daterangepicker_day_off_bg_color;
    $daterangepickerDayOffBorderColor = $this->melis_core_platform_theme_daterangepicker_day_off_border_color;
    $daterangepickerDayOffTextColor = $this->melis_core_platform_theme_daterangepicker_day_off_text_color;
    $daterangepickerFooterSelectedDateTextColor = $this->melis_core_platform_theme_daterangepicker_footer_selected_date_text_color;
    $daterangepickerFooterSelectedDateTextFontSize = $this->melis_core_platform_theme_daterangepicker_footer_selected_date_text_font_size;
    $daterangepickerFooterButtonsTextFontSize = $this->melis_core_platform_theme_daterangepicker_footer_buttons_text_font_size;
    $daterangepickerFooterCancelBtnBgColor = $this->melis_core_platform_theme_daterangepicker_footer_cancel_btn_bg_color;
    $daterangepickerFooterCancelBtnHoverBgColor = $this->melis_core_platform_theme_daterangepicker_footer_cancel_btn_hover_bg_color;
    $daterangepickerFooterCancelBtnBorderColor = $this->melis_core_platform_theme_daterangepicker_footer_cancel_btn_border_color;
    $daterangepickerFooterCancelBtnHoverBorderColor = $this->melis_core_platform_theme_daterangepicker_footer_cancel_btn_hover_border_color;
    $daterangepickerFooterCancelBtnTextColor = $this->melis_core_platform_theme_daterangepicker_footer_cancel_btn_text_color;
    $daterangepickerFooterCancelBtnHoverTextColor = $this->melis_core_platform_theme_daterangepicker_footer_cancel_btn_hover_text_color;
    $daterangepickerFooterApplyBtnBgColor = $this->melis_core_platform_theme_daterangepicker_footer_apply_btn_bg_color;
    $daterangepickerFooterApplyBtnHoverBgColor = $this->melis_core_platform_theme_daterangepicker_footer_apply_btn_hover_bg_color;
    $daterangepickerFooterApplyBtnBorderColor = $this->melis_core_platform_theme_daterangepicker_footer_apply_btn_border_color;
    $daterangepickerFooterApplyBtnHoverBorderColor = $this->melis_core_platform_theme_daterangepicker_footer_apply_btn_hover_border_color;
    $daterangepickerFooterApplyBtnTextColor = $this->melis_core_platform_theme_daterangepicker_footer_apply_btn_text_color;
    $daterangepickerFooterApplyBtnHoverTextColor = $this->melis_core_platform_theme_daterangepicker_footer_apply_btn_hover_text_color; */
?>
/* =============== Primary Color =============== */
.table-primary thead th {
    border-color: <?= $primaryColor; ?> !important;
    background-color: <?= $primaryColor; ?> !important;
}
.widget.widget-tabs-double .widget-head ul li.active a.glyphicons, 
.widget.widget-tabs-double .widget-head ul li a.glyphicons:hover, 
.widget.widget-tabs-double .widget-head ul li.active a.glyphicons:hover, 
.widget-tabs .nav-tabs > li.active > a.glyphicons:hover, 
.widget-tabs .nav-tabs > li > a.glyphicons:hover,
.widget.widget-tabs-double-2>.widget-head ul li.active a.glyphicons i:before,
.widget.widget-tabs > .widget-head ul li.active a.glyphicons, 
.widget.widget-tabs > .widget-head ul li.active a.glyphicons i:before,
.nav-tabs:not(.product-text-tab) .nav-item.active .nav-link.active span,
.nav-tabs:not(.product-text-tab) .nav-link.active span,
.nav.nav-tabs:not(.product-text-tab) .nav-item .nav-link.active span,
.nav.nav-tabs:not(.product-text-tab) .nav-item .nav-link.active,
.gdpr-tab-table-container .widget-head ul li.active a,
.gdpr-tab-table-container .widget-head ul li.active a .fa:before,
.melis-modal-cont .modal-content h3 a .glyphicons.lock i::before {
    color: <?= $primaryColor; ?>;
}
.grid-stack .grid-stack-placeholder>.placeholder-content,
.client-contact-address .default-card>.card-header,
.client-contact-address .panel-default>.panel-heading {
    background-color: <?= $primaryColor; ?> !important;
}
#btnDelImg,
.cron-info-toggle,
.progressContent .progress .text-danger,
.contacts .innerLR .media .media-body .media-heading a,
.contacts .innerLR .media a,
.widget .innerAll.half.media .media-body .text-muted-dark a,
.widget .innerAll .list-unstyled li a,
.widget .row-hover a,
.widget .media .media-body .innerB small a,
.widget .media .media-body h5 a,
.widget .innerAll.row-hover h5 a,
.widget .innerAll .media .media-body .text-muted-dark a,
.widget .innerAll .media .media-body a.text-small,
.widget.widget-tabs .widget-body .tab-content .tab-pane a.small,
.tickets .media .media-body .content-text p a,
.tickets .media .media-body small a,
.panel-flip .widget-scroll table tr td a,
.timeline-activity li a,
.chat-items .media .author a,
.widget-activity .widget-body .tab-pane .list li span a,
.glyphicons-social.single i:before, .glyphicons.single i:before,
.glyphicons-social.single, .glyphicons.single,
.email-content .from a,
.widget .widget-body .jumbotron .btn-primary:hover,
.widgets .widget .widget-body .widget-stats,
.widgets .widget .widget-body .well address strong a,
.widgets .widget .widget-body .well address a,
.widget-timeline .list-timeline li span a,
.panel-group.accordion .panel .panel-heading .panel-title a,
.commerce-dashboard-plugin-order-messages .media-body.media-body-inline span:not(.label.label-inverse),
.commerce-dashboard-plugin-order-messages .media-body.media-body-inline small,
.commerce-dashboard-plugin-order-messages .media-body.media-body-inline i,
.menubar ul li a,
.vevent a,
.pager .next > a,
.row-icons [class*="col"] i,
.row-icons [class*="col"] i:before,
.carouse-caption p a,
.carouse-caption p a:hover,
.tiny-slider .nav-tabs .nav-item .nav-link,
.tiny-slider .nav-tabs .nav-item .nav-link.active,
.tiny-slider .nav-tabs .nav-item .nav-link:hover,
.forgot-password a,
.forgot-password a:hover {
    color: <?= $primaryColor; ?> !important;
}
.tokenize-dropdown.dropdown .dropdown-menu .dropdown-item.active, 
.tokenize-dropdown.dropdown .dropdown-menu .dropdown-item:active,
.list-group-item.active {
    background-color: <?= $primaryColor; ?> !important;
    border-color: <?= $primaryColor; ?> !important;
}
.progress .progress-bar.progress-bar-danger,
#mini-template-buttons h3.ui-accordion-header-active.ui-state-active,
.commerce-dashboard-plugin-order-messages.answered .media-body.media-body-inline span.label.label-inverse,
.workflow-modal-content .wmc-header,
.gdpr-auto-delete-multi-tabs .nav-pills .nav-link:hover,
.gdpr-auto-delete-multi-tabs .nav-pills .nav-link.active, 
.nav-pills .show>.nav-link,
.has-switch span.switch-primary,
.label.label-primary,
.tabsbar ul li.active a,
.tabsbar .nav-tabs > li.active > a,
.badge.badge-primary,
.navbar.main.navbar-primary .navbar-brand {
    background: <?= $primaryColor; ?> !important;
}
.show>.btn-primary.dropdown-toggle {
    background: <?= $primaryColor; ?> !important;
}
.melis-gdpr-banner-container {
    background: <?= $primaryColor; ?> !important;
}
#categoryTreeView .jstree-proton .jstree-clicked {
    background: <?= $primaryColor; ?> !important;
    box-shadow: inset 0 0 1px <?= $primaryColor; ?> !important;
}
.melis-newsletter-send-subscribers-select-container .select2-container--default.select2-container--focus .select2-selection--multiple {
    border-color: <?= $primaryColor; ?> !important;
}
.datepicker .table-condensed tr td.active, 
.datepicker .table-condensed tr td.active:hover, 
.datepicker .table-condensed tr td.active.disabled, 
.datepicker .table-condensed tr td.active.disabled:hover,
.datepicker table tr td span.active, 
.datepicker table tr td span.active:hover, 
.datepicker table tr td span.active.disabled, 
.datepicker table tr td span.active.disabled:hover {
    background: <?= $primaryColor; ?> !important;
}

.tool_line-chart circle {
    fill: <?= $primaryColor; ?>;
}

.tool_line-chart path {
    stroke: <?= $primaryColor; ?>;
}
#convo-content .chat-contact-name,
small a:hover,
small a,
.carousel-caption a:hover,
.carousel-caption a,
.tiny-slider .nav-tabs > .nav-item .nav-link:hover,
.tiny-slider .nav-tabs > .nav-item .nav-link.active,
.tiny-slider .btn-clipboard,
.melis-cms-google-analytics-refresh .btn:hover .fa,
.tool_stats-table li,
.tabsbar ul.order-checkout-steps li a i:before {
    color: <?= $primaryColor; ?>;
}
.bootstrap-datetimepicker-widget table td span.active,
.bootstrap-datetimepicker-widget table td i.active,
.bootstrap-datetimepicker-widget table td.active,
.bootstrap-datetimepicker-widget table td.active:hover {
    background-color: <?= $primaryColor; ?> !important;
    color: #fff;
}
.tiny-slider .btn-clipboard:hover, 
.tiny-slider .btn-clipboard:focus,
.widget.widget-body-primary>.widget-body,
.ColVis .ColVis_Button {
    background-color: <?= $primaryColor; ?>;
}

#convo-content #chat-container .my-msg {
    background: <?= $primaryColor; ?>;
}

.survey .nav-pills .nav-link,
.table-with-progress .text-right .btn-group .btn-danger.btn-regular {
    background-color: <?= $primaryColor; ?> !important;
    border-color: <?= $primaryColor; ?> !important;
}

.btn-group .btn-danger.btn-regular:hover,
.btn-group .btn-danger.btn-regular:focus {
    background-color: #fff !important;
    color: <?= $primaryColor; ?> !important;
}

.table .btn-group .btn-danger.btn-regular:hover,
.table .btn-group .btn-danger.btn-regular:focus {
    background-color: #fff !important;
    color: <?= $primaryColor; ?> !important;
}

.innerTB .glyphicons p a,
.widget .widget-body p a,
#convo-content .chat-contact-name {
    color: <?= $primaryColor; ?>;
}

#content.render-widgets.widgets .widget .widget-body .widget-timeline .view-all:focus,
#content.render-widgets.widgets .widget .widget-body .widget-timeline .view-all:hover,
.media-msgrBody .text-danger {
    color: <?= $primaryColor; ?> !important;
}

#categoryProductListTbl .toolTipHoverEvent,
#categoryProductListTbl .toolTipCatHoverEvent {
    color: <?= $primaryColor; ?> !important;
}

.ColVis_MasterButton:hover,
.btn-primary:not(:disabled):not(.disabled).active,
.btn-primary:not(:disabled):not(.disabled):active,
.show>.btn-primary.dropdown-toggle {
    background-color: transparent;
    border-color: <?= $primaryColor; ?>;
    color: <?= $primaryColor; ?>;
}

a, a:hover {
    color: <?= $primaryColor; ?>;
}

.jstree-proton .jstree-hovered,
.jstree-proton .jstree-anchor:hover,
.jstree-proton .jstree-clicked,
body .navbar.main.navbar-primary {
    background-color: <?= $primaryColor; ?>;
}

#melis-navtabs-container-outer {
    background: <?= $primaryColor; ?>;
}

#melis-id-nav-bar-tabs {
    background: <?= $primaryColor; ?>;
}

.navbar.main.navbar-primary .nav > li.active > .dropdown-toggle,
.navbar.main.navbar-primary .nav > li.active .dropdown-toggle .fa,
.navbar.main.navbar-primary .nav > li.active .dropdown-toggle:hover,
.navbar.main.navbar-primary .nav > li.active .dropdown-toggle:hover .fa,
.navbar.main.navbar-primary .nav > li .dropdown-toggle:hover,
.navbar.main.navbar-primary .nav > li .dropdown-toggle:hover .fa {
    color: <?= $primaryColor; ?> !important;
}

.navbar.main.navbar-primary .nav > li > a:hover > i {
    color: <?= $primaryColor; ?> !important;
}

.nav-tabs.product-text-tab li.active a,
.nav-tabs.product-text-tab li.active:focus a,
.nav-tabs.product-text-tab li.active:active a,
.nav-tabs.product-text-tab li a:hover {
    background: <?= $primaryColor; ?>;
}

.navbar.main .nav.navbar-right {
    background: <?= $primaryColor; ?>;
}

.navbar.main .nav.navbar-right li:first-child {
    border-left: 1px solid <?= $secondaryColor; ?>;
}

.navbar.main .nav.navbar-right li {
    border-bottom: 1px solid <?= $secondaryColor; ?>;
}

/* Left sidebar menu */
.sidebar.sidebar-inverse {
    background: <?= $sidebarBGColor; ?>;
}
.sidebar.sidebar-inverse .user-profile ul li.active,
.sidebar.sidebar-inverse .user-profile ul li.active:hover {
    border-color: <?= $primaryColor; ?>;
}

.sidebar.sidebar-inverse .user-profile ul li.active a,
.sidebar.sidebar-inverse .user-profile ul li.active:hover a {
    background: <?= $primaryColor; ?>;
}

.sidebar.sidebar-inverse > .sidebarMenuWrapper > ul li.active-menu.hasSubmenu > a[data-bs-toggle="collapse"] {
    background-color: <?= $primaryColor; ?>;
}

/* Widgets */
.widget.widget-tabs-double .widget-head ul li.active a.glyphicons,
.widget.widget-tabs-double .widget-head ul li a.glyphicons:hover, 
.widget.widget-tabs-double .widget-head ul li.active a.glyphicons:hover, 
.widget.widget-tabs-double.widget-regular .widget-head ul li.active a i:before,
.widget.widget-tabs-double.widget-regular .widget-head ul li.active a,
.modal .widget.widget-tabs.widget-tabs-gray>.widget-head ul li.active a.glyphicons,
.modal .widget.widget-tabs.widget-tabs-gray>.widget-head ul li.active a.glyphicons i:before,
.widget.widget-tabs .widget-head ul li.active a.glyphicons,
.widget.widget-tabs .widget-head ul li.active a.glyphicons i:before
.widget.widget-tabs>.widget-head ul li.active a.glyphicons span,
.widget.widget-tabs>.widget-head ul li.active a.glyphicons,
.widget.widget-tabs>.widget-head ul li.active a.glyphicons i:before {
    color: <?= $primaryColor; ?> !important;
}

#modal-user-management .widget.widget-tabs-double > .widget-head ul li.active a.glyphicons.active i:before,
#modal-user-management .widget.widget-tabs-double > .widget-head ul li.active a.glyphicons.active,
#modal-user-management .widget.widget-tabs-double > .widget-head ul li a.glyphicons:hover, 
#modal-user-management .widget.widget-tabs-double > .widget-head ul li a.glyphicons:hover i:before,
#modal-user-management .widget.widget-tabs-double > .widget-head ul li.active a.active i:before,
#modal-user-management .widget.widget-tabs-double > .widget-head ul li.active a.active,
.render-tabs .widget.widget-tabs-double.widget-regular > .widget-head ul li.active a i:before,
.widget.widget-tabs-icons-only-2>.widget-head ul li a.glyphicons:hover i:before {
    color: <?= $primaryColor; ?> !important;
}

.widget.widget-tabs-double-2>.widget-head ul li:hover a {
    color: <?= $primaryColor; ?>;
}

.widget.widget-tabs-double-2>.widget-head ul li:hover a i:before {
    color: <?= $primaryColor; ?>;
}

.wizard .widget.widget-tabs-double>.widget-head ul li a.glyphicons:hover {
    color: <?= $primaryColor; ?> !important;
}

.wizard .widget.widget-tabs-double>.widget-head ul li a.glyphicons.active i:before,
.wizard .widget.widget-tabs-double>.widget-head ul li a.glyphicons:hover i:before,
.wizard .widget.widget-tabs-double>.widget-head ul li.active a.glyphicons:hover i:before {
    color: <?= $primaryColor; ?> !important;
}

.wizard .widget.widget-tabs-double>.widget-head ul li a.glyphicons:hover,
.wizard .widget.widget-tabs-double>.widget-head ul li.active a.glyphicons:hover {
    color: <?= $primaryColor; ?> !important;
}

.wizard.wizard-design .widget.widget-tabs-double>.widget-head ul li.active a.glyphicons,
.wizard.wizard-design .widget.widget-tabs-double>.widget-head ul li.active a.glyphicons i:before {
    color: <?= $primaryColor; ?>;
}

.navbar.main .nav.navbar-right .dropdown-menu li.active a,
.dropdown-menu li.active a,
.dropdown-menu li.active:hover a {
    background-color: <?= $primaryColor; ?>;
}

.widget.widget-tabs>.widget-head ul li.active a, 
.widget.widget-tabs-double>.widget-head ul li a .fa:before, 
.widget.widget-tabs>.widget-head ul li.active a .fa:before,
.mccom-dashboard-latest-heading .widget-head ul li.active > a i:before,
.navbar.main .nav.navbar-right .dropdown-menu li.active:hover a {
    color: <?= $primaryColor; ?>;
}

#id_meliscore_header_flash_messenger {
    border-left: 1px solid <?= $secondaryColor; ?> !important;
}

#tab-arrow-top {
    background-color: <?= $primaryColor; ?>;
}

.fc-prev-button.btn-primary:focus .bi.bi-chevron-left::before,
.fc-prev-button.btn-primary:hover .bi.bi-chevron-left::before,
.fc-next-button.btn-primary:focus .bi.bi-chevron-right::before,
.fc-next-button.btn-primary:hover .bi.bi-chevron-right::before,
.text-primary {
    color: <?= $primaryColor; ?> !important;
}

.ra-username {
    color: <?= $primaryColor; ?>;
}

/* Dashboard */
.bg-primary {
    background: <?= $primaryColor; ?> !important;
}

.overlay-loader {
    background: <?= $primaryColor; ?>;
}

.datepicker thead th.dow {
    background: <?= $primaryColor; ?> !important;
}

.table-primary thead th {
    border-color: <?= $primaryColor; ?>;
    background-color: <?= $primaryColor; ?> !important;
    color: #fff;
}

.pagination > li.active > a,
.pagination > li.active > a:focus,
.pagination > li.active > a:hover {
    background: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}

.pagination>li.primary>a:focus,
.pagination>li>a:focus,
.pagination>li>a:hover,
.pagination>li.primary>a {
    background: <?= $primaryColor; ?>;
}

.pagination > .page-item.active > .page-link, 
.pagination > .page-item.active > .page-link:focus, 
.pagination > .page-item.active > .page-link:hover {
    background-color: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}

.widget.widget-3 .widget-footer a:hover i:before,
.widget.widget-3 .widget-footer a:hover,
#pdfTarget .btn:focus .fa-download,
#pdfTarget .btn:hover .fa-download,
.page-link {
    color: <?= $primaryColor; ?>;
}

.rating:not(.read-only) span.star:hover:before, 
.rating:not(.read-only) span.star:hover~span.star:before,
.dt-paging-button.page-item.active .page-link:hover,
.dt-paging-button.page-item .page-link:hover {
    color: <?= $primaryColor; ?> !important;
}

/* Buttons */
.btn-primary {
    background: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}
.btn-primary:active:hover,
.btn-primary[disabled]:hover {
    color: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
    background: #fff;
}

.label.label-primary.label-stroke,
.badge.badge-primary.badge-stroke,
.btn-group.open .btn-primary.dropdown-toggle,
.btn-primary.disabled,
.btn-primary[disabled],
.btn-primary:hover,
.btn-primary:focus,
.btn-primary:active,
.btn-primary.active {
    color: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}

.btn-primary.btn-stroke {
    color: <?= $primaryColor; ?>;
}

.btn-primary.btn-stroke:hover,
.btn-primary.btn-stroke:focus,
.btn-primary.btn-stroke:active,
.btn-primary.btn-stroke.active {
    background: <?= $primaryColor; ?>;
}
/** login submit button */
.content-login .form-group .btn-primary {
    background: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
    color: #ffffff;
}
.content-login .form-group .btn-primary:hover {
    color: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
    background-color: #ffffff;
}
.content-login .form-group label {
    color: #686868;
}

/* Modal */
.modal-content .widget .widget-head {
    background: <?= $primaryColor; ?>;
}

/* Nav Tabs */
.tabsbar .nav-group-dropdown li .tab-element {
    background: <?= $primaryColor; ?>;
}
.tabsbar .nav-group-dropdown li:hover > .tab-element > i:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar .nav-group-dropdown li.active > a.tab-element > i:before {
    color: <?= $primaryColor; ?>;
}

.navbar.main.navbar-primary .tabsbar li:hover > .tab-element {
    color: <?= $primaryColor; ?>;
}

.tabsbar .nav-group-dropdown li.active > a.tab-element {
    color: <?= $primaryColor; ?> !important;
}

.tabsbar .has-sub.active > .tab-element i:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar .has-sub:hover > .tab-element:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar .has-sub.active-parent.on > .tab-element i:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar .has-sub.active-parent.on > .tab-element:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar .has-sub.active-parent.on > .tab-element {
    color: <?= $primaryColor; ?> !important;
}

.tabsbar .has-sub.active > .tab-element:before {
    color: <?= $primaryColor; ?>;
}

.tabsbar.tabsbar-2 ul li.active {
    background: <?= $primaryColor; ?>;
}

.tabsbar ul li.active a {
    background: <?= $primaryColor; ?>;
}

.tabsbar.tabsbar-2 ul li:not(.active):hover a {
    color: <?= $primaryColor; ?>;
}

.tabsbar.tabsbar-2 ul li:not(.active):hover a i:before {
    color: <?= $primaryColor; ?>;
}

/* Accordion */
.tab-pane a.btn.a-accordion.collapsed:hover,
.tab-pane a.btn.a-accordion {
    border-color: <?= $primaryColor; ?>;
    background: <?= $primaryColor; ?>;
}

.tab-pane a.btn.a-accordion.collapsed {
    background: <?= $primaryColor; ?>;
}

.commerce-toggle .card-header,
.commerce-toggle .panel-heading {
    background-color: <?= $primaryColor; ?>;
}

.commerce-toggle .accordion-toggle,
.commerce-toggle .accordion-toggle {
    background-color: <?= $primaryColor; ?> !important;
}

.ranges li {
    color: <?= $primaryColor; ?>;
}

.ranges li.active {
    background: <?= $primaryColor; ?>;
    border: 1px solid <?= $primaryColor; ?>;
}

.ranges li:hover {
    background: <?= $primaryColor; ?>;
    border: 1px solid <?= $primaryColor; ?>;
}

textarea:focus,
input[type="text"]:focus,
input[type="password"]:focus,
input[type="datetime"]:focus,
input[type="datetime-local"]:focus,
input[type="date"]:focus,
input[type="month"]:focus,
input[type="time"]:focus,
input[type="week"]:focus,
input[type="number"]:focus,
input[type="email"]:focus,
input[type="url"]:focus,
input[type="search"]:focus,
input[type="tel"]:focus,
input[type="color"]:focus,
.uneditable-input:focus {
    border-left: 1px solid <?= $primaryColor; ?>;
}

.content-cont .nav-tabs.product-text-tab li.active a,
.content-cont .nav-tabs.product-text-tab li.active:focus a,
.content-cont .nav-tabs.product-text-tab li.active:active a,
.content-cont .nav-tabs.product-text-tab li a:hover {
    background: <?= $primaryColor; ?>;
}

.orderPaymentCouponLink {
    color: <?= $primaryColor; ?>;
}

/* Media Queries */
@media (min-width: 768px) {
    .navbar #melis-id-nav-bar-tabs > li {
        background: <?= $primaryColor; ?>;
    }

    .navbar #melis-id-nav-bar-tabs > li:hover > a {
        color: <?= $primaryColor; ?> !important;
    }

    .navbar #melis-id-nav-bar-tabs > li:hover > a > i {
        color: <?= $primaryColor; ?>;
    }

    .navbar #melis-id-nav-bar-tabs > li > a.close:hover:before {
        color: <?= $primaryColor; ?>;
    }

    .melis-tabprev,
    .melis-tabnext {
        background: <?= $primaryColor; ?>;
    }

    .melis-tabprev:hover,
    .melis-tabnext:hover {
        color: <?= $primaryColor; ?>;
    }
}

/* MarketPlace */
.melis-store .post-info a {
    color: <?= $primaryColor; ?>;
}

/* Modules */
.module-settings .ms-heading {
    background: <?= $primaryColor; ?>;
}

/* DragnDrop */
.melis-cms-dnd-box {
    border-bottom: 4px solid <?= $primaryColor;?>!important;
    border-left: 4px solid <?= $primaryColor;?>!important;
}
.melis-cms-dnd-title {
    background: <?= $primaryColor; ?>!important;
}
.m-plugin-sub-tools {
    background: <?= $primaryColor; ?>!important;
}
.module-display-heading .ms-heading {
    background: <?= $primaryColor; ?>!important;
}
.melis-cms-filter-btn-sub-category.active,
.melis-cms-ps-box .melis-cms-filter-btn.active, .melis-cms-category-btn.active {
    background: <?= $primaryColor; ?>!important;
    border-color: <?= $primaryColor; ?>!important;
}
.melis-ui-outlined:hover {
    outline: 1px solid <?= $primaryColor; ?>!important;
    box-shadow: 0 0 0 1px <?= $primaryColor; ?>!important;
    -webkit-box-shadow: 0 0 0 1px <?= $primaryColor; ?>!important;
    -moz-box-shadow: 0 0 0 1px <?= $primaryColor; ?>!important;
    -ms-box-shadow: 0 0 0 1px <?= $primaryColor; ?>!important;
    z-index: 9999996 !important;
}
.melis-cms-category-plugins-box {
    border-bottom-color: <?= $secondaryColor; ?> !important;
}

/* Commerce */
.red-box-panel h3 {
    border-bottom: 1px solid <?= $primaryColor; ?>;
    background: <?= $primaryColor; ?>;
}

.progress .progress-bar.progress-bar-danger {
    background: <?= $primaryColor; ?>;
}

.client-contact-address .default-card>.card-header,
.client-contact-address .panel-default>.panel-heading {
    background-color: <?= $primaryColor; ?>;
}

.widget-red {
    background: <?= $primaryColor; ?> !important;
}


.meliscms-search-box.sidebar-treeview-search .sbox-icon:hover {
    background: <?= $primaryColor; ?>;
}

.progress .progress-bar.progress-bar-primary {
    background:  <?= $primaryColor; ?>;
}

.rating span.star.active:before, .rating span.star.active~span.star:before {
    color: <?= $primaryColor; ?>;
}

.page-elements .innerAll.spacing-x2 .widget.widget-primary {
    background: <?= $primaryColor; ?>;
}

.pricing-table ul li a.btn.btn-primary.btn-lg:hover,
.view-map:hover .fa,
.view-map,
.widget-heading-simple .widget-body .innerAll a,
.social-comments .user-info a,
.activity-line .widget-body .innerAll a,
.activity-line .activity-status .text a,
.activity-line .widget-body span a,
.share .share-buttons .glyphicons:hover i:before,
.share .share-buttons .glyphicons-social:hover i:before,
#metrics .legendLabel a,
#id_melis_medical_memos .box-generic a,
.timeline-top-info a,
#pdfTarget .box-generic address a,
.inbox-scrollable .list-group-1>li:hover>a>[class*="fa-"],
.finances_summary .widget-body .separator a i,
.finances_summary .widget-body .separator a,
.resume-documents li a i {
    color: <?= $primaryColor; ?> !important;
}

.timeline-activity li.active i.list-icon {
    background-color: <?= $primaryColor; ?>;
    border: 2px solid <?= $primaryColor; ?>;
}

.table-vertical-center.checkboxs .selectable .center .btn-group .btn-danger,
.table-thead-simple .actions .btn-danger .fa,
.table-thead-simple .actions .btn-danger,
.table-thead-simple .important .btn-danger .fa,
.table-thead-simple .important .btn-danger,
.timeline-activity li:hover i.list-icon,
.timeline-activity li.active:hover i.list-icon {
    border-color: <?= $primaryColor; ?>;
    color: <?= $primaryColor; ?>;
}

.table-vertical-center.checkboxs .selectable .center .btn-group .btn-danger:hover,
.select2-container--default .select2-results__option--highlighted[aria-selected] {
    background-color: <?= $primaryColor; ?>;
}

.table-pricing-2 th {
    background: <?= $primaryColor; ?>;
}

.list-group-1>li.active, .list-group-1>li.active:hover {
    background: <?= $primaryColor; ?>;
}

.table-primary tbody td.important {
    color: <?= $primaryColor; ?>;
}

.table-pricing-3>ul>li.active .body {
    border-color: <?= $secondaryColor; ?>;
    background-color: <?= $primaryColor; ?>;
}

.innerAll.bg-primary .media {
    background: <?= $primaryColor; ?>;
}

.layout-timeline ul.timeline > li.active::before {
    background: <?= $primaryColor; ?> none repeat scroll 0 0 !important;
}

.layout-timeline ul.timeline > li.active .type::before,
.layout-timeline ul.timeline > li.active .type::after {
    background: <?= $primaryColor; ?> none repeat scroll 0 0 !important;
}

.layout-timeline ul.timeline > li.active .type i::before {
    color: <?= $primaryColor; ?> !important;
}

.layout-timeline ul.timeline > li.active .type {
    color: <?= $primaryColor; ?> !important;
}

.pricing-table.primary .list-group {
    background: <?= $primaryColor; ?>;
}

.pricing-table.primary .caret {
    border-top-color: <?= $primaryColor; ?>;
}

.bwizard-steps li.active {
    background: <?= $primaryColor; ?>;
}

.bwizard-steps li.active:after {
    border-left-color: <?= $primaryColor; ?>;
}

.slider-nav .slick-track .slick-slide {
    background:  <?= $primaryColor; ?>;
}

.slider-nav .slick-track .slick-slide:before {
    border-top: 1px solid <?= $primaryColor; ?>;
    border-bottom: 1px solid <?= $primaryColor; ?>;
}

.fc-event, .fc-event:hover {
    background: <?= $primaryColor; ?>;
}

.event-icon {
    background: <?= $primaryColor; ?>;
}

.update-event:hover {
    background: <?= $primaryColor; ?>;
}

::-webkit-scrollbar-thumb {
    background: <?= $primaryColor; ?>;
}

.nicescroll-cursors {
    background: <?= $primaryColor; ?> !important;
}

.content-cont .widget.widget-tabs-double-2>.widget-head ul li a:hover {
    color: <?= $primaryColor; ?>;
}

#external-events li {
    background: <?= $primaryColor; ?>;
}


.notyfy_wrapper.notyfy_primary {
    background: <?= $primaryColor; ?>;
}

div.glyphicons.glyphicon-primary i:before,
div.glyphicons-social.glyphicon-primary i:before {
    color: <?= $primaryColor; ?>;
}

.nav-pills.nav-timeline>li>a {
    background: <?= $primaryColor; ?>;
}

.modals .wizard .widget.widget-wizard-pills .widget-head.widget-steps-head ul li.active a.active,
.widget.widget-wizard-pills .widget-head ul li.active.primary a {
    background: <?= $primaryColor; ?>;
}

.wizard-design .pagination > li.next > a:focus {
    background: <?= $primaryColor; ?>;
}

.activity-line .icon.primary {
    background: <?= $primaryColor; ?>;
}

.activity-line .color-widget.primary {
    background: <?= $primaryColor; ?>;
}
/* User Profile */
.profile-photo .image-tool-tip {
    background: <?= $primaryColor; ?>;
}

.profile-photo:hover .photo-overlay {
    background: <?= $primaryColor; ?>;
    opacity: 0.5;
}

.u-username {
    color: <?= $primaryColor; ?>;
}

.u-lists .fa {
    color: <?= $primaryColor; ?>;
}
/* Language */
.language-list .site i {
    color: <?= $primaryColor; ?>;
}
.open-page-from-lan-tab[data-opentab]:hover {
    color: <?= $primaryColor; ?>;
}
.open-page-from-lan-tab[data-opentab]:hover .site {
    color: <?= $primaryColor; ?>;
}
/* Login page */
.login-page .navbar.main .nav.navbar-right {
    background: <?= $primaryColor; ?>;
}
.login-page .footer a:hover,
.login-page .footer a {
    color: <?= $primaryColor; //$loginLinkColor; ?>; 
}
/* =============== Secondary Color =============== */
.widget.widget-tabs > .widget-head ul li.active a.glyphicons:focus i:before,
.widget.widget-tabs > .widget-head ul li.active a.glyphicons:hover i:before,
.widget.widget-tabs-double-2>.widget-head ul li.active a.glyphicons:focus i:before,
.widget.widget-tabs-double-2>.widget-head ul li.active a.glyphicons:hover i:before,
.gdpr-tab-table-container .widget-head ul li a,
.gdpr-tab-table-container .widget-head ul li a .fa:before,
.reponsive-menu-tabs:hover span, .reponsive-menu-tabs:hover .fa {
    color:  <?= $secondaryColor; ?>;
}
.navbar #melis-id-nav-bar-tabs > li {
    border-bottom: 1px solid <?= $secondaryColor; ?>;
}

.cb-cont .cbmask-outer {
    border: 2px solid <?= $secondaryColor; ?>;
}

.cb-cont .cbmask-inner.cb-active {
    background: <?= $secondaryColor; ?>;
}

.navbar.main.navbar-primary .navbar-brand {
    border-bottom: 1px solid <?= $secondaryColor; ?>;
}
#newplugin-cont .nav .open > a, #newplugin-cont .nav > li > a:focus, #newplugin-cont .nav .open > a:focus, #newplugin-cont .nav > li > a:hover, #newplugin-cont .nav .open > a:hover {
    background-color: <?= $secondaryColor; ?>;
}
#res-page-cont {
    border-bottom: 1px solid <?= $secondaryColor; ?>;
}
.widget.widget-body-primary>.widget-body {
    background-color: <?= $secondaryColor; ?>;
}

.form-group i.fa-info-circle + .tooltip .tooltip-inner {
    background-color: <?= $secondaryColor; ?>;
}

.tooltip .tooltip-inner {
    background-color: <?= $secondaryColor; ?>;
}

.tooltip.bs-tooltip-left .arrow {
    border-left-color: <?= $secondaryColor; ?>;
}

.tooltip.left .tooltip-arrow {
    border-left-color: <?= $secondaryColor; ?>;
}

.bs-tooltip-auto[data-popper-placement^=bottom] .tooltip-arrow::before, 
.bs-tooltip-start .tooltip-arrow::before {
    border-bottom-color: <?= $secondaryColor; ?> !important;
}

.tooltip.fade.bs-tooltip-auto[x-placement^=bottom] .arrow::before,
.tooltip.fade.bs-tooltip-bottom .arrow::before {
    border-bottom-color: <?= $secondaryColor; ?> !important;
}

.bs-tooltip-auto[data-popper-placement^=top] .tooltip-arrow::before, 
.bs-tooltip-start .tooltip-arrow::before {
    border-top-color: <?= $secondaryColor; ?> !important;
}

.tooltip.fade.bs-tooltip-auto[x-placement^=top] .arrow::before,
.tooltip.fade.bs-tooltip-top .arrow::before {
    border-top-color: <?= $secondaryColor; ?> !important;
}

.bs-tooltip-auto[data-popper-placement^=right] .tooltip-arrow::before, 
.bs-tooltip-end .tooltip-arrow::before {
    border-right-color: <?= $secondaryColor; ?> !important;
}

.tooltip.fade.bs-tooltip-auto[x-placement^=right] .arrow::before, 
.tooltip.fade.bs-tooltip-right .arrow::before {
    border-right-color: <?= $secondaryColor; ?> !important;
}

.bs-tooltip-auto[data-popper-placement^=left] .tooltip-arrow::before, 
.bs-tooltip-start .tooltip-arrow::before {
    border-left-color: <?= $secondaryColor; ?> !important;
}

.bs-tooltip-auto[x-placement^="left"] .arrow::before,
.bs-tooltip-left .arrow::before,
.tooltip.fade.bs-tooltip-auto[x-placement^=left] .arrow::before, 
.tooltip.fade.bs-tooltip-left .arrow::before {
    border-left-color: <?= $secondaryColor; ?> !important;
}

.tickets li .media-heading {
    color: <?= $secondaryColor; ?>;
}

.checkbox-custom i.checked {
    color: <?= $secondaryColor; ?>;
}

#events-carousel.owl-theme .owl-controls .owl-page span {
    background: <?= $secondaryColor; ?>;
}

#events-speakers.owl-theme .owl-controls .owl-page span {
    background: <?= $secondaryColor; ?>;
}

.carousel.carousel-1 .carousel-indicators li.active {
    background: <?= $secondaryColor; ?>;
}

.carousel.carousel-1 .carousel-indicators li {
    background: <?= $secondaryColor; ?>;
}

.nav-timeline>li.active>a {
    background: <?= $secondaryColor; ?>;
}
.nav-pills.nav-timeline>li>a:hover {
    background: <?= $secondaryColor; ?>;
}

.nav-tabs>li>a:hover, .nav-pills>li>a, .nav-pills>li>a:hover {
    color: <?= $secondaryColor; ?> !important;
}

.list-group-1>li:hover>a>[class*="fa-"] {
    color: <?= $secondaryColor; ?>;
}

.navbar.main.navbar-primary .toggle-button i {
    color: <?= $secondaryColor; ?>;
}

.module-settings .ms-heading .tooltip .tooltip-inner {
    background: <?= $secondaryColor; ?>;
}
.pagination>li>a, .pagination>li>span {
    color: <?= $secondaryColor; ?>;
}

.calendar-highlight {
    background: <?= $secondaryColor; ?>;
}

/* Plug-in Dashboard Right Sidebar */
.melis-core-dashboard-dnd-title {
    background-color: <?= $primaryColor; ?>;
}
.melis-core-dashboard-dnd-box {
    border-color: <?= $primaryColor; ?>;
}
.melis-core-dashboard-dnd-box #melisDashBoardPluginBtn {
    background-color: <?= $primaryColor; ?>;
}
.melis-core-dashboard-plugin-delete-all #dashboard-plugin-delete-all {
    background-color: <?= $primaryColor; ?>;
    border-color: <?= $primaryColor; ?>;
}
#dashboard-plugin-delete-all:hover {
    background-color: <?= $secondaryColor; ?>;
    border-color: <?= $secondaryColor; ?>;
}

#id_melismessenger_tool_header_messages:hover a .fa-comment {
    color: <?= $primaryColor; ?>;
}

.melis-core-dashboard-ps-box .melis-core-dashboard-filter-btn.active, .melis-core-dashboard-category-btn.active {
    background-color: <?= $primaryColor; ?>;
    border-color: <?= $secondaryColor; ?>;
}
.melis-core-dashboard-plugin-snippets:hover {
    background-color: <?= $primaryColor; ?>;
}

/* Plug-in Page Edition Right Sidebar */
.melis-cms-dnd-box #melisPluginBtn {
    background-color: <?= $primaryColor; ?> !important;
}
.melis-cms-plugin-snippets:hover {
    background-color: <?= $primaryColor; ?> !important;
}
.melis-cms-ps-box .melis-cms-filter-btn.active, .melis-cms-category-btn.active {
    background-color: <?= $primaryColor; ?> !important;
}

/* Workflow Page Edition Modal */
.workflow-modal-cont .pw-title {
    background-color: <?= $primaryColor; ?>;
}
.workflow-modal-content .wmc-content.wmc-header > span{
    background-color: <?= $primaryColor; ?>;
}

.workflow-modal-content .wmc-header span {
    border-right: 1px solid <?= $secondaryColor; ?> !important;
}
.workflow-modal-content .wmc-header {
    background: <?= $primaryColor; ?>;
}

/* Page Edition */
.melis-plugin-indicator {
    background-color: <?= $primaryColor; ?>!important;
}
.melis-plugin-tools-box {
    background-color: <?= $primaryColor; ?>!important;
}

/* Bootstrap Modal */
.bootstrap-dialog.type-danger .modal-header {
    background-color: <?= $primaryColor; ?>;
}

.widget.widget-tabs-double .widget-head ul li a.glyphicons, 
.widget.widget-tabs-double .widget-head ul li a.glyphicons i:before {
    color: #fff;
}

/* Media Queries */
@media (max-width: 768px) {
     .login-page .navbar.main .nav>li .dropdown-menu li {
        border-color: <?= $secondaryColor; ?>;
    }
}
@media (min-width: 768px) {
    .navbar #melis-id-nav-bar-tabs > li {
        border-right: 1px solid <?= $secondaryColor; ?>;
    }

    .navbar.main.navbar-primary .navbar-brand {
        border-right: 1px solid <?= $secondaryColor; ?>;
    }

    .navbar.main .nav.navbar-right > li {
        border-left-color: <?= $secondaryColor; ?>;
    }

    .navbar.main .nav.navbar-right > li {
        border-right: 1px solid <?= $secondaryColor; ?>;
    }

    .container-level-a  .tooltabmodal .widget.widget-tabs.widget-tabs-responsive > .widget-head ul li {
        border-right: 1px solid <?= $secondaryColor; ?>;
    }
}

/* Melis Default Color */
.melis-primary-txt {
    color: <?= $secondaryColor; ?> !important;
}
.melis-primary-bg {
    background: <?= $primaryColor; ?> !important;
}

/* common */
.modal-content .form-group .has-switch .switch-animate span {
    color: #ffffff;
}
.platform-theme-options-tools-info .ui-widget-content {
    background-color: #e9e9e9;
}
.platform-theme-options-tools-info .ui-widget-header {
    background-color: #e61c23;
}
.platform-theme-options-tools-info .btn-group-font-style label {
    color: #797979;
    font-size: 25px;
    font-weight: normal;
    min-width: 3.5rem;
    margin: 0 5px;
}
.platform-theme-options-tools-info .btn-group .btn-check:checked+.btn, 
.platform-theme-options-tools-info .btn-group .btn.active, 
.platform-theme-options-tools-info .btn-group .btn.show, 
.platform-theme-options-tools-info .btn-group .btn:first-child:active, 
.platform-theme-options-tools-info .btn-group :not(.btn-check)+.btn:active,
.platform-theme-options-tools-info .btn-group .btn-check+.btn:hover {
    background-color: #e61c23 !important;
    border-color: #e61c23 !important;
}
.has-switch span.switch-left {
    color: #ffffff !important;
}
.has-switch label {
    color: #686868;
    font-size: 10px;
}
.form-group .group-span-filestyle label {
    color: #fff;
}

/* Platform theme options */
/* top logo */
.navbar.main.navbar-primary .toggle-button i {
    color: <?= $toggleBtnColor; ?>;
}
.navbar.main.navbar-primary .toggle-button:hover i {
    color: <?= $toggleBtnHoverColor; ?>;
}
.navbar.main.navbar-primary .left-menu .navbar-brand {
    background-color: <?= $logoBgColor; ?> !important;
}
.navbar.main.navbar-primary .appbrand span {
    color: <?= $logoTxtColor; ?>;
    font-size: <?= $logoTxtFontSize; ?>px;
}

/* user profile */
#id_meliscore_leftmenu_identity {
    background-color: <?= $userProfileBgColor; ?>;
}
.sidebar.sidebar-inverse .user-profile .rounded-circle, 
.sidebar.sidebar-inverse .user-profile .img-circle {
    border-color: <?= $userProfileImgBorderColor; ?> !important;
    border-radius: <?= $userProfileImgBorderRadius; ?> !important;
}

/* #user-name-link */
.sidebar.sidebar-inverse .user-profile a {
    color: <?= $userProfileNameTextColor; ?>;
}
.sidebar .user-profile .media-body p {
    color: <?= $userProfileStatusTextIconColor; ?> !important;
}
/** profile edit and logout buttons */
/* .sidebar.sidebar-inverse .user-profile ul li.active a, 
.sidebar.sidebar-inverse .user-profile ul li.active:hover a {
    background-color: #e61c23;
    color: #fff;
}
.sidebar.sidebar-inverse .user-profile ul li a:hover {
    color: #5a5a5a;
} */
/* menu */
.sidebar>.sidebarMenuWrapper {
    background-color: <?= $menuBgColor; ?>;
}
.sidebar.sidebar-inverse>.sidebarMenuWrapper>ul li {
    border-bottom-color: <?= $menuBorderBottomColor; ?>;
}
.sidebar.sidebar-inverse>.sidebarMenuWrapper>ul li a {
    color: <?= $menuTextIconColor; ?>;
}
.sidebar.sidebar-inverse>.sidebarMenuWrapper>ul li:hover>a {
    background: <?= $menuHoverColor; ?>;
}
.sidebar.sidebar-inverse > .sidebarMenuWrapper > ul li.active-menu.hasSubmenu > a[data-bs-toggle="collapse"] {
    background-color: <?= $menuFocusColor; ?>;
}
/** submenu */
.sidebar.sidebar-inverse>.sidebarMenuWrapper>ul li.active-menu.hasSubmenu {
    background-color: <?= $submenuBgColor; ?>;
    color: <?= $submenuTextIconColor; ?>;
}
.sidebar.sidebar-inverse>.sidebarMenuWrapper>ul li.active.hasSubmenu .hasSubmenu.active>a {
    background: <?= $submenuHoverActiveBgColor; ?>;
    color: <?= $submenuTextIconHoverColor; ?>;
}

/* footer */
#id_meliscore_footer .footer {
    font-size: <?= $footerTextFontSize; ?>px;
}
#id_meliscore_footer .footer a {
    color: <?= $footerLinkTextColor; ?>;
}
#id_meliscore_footer .footer p {
    color: <?= $footerTextColor; ?>;
}

/** login footer */
#id_meliscore_login_footer .footer {
    color: <?= $loginPagefooterTextColor; ?>;
}

/* header navigation */
.navbar.main.navbar-primary .dropdown-toggle {
    background-color: <?= $headerBgColor; ?>;
    color: <?= $headerTextIconColor; ?>;
}
.navbar.main.navbar-primary .nav > li.active > .dropdown-toggle {
    background-color: <?= $headerBgActiveColor; ?>;
    color: <?= $headerTextIconActiveColor; ?>;
}

/* bubble plugins */
#btn-hide-bubble-plugins {
    background: <?= $bubblePluginHideBtnBgBorderColor; ?>;
    border-color: <?= $bubblePluginHideBtnBgBorderColor; ?>;
    color: <?= $bubblePluginHideBtnTextIconColor; ?>;
    font-size: <?= $bubblePluginHideBtnFontSize; ?>px;
}
#btn-hide-bubble-plugins .fa-arrow-up:before {
    color: <?= $bubblePluginHideBtnTextIconColor; ?>;
}
#btn-hide-bubble-plugins:hover .fa-arrow-up:before {
    color: <?= $bubblePluginHideBtnTextIconHoverColor; ?>;
}
#btn-hide-bubble-plugins:hover {
    background: <?= $bubblePluginHideBtnBgHoverColor; ?>;
    color: <?= $bubblePluginHideBtnTextIconHoverColor; ?>;
}

.melis-dashboard-bubble-plugin .widget {
    background-color: <?= $bubblePluginWidgetBgColor; ?>;
}

.melis-dashboard-bubble-plugin .front .btn {
    background-color: <?= $bubblePluginWidgetBtnBgColor; ?>;
}
.melis-dashboard-bubble-plugin .front .btn:hover {
    color: <?= $bubblePluginWidgetBtnTextHoverColor; ?>;
}

/* applicable only on news, notification and message widgets */
.melis-dashboard-bubble-plugin .front .widget-body .lead .fa,
.melis-dashboard-bubble-plugin .front .widget-body .lead {
    color: <?= $bubblePluginWidgetHeaderTextIconColor; ?> !important;
    font-size: <?= $bubblePluginWidgetHeaderTextIconFontSize; ?>px;
}

/** updates, header, button and border has the same color */
.melis-dashboard-bubble-updates-plugin .front .widget-body .lead .fa,
.melis-dashboard-bubble-updates-plugin .front .widget-body .lead {
    color: <?= $bubblePluginUpdatesHeaderTextIconColor; ?> !important;
}
.melis-dashboard-bubble-updates-plugin .front .widget-body .innerAll.bg-default {
    background-color: <?= $bubblePluginUpdatesHeaderBgColor; ?> !important;
}
.melis-dashboard-bubble-updates-plugin .front .widget-body .btn {
    color: <?= $bubblePluginUpdatesBtnTextHoverColor; ?> !important;
    border-color: <?= $bubblePluginUpdatesBtnTextHoverColor; ?> !important;
}
.melis-dashboard-bubble-updates-plugin .front .widget-body .btn:hover {
    background-color: <?= $bubblePluginUpdatesHeaderBgColor; ?> !important;
    border-color: <?= $bubblePluginUpdatesHeaderBgColor; ?> !important;
}

/** themed colors for news card button effects */
.melis-dashboard-bubble-news-melis-plugin .front .widget-body .innerAll.bg-inverse {
    background-color: <?= $bubblePluginNewsHeaderBgColor; ?> !important;
}
.melis-dashboard-bubble-news-melis-plugin .front .widget-body .btn {
    color: <?= $bubblePluginNewsBtnBorderTextColor; ?> !important;
    border-color: <?= $bubblePluginNewsBtnBorderColor; ?> !important;
}
.melis-dashboard-bubble-news-melis-plugin .front .widget-body .btn:hover {
    background-color: <?= $bubblePluginNewsBtnBgHoverColor; ?> !important;
}

/** themed colors for notification card button effects */
.melis-dashboard-bubble-notifications-plugin .front .widget-body .innerAll.bg-success {
    background-color: <?= $bubblePluginNotifHeaderBgColor; ?> !important;
}
.melis-dashboard-bubble-notifications-plugin .front .widget-body .btn {
    color: <?= $bubblePluginNotifBtnBorderTextColor; ?> !important;
    border-color: <?= $bubblePluginNotifBtnBorderTextColor; ?> !important;
}
.melis-dashboard-bubble-notifications-plugin .front .widget-body .btn:hover {
    background-color: <?= $bubblePluginNotifBtnBorderTextColor; ?> !important;
    border-color: <?= $bubblePluginNotifBtnBorderTextColor; ?> !important;
}

/** themed colors for chat card button effects */
.melis-dashboard-bubble-chat-plugin .front .widget-body .innerAll.bg-info {
    background-color: <?= $bubblePluginMsgHeaderBgColor; ?> !important
}
.melis-dashboard-bubble-chat-plugin .front .widget-body .btn {
    color: <?= $bubblePluginMsgBtnBorderTextColor; ?> !important;
    border-color: <?= $bubblePluginMsgBtnBorderTextColor; ?> !important;
}
.melis-dashboard-bubble-chat-plugin .front .widget-body .btn:hover {
    background-color: <?= $bubblePluginMsgBtnBorderTextColor; ?> !important;
    border-color: <?= $bubblePluginMsgBtnBorderTextColor; ?> !important;
}

.melis-dashboard-bubble-plugin .front .widget-body .btn {
    font-size: <?= $bubblePluginWidgetFrontTextFontSize; ?>px;
}
.melis-dashboard-bubble-plugin .back .widget-head {
    background-color: <?= $bubblePluginWidgetBackHeaderBgColor; ?>;
    color: <?= $bubblePluginWidgetBackHeaderTextColor; ?>;
    font-size: <?= $bubblePluginWidgetBackHeaderTextFontSize; ?>px;
}
.melis-dashboard-bubble-plugin .back .widget-head .btn {
    background-color: <?= $bubblePluginWidgetBackHeaderCloseBtnBgColor; ?>;
    font-size: <?= $bubblePluginWidgetBackHeaderBtnTextFontSize; ?>px;
}
.melis-dashboard-bubble-plugin .back .widget-head .btn,
.melis-dashboard-bubble-plugin .back .widget-head .btn .fa {
    color: <?= $bubblePluginWidgetBackHeaderCloseBtnIconColor; ?>;
}
/** tabled contents */
.melis-dashboard-bubble-plugin .back .widget-body {
    color: #686868;
}
.melis-dashboard-bubble-plugin .back .widget-body table tr td {
    color: <?= $bubblePluginWidgetBackContentHeaderTextColor; ?>;
}
.melis-dashboard-bubble-plugin .back .widget-body table tr:not(:first-child) td {
    color: <?= $bubblePluginWidgetBackContentDetailsTextColor; ?>;
}

/* dashboard plugins msg */
/* .melis-core-dashboard-msg .alert-warning.no-plugins {
    color: #664d03;
    background-color: #fff3cd;
    border-color: #ffe69c;
} */
.melis-core-dashboard-msg .alert-info.no-plugins {
    background-color: <?= $dashboardPluginNoPluginAlertBgColor; ?>;
    border-color: <?= $dashboardPluginNoPluginAlertBorderColor; ?>;
    color: <?= $dashboardPluginNoPluginAlertColor; ?>;
    font-size: <?= $dashboardPluginNoPluginAlertTextFontSize; ?>px;
    <?php
        $fontStyle              = explode(';', $dashboardPluginNoPluginAlertTextFontStyle);

        $noPluginsFontWeight    = $fontStyle[0] ?? 'normal';
        $noPluginsFontStyle     = $fontStyle[1] ?? 'normal';
        $noPluginsTextTransform = $fontStyle[2] ?? 'inherit';
        $noPluginsTextDecoraton = $fontStyle[3] ?? 'inherit';
    ?>
    font-weight: <?= $noPluginsFontWeight; ?>;
    font-style: <?= $noPluginsFontStyle; ?>;
    text-transform: <?= $noPluginsTextTransform; ?>;
    text-decoration: <?= $noPluginsTextDecoraton; ?>;
}

/* plugins */
.grid-stack>.grid-stack-item>.grid-stack-item-content {
    border-radius: <?= $dashboardPluginBorderRadius; ?>;
}
.grid-stack-item-content .widget-head {
    background-color: <?= $dashboardPluginPluginHeaderBgColor; ?>;
}
.grid-stack-item-content .widget-head .heading {
    color: <?= $dashboardPluginPluginHeaderTextColor; ?>;
    font-size: <?= $dashboardPluginPluginHeaderTextFontSize; ?>px;
}
.grid-stack-item-content .widget-head .btn-group .btn {
    background-color: <?= $dashboardPluginPluginHeaderBtnsBgColor; ?>;
    border-color: <?= $dashboardPluginPluginHeaderBtnsBorderColor; ?>;
    color: <?= $dashboardPluginPluginHeaderBtnsIconColor; ?>;
}
.grid-stack-item-content .widget-head .btn-group .btn:hover {
    background-color: <?= $dashboardPluginPluginHeaderBtnsBgHoverColor; ?>;
    border-color: <?= $dashboardPluginPluginHeaderBtnsBorderHoverColor; ?>;
    color: <?= $dashboardPluginPluginHeaderBtnsIconColor; ?>;
}
.grid-stack-item-content .widget-body {
    background-color: <?= $dashboardPluginPluginBodyBgColor; ?>;
}
.grid-stack-item-content {
    border-color: <?= $dashboardPluginPluginBodyBorderColor; ?>;
}

/* dashboard plugins menu */
.melis-core-dashboard-dnd-box {
    border-bottom-width: <?= $dashboardPluginMenuBoxBorderWidth; ?>px;
    border-left-width: <?= $dashboardPluginMenuBoxBorderWidth; ?>px;
    border-color: <?= $dashboardPluginMenuBoxBorderColor; ?>;
    background-color: <?= $dashboardPluginMenuBoxBgColor; ?>;
}
.melis-core-dashboard-dnd-title {
    background-color: <?= $dashboardPluginMenuBoxTitleBgColor; ?>;
    color: <?= $dashboardPluginMenuBoxTitleColor; ?>;
    font-size: <?= $dashboardPluginMenuBoxTitleFontSize; ?>px;
    <?php
        $dashboardPluginBoxTitleFontStyle = explode(';', $dashboardPluginMenuBoxTitleFontStyle);

        $dashboardPluginsMenuBoxTitleFontWeight    = $dashboardPluginBoxTitleFontStyle[0] ?? 'normal';
        $dashboardPluginsMenuBoxTitleTextTransform = $dashboardPluginBoxTitleFontStyle[1] ?? 'inherit';
        $dashboardPluginsMenuBoxTitleTextDecoraton = $dashboardPluginBoxTitleFontStyle[2] ?? 'inherit';
    ?>
    text-transform: <?= $dashboardPluginsMenuBoxTitleTextTransform; ?>;
    font-weight: <?= $dashboardPluginsMenuBoxTitleFontWeight; ?>;
    text-decoration: <?= $dashboardPluginsMenuBoxTitleTextDecoraton; ?>;
}
.melis-core-dashboard-plugin-filter-box .melis-core-dashboard-ps-box:first-child {
    border-top-color: <?= $dashboardPluginMenuBoxFilterBoxBorderTopColor; ?>;
}
.melis-core-dashboard-category-btn.active,
.melis-core-dashboard-ps-box .melis-core-dashboard-filter-btn {
    background-color: <?= $dashboardPluginMenuBoxFilterBoxBtnBgColor; ?>;
    border-bottom-color: <?= $dashboardPluginMenuBoxFilterBoxBtnBorderColor; ?>;
    color: <?= $dashboardPluginMenuBoxFilterBoxBtnTextColor; ?>;
    font-size: <?= $dashboardPluginMenuBoxFilterBoxBtnTextFontSize; ?>px;
}
.melis-plugins-icon-new-child .melis-plugins-icon-new,
.melis-plugins-icon-new-parent > .new-plugin-indicator,
.melis-plugins-icon-new-parent {
    color: <?= $dashboardPluginMenuNewPluginIndicatorColor; ?>;
}
.melis-plugins-icon-new-child .melis-plugins-icon-new {
    font-size: <?= $dashboardPluginMenuNewPluginIndicatorTextFontSize; ?>px;
}
.melis-core-dashboard-category-btn {
    color: <?= $dashboardPluginMenuCategoryBtnTextColor; ?>;
    font-size: <?= $dashboardPluginMenuCategoryBtnTextFontSize; ?>px;
}
.melis-core-dashboard-plugin-title {
    color: <?= $dashboardPluginMenuPluginTitleTextColor; ?>;
    font-size: <?= $dashboardPluginMenuPluginTitleTextFontSize; ?>px;
}
#dashboard-plugin-delete-all {
    background-color: <?= $dashboardPluginMenuDeleteAllBtnColor; ?>;
    border-color: <?= $dashboardPluginMenuDeleteAllBtnBorderColor; ?>;
    color: <?= $dashboardPluginMenuDeleteAllBtnTextColor; ?>;
    font-size: <?= $dashboardPluginMenuDeleteAllBtnTextFontSize; ?>px;
}

/* Component options */
/* modals */
.modal .widget,
.modal .modal-body,
.modal .modal-content,
.modal .modal-dialog {
    background-color: <?= $modalBgColor; ?> !important;
}
.modal .modal-content {
    border-width: 0;
    border-color: <?= $modalBorderColor; ?>;
}
/* affected classes for border-radius */
.modal .modal-content,
.modal .dialog,
.modal {
    border-radius: <?= $modalBorderRadiusSize; ?>;
}
.modal-content .widget.widget-tabs.widget-tabs-responsive > .widget-head,
.modal-body .melis-nav-tabs-box {
    border-top-left-radius: <?= $modalBorderRadiusSize; ?>;;
    border-top-right-radius: <?= $modalBorderRadiusSize; ?>;;
}
/* end affected classes for border-radius */

/** options_modal_nav_tabs_color */
.modal-content .widget .widget-head {
    background-color: <?= $modalNavTabsBgColor; ?>;
}
/** options_modal_nav_tabs_active_bg_color */
.modal-content .nav-tabs > li.active > a {
    background-color: <?= $modalNavTabsActiveBgColor; ?>;
}
.modal-content .nav-tabs.product-text-tab > li.active > a {
    background-color: <?= $modalNavTabsActiveBgColor; ?>;
}
/** options_modal_nav_tabs_border_right_color, options_modal_nav_tabs_border_right_width */
.modal-content .widget.widget-tabs.widget-tabs-responsive > .widget-head ul li,
.widget.widget-tabs.widget-tabs-responsive > .widget-head ul li {
    border-right-width: <?= $modalNavTabsBorderRightWidth; ?>px;
}
.widget.widget-tabs.widget-tabs-responsive > .widget-head ul li {
    border-right-color: <?= $modalNavTabsBorderRightColor; ?>;
}
.modal-content .widget.widget-tabs.widget-tabs-responsive > .widget-head ul li {
    border-right-color: <?= $modalNavTabsBorderRightColor; ?>;
}
/** options_modal_nav_tabs_text_color */
.modal-content .widget.widget-tabs-double > .widget-head ul li:not(.active) a.glyphicons i:before, 
.modal-content .widget.widget-tabs-double .widget-head ul li a.glyphicons i:before,
.modal-content .widget.widget-tabs-double > .widget-head ul li:not(.active) a.glyphicons,
.modal-content .widget.widget-tabs-double .widget-head ul li a.glyphicons {
    color: <?= $modalNavTabsTextIconColor; ?>;
    font-size: <?= $modalNavTabsTextIconFontSize; ?>px;
}
.modal-content .widget.widget-tabs-double > .widget-head ul li a.glyphicons:hover {
    background-color: <?= $modalNavTabsActiveBgColor; ?>;
    color: <?= $modalNavTabsTextIconHoverColor; ?>;
}
/** options_modal_content_text_color, options_modal_content_form_group_label */
.modal-content .span,
.modal-content .form-group span,
.modal-content .form-group label,
.modal-content p {
    color: <?= $modalContentTextColor; ?>;
}
/** options_modal_content_text_font_size */
.modal-content .span,
.modal-content .form-group span,
.modal-content .form-group label,
.modal-content p {
    font-size: <?= $modalContentTextFontSize; ?>px;
}
/** options_modal_content_text_font_styles */
.modal-content .span,
.modal-content .form-group span,
.modal-content p {
    <?php
        $modalContntFontStyle      = explode(';', $modalContentTextFontStyles);

        $modalContentFontWeight    = $modalContntFontStyle[0] ?? 'normal';
        $modalContentFontStyle     = $modalContntFontStyle[1] ?? 'normal';
        $modalContentTextTransform = $modalContntFontStyle[2] ?? 'inherit';
        $modalContentTextDecoraton = $modalContntFontStyle[3] ?? 'inherit';
    ?>
    font-style: <?= $modalContentFontStyle; ?>;
    font-weight: <?= $modalContentFontWeight; ?>;
    text-transform: <?= $modalContentTextTransform; ?>;
    text-decoration: <?= $modalContentTextDecoraton; ?>;
}
/** options_modal_content_close_btn_bg_color, options_modal_content_close_btn_border_color, options_modal_content_close_btn_text_color */
.modal-content .btn-danger {
    background-color: <?= $modalContentCloseBtnBgColor; ?>;
    border-color: <?= $modalContentCloseBtnBorderColor; ?>;
    color: <?= $modalContentCloseBtnTextColor; ?>;
}
/** options_modal_content_close_btn_active_bg_color, options_modal_content_close_btn_active_text_color */
.modal-content .btn-danger:hover {
    background-color: <?= $modalContentCloseBtnHoverBgColor; ?>;
    color: <?= $modalContentCloseBtnHoverTextColor; ?>;
}
.modal-content .btn-success {
    background-color: <?= $modalContentSaveBtnBgColor; ?>;
    border-color: <?= $modalContentSaveBtnBorderColor; ?>;
    color: <?= $modalContentSaveBtnTextColor; ?>;
}
.modal-content .btn-success:hover {
    background: <?= $modalContentSaveBtnHoverBgColor; ?>;
    border-color: <?= $modalContentSaveBtnBorderColor; ?>;
    color: <?= $modalContentSaveBtnHoverTextColor; ?>;
}

/* bootstrap dialog */
.bootstrap-dialog.confirm-modal-header.type-warning .modal-header {
    background-color: <?= $dialogContentHeaderBgColor; ?> !important;
}
.bootstrap-dialog-header .bootstrap-dialog-title {
    color: <?= $dialogContentHeaderTitleColor; ?>;
    font-size: <?= $dialogContentHeaderTitleFontSize; ?>px;
}
.bootstrap-dialog-close-button .btn-close {
    --bs-btn-close-color: <?= $dialogCloseButtonColor; ?>;
    font-size: <?= $dialogCloseButtonFontSize; ?>px;
}
.bootstrap-dialog.confirm-modal-header.type-warning .modal-content {
    background-color: <?= $dialogContentBgColor; ?>;
    border-color: <?= $dialogContentBorderColor; ?>;
}
.bootstrap-dialog-message {
    color: <?= $dialogContentTextColor; ?>;
    font-size: <?= $dialogContentTextFontSize; ?>px;
}
.btn-danger.bootstrap4-dialog-button {
    backgroun-color: <?= $dialogNoBtnBgColor; ?>;
    border-color: <?= $dialogNoBtnBorderColor; ?>;
    color: <?= $dialogNoBtnTextColor; ?>;
}
.btn-danger.bootstrap4-dialog-button:hover {
    background-color: <?= $dialogNoBtnBgHoverColor; ?>;
    border-color: <?= $dialogNoBtnBorderHoverColor; ?>;
    color: <?= $dialogNoBtnTextHoverColor; ?>;
}
.btn-success.bootstrap4-dialog-button {
    background-color: <?= $dialogYesBtnBgColor; ?>;
    border-color: <?= $dialogYesBtnBorderColor; ?>;
    color: <?= $dialogYesBtnTextColor; ?>;
}
.btn-success.bootstrap4-dialog-button:hover {
    background-color: <?= $dialogYesBtnBgHoverColor; ?>;
    border-color: <?= $dialogYesBtnBorderHoverColor; ?>;
    color: <?= $dialogYesBtnTextHoverColor; ?>;
}
.bootstrap4-dialog-button {
    font-size: <?= $dialogBtnTextFontSize; ?>px;
}
/* form elements */
/** options_form_bg_color, options_form_text_color */
form {
    background-color: <?= $formBgColor; ?>;
    color: <?= $formTextColor; ?>;
}
form .form-group select option {
    background-color: <?= $formSelectOptionBgColor; ?>;
    color: <?= $formSelectOptionTextColor; ?>
}
form .form-group textarea,
form .form-group select,
form .form-group input[type="text"]:not(.tt-input),
form .form-group input[type="submit"],
form .form-group input[type="button"] {
    background-color: <?= $formInputElementsBgColor; ?>;
    border-width: <?= $formInputElementsBorderWidth; ?>px;
    border-style: solid;
    border-color: <?= $formInputElementsBorderColor; ?>;
    border-radius: <?= $formInputElementsBorderRadius; ?>;
    color: <?= $formInputElementsTextColor; ?>;
}
form .form-group input[type="text"]:disable,
form .form-group input[type="text"]:readonly {
    background-color: <?= $formInputTextDisableReadonlyBgColor; ?>;
    border-width: <?= $formInputElementsBorderWidth; ?>px;
    border-solid: solid;
    border-color: <?= $formInputTextDisableReadonlyBorderColor; ?>;
    color: <?= $formInputTextDisableReadonlyTextColor; ?>;
}
form .form-group input[type="button"],
form .form-group input[type="submit"] {
    background-color: <?= $formButtonSubmitBgColor; ?>;
    border-width: <?= $formButtonSubmitBorderWidth; ?>px;
    border-style: solid;
    border-color: <?= $formButtonSubmitBorderColor; ?>;
    border-radius: <?= $formButtonSubmitBorderRadius; ?>;
    color: <?= $formButtonSubmitTextColor; ?>;
}
form .form-group input[type="button"]:hover,
form .form-group input[type="submit"]:hover {
    background-color: #444;
    border-color: #fff;
    color: #ffffff;
}
form .form-group label span.switch-left {
    color: #ffffff;
}
form .form-group label {
    color: #686868;
    font-weight: bold;
}
form .form-group .bootstrapfilestyle .group-span-filestyle label {
    background-color: #fafafa;
    border-width: 1px;
    border-style: solid;
    border-color: #cecece;

    color: #686868;
    font-weight: normal;
}
form .form-group .tip-info {
    color: #686868;
    font-size: 17px;
}
/* tabs */
.widget.widget-tabs-double-2>.widget-head {
    background-color: <?= $tabWidgetHeadBgColor; ?>;
    border-width: <?= $tabWidgetHeadBorderWidth; ?>px;
    border-style: solid;
    border-color: <?= $tabWidgetHeadBorderColor; ?>;
}
.widget.widget-tabs-double-2>.widget-head ul {
    height: <?= $tabWidgetHeadNavItemAndLinkHeight; ?>px;
}
.widget.widget-tabs-double-2>.widget-head ul li {
    border-right-width: <?= $tabWidgetNavItemBorderRightWidth; ?>px;
    border-right-style: solid;
    border-right-color: <?= $tabWidgetNavItemBorderRightColor; ?>;
    height: <?= $tabWidgetHeadNavItemAndLinkHeight; ?>px;
}
.widget.widget-tabs-double-2>.widget-head ul li a.glyphicons {
    color: <?= $tabWidgetNavLinkTextColor; ?>;
    font-size: <?= $tabWidgetNavLinkTextFontSize; ?>px;
    min-width: <?= $tabWidgetNavLinkMinWidth; ?>px;
    height: <?= $tabWidgetHeadNavItemAndLinkHeight; ?>px;
    text-align: <?= $tabWidgetNavLinkTextAlign; ?>;
}
.widget.widget-tabs-double-2>.widget-head ul li a.glyphicons i {
    height: <?= $tabWidgetNavLinkIconHeight; ?>px;
}
.widget.widget-tabs>.widget-head ul li a i:before {
    color: <?= $tabWidgetLinkIconColor; ?>;
    font-size: <?= $tabWidgetLinkIconFontSize; ?>px;
}
.widget.widget-tabs>.widget-head ul li a.glyphicons:hover,
.widget.widget-tabs>.widget-head ul li.active a.active.glyphicons, 
.widget.widget-tabs>.widget-head ul li.active a.active.glyphicons i:before,
.widget.widget-tabs>.widget-head ul li.active a.glyphicons, 
.widget.widget-tabs>.widget-head ul li.active a.glyphicons i:before {
    background-color: #ffffff;
    color: #e61c23;
}
.widget.widget-tabs>.widget-head ul li.active a.active.glyphicons:hover,
.widget.widget-tabs>.widget-head ul li.active a.active.glyphicons,
.widget.widget-tabs>.widget-head ul li.active a.glyphicons:hover,
.widget.widget-tabs>.widget-head ul li.active a.glyphicons {
    border-color: #ffffff;
}
/* date picker, date range picker and bootstrap date time picker */
.daterangepicker {
    color: #686868;
    background-color: #ffffff;
    border-radius: 4px;
    border-width: 1px;
    border-style: solid;
    border-color: #dddddd;
}
/** daterangepicker ranges button */
.daterangepicker .ranges li {
    background-color: #f5f5f5;
    color: #686868;
    font-size: 13px !important;
    border-radius: 4px;

    border-width: 1px;
    border-style: solid;
    border-color: #f5f5f5;

    border-bottom-color: #e5e5e5 !important;
}
.daterangepicker .ranges li.active, 
.daterangepicker .ranges li:hover {
    background: #e61c23;
    border-color:  #e61c23;
    color: #ffffff;
}
.daterangepicker td.active, 
.daterangepicker td.active:hover {
    background-color: #357ebd;
    border-color: transparent;
    color: #ffffff;
}
.daterangepicker td.in-range {
    background-color: #ebf4f8;
    border-color: transparent;
    color: #000000;
    border-radius: 0;
}
.daterangepicker td.start-date {
    border-radius: 4px 0 0 4px;
}
.daterangepicker td.end-date {
    border-radius: 0 4px 4px 0;
}
/* .available */
.daterangepicker .calendar-table td, 
.daterangepicker .calendar-table th {
    border-width: 1px;
    border-style: solid;
    border-color: transparent;

    border-radius: 4px;
    color: #686868;

    font-size: 12px;
    text-align: center;
}
.daterangepicker td.available:hover, 
.daterangepicker th.available:hover {
    background-color: #eeeeee;
    border-color: transparent;
}
.daterangepicker td.off, 
.daterangepicker td.off.end-date,
.daterangepicker td.off.in-range, 
.daterangepicker td.off.start-date {
    background-color: #ffffff;
    border-color: transparent;
    color: #999999;
}
.daterangepicker .drp-selected {
    color: #686868;
    font-size: 12px;
}
.daterangepicker .drp-buttons .btn {
    font-size: 12px;
}
.daterangepicker .btn-danger,
.daterangepicker .cancelBtn {
    background-color: #ffffff !important;
    border-color: #bd362f !important;
    color: #bd362f !important;
}
.daterangepicker .btn-danger:hover,
.daterangepicker .cancelBtn:hover {
    background-color: #bd362f !important;
    border-color: #bd362f !important;
    color: #ffffff !important;
}
.daterangepicker .btn-success,
.daterangepicker .applyBtn {
    background-color: #ffffff !important;
    border-color: #72af46 !important;
    color: #72af46 !important;
}
.daterangepicker .btn-success:hover,
.daterangepicker .applyBtn:hover {
    background-color: #72af46 !important;
    border-color: #72af46 !important;
    color: #ffffff !important;
}
/** datepicker / datetimepicker */
.datepicker {
    color: #686868;
    background-color: #ffffff;
    border-radius: 4px;
    border-width: 1px;
    border-style: solid;
    border-color: #dddddd;
}
.datepicker .picker-switch,
.datepicker .next,
.datepicker .prev {
    text-align: center;
    border-radius: 4px;
    color: #212529;
}
.datepicker table thead tr th:hover {
    background: #f8f9fa;
}
.datepicker thead th.dow {
    backgkround-color: #e61c23 !important;
    color: #ffffff;
}
.datepicker table td,
.datepicker table th {
    border-radius: 4px;
    text-align: center;
}
.datepicker table tr td.day {
    color: #212529;
}
.datepicker table tr td.day:hover {
    background-color: #eeeeee;
}
.datepicker table tr td.day.old.weekend {
    color: #999999;
}
.datepicker .table-condensed tr td.day.active {
    backgkround-color: #e61c23 !important;
    color: #ffffff;
}
.datepicker table td.day.active.today:before {
    border-bottom-color: #ffffff;
}
/** timepicker specific css */
.datepicker .picker-switch [data-action="togglePicker"] {
    background-color: #fff;
    color: #e61c23 !important;
}
.datepicker .picker-switch [data-action="togglePicker"]:hover {
    background-color: #f8f9fa;
}
.datepicker .timepicker .btn {
    background-color: #fff;
    color: #e61c23 !important;
}
.datepicker .timepicker .btn:hover {
    background-color: #f8f9fa;
}
.datepicker .timepicker table tr:nth-child(2) .timepicker-hour,
.datepicker .timepicker table tr:nth-child(2) .timepicker-minute,
.datepicker .timepicker table tr:nth-child(2) .timepicker-second,
.datepicker .timepicker table tr:nth-child(2) .separator {
    background-color: #fff;
    color: #212529;
}
/** boostrap-datetimepicker4 */
.bootstrap-datetimepicker-widget {
    color: #686868;
    background-color: #ffffff;
    border-radius: 4px;
    border-width: 1px;
    border-style: solid;
    border-color: #dddddd;
}
.bootstrap-datetimepicker-widget.dropdown-menu {
    background-color: #ffffff;
    font-size: 14px;
    text-align: left;

    border-width: 1px;
    border-style: solid;
    border-color: #cccccc;

    border-radius: 4px;
}
.bootstrap-datetimepicker-widget li {
    border-bottom-width: 1px;
    border-bottom-style: solid;
    border-bottom-color: #e5e5e5;
}
.bootstrap-datetimepicker-widget li .datepicker {
    border-radius: 4px;
}
.bootstrap-datetimepicker-widget li .datepicker .next,
.bootstrap-datetimepicker-widget li .datepicker .prev {
    text-align: center;
    border-radius: 4px;
    color: #212529;
}
.bootstrap-datetimepicker-widget table thead tr th:hover {
    background: #f8f9fa;
}
.bootstrap-datetimepicker-widget .datepicker thead th.dow {
    backgkround-color: #e61c23 !important;
    color: #ffffff;
}
.bootstrap-datetimepicker-widget table td, 
.bootstrap-datetimepicker-widget table th {
    border-radius: 4px;
    text-align: center;
}
.bootstrap-datetimepicker-widget table td.old, 
.bootstrap-datetimepicker-widget table td.new {
    color: #dee2e6;
    text-align: center;
}
.bootstrap-datetimepicker-widget .datepicker .table-condensed tr td.active {
    backgkround-color: #e61c23 !important;
    color: #ffffff;
}
.bootstrap-datetimepicker-widget table td.active.today:before {
    border-bottom-color: #ffffff;
}
.bootstrap-datetimepicker-widget .datepicker table tr td.day:hover {
    background-color: #eeeeee;
}
.bootstrap-datetimepicker-widget a[data-action] {
    color: #e61c23;
}