<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = $this->zoneconfig['conf']['id'];

$form               = $this->form;
$scheme             = $this->schemes;
$loginBackground    = '/MelisCore/images/login/melis-blackboard.jpg';
$loginLogo          = '/MelisCore/images/login/melis-box.png';
$sidebarHeaderTitle = strtoupper($this->translate('tr_meliscore_header Title'));
$sidebarHeaderLogo  = '/MelisCore/images/dashboard/melis-logo.svg';
$favicon            = 'favicon.ico';

$tooltips = array(
    'melis_core_platform_color_primary_color' => 'tr_meliscore_platform_scheme_primary_tooltip',
    'melis_core_platform_color_secondary_color' => 'tr_meliscore_platform_scheme_secondary_tooltip',
    'melis_core_platform_color_sidebar_bg_color' => 'tr_melis_core_platform_color_sidebar_bg_color_tooltip',
    'melis_core_platform_color_login_link_color' => 'tr_melis_core_platform_color_login_link_color_tooltip'
);

if ($scheme) {

    if ($scheme->getLoginBackground())
        $loginBackground = $scheme->getLoginBackground();

    if ($scheme->getLoginLogo())
        $loginLogo = $scheme->getLoginLogo();

    if ($scheme->getSidebarHeaderText())
        $sidebarHeaderTitle = $scheme->getSidebarHeaderText();

    if ($scheme->getSidebarHeaderLogo())
        $sidebarHeaderLogo = $scheme->getSidebarHeaderLogo();

    if ($scheme->getFavicon())
        $favicon = $scheme->getFavicon();
}

$headerTitle = '<span id="platform-scheme-sidebar-header-title">' . $this->escapeHtml($sidebarHeaderTitle) . '</span>';
$headerTitleLen = str_replace(' ', '', trim($sidebarHeaderTitle));
$headerTitleLen = strlen($headerTitleLen);

if ($headerTitleLen > 13) {
    $headerTitle = '<span id="platform-scheme-sidebar-header-title" class="ml-header">' . $this->escapeHtml($sidebarHeaderTitle) . '</span>';
}

?>
<div id="<?= $id; ?>" class="tab-pane container-level-a" data-melisKey='<?= $this->melisKey; ?>'>
    <?php
    if ($this->hasAccess) { ?>
        <div class="me-heading bg-white border-bottom">
            <div class="d-flex flex-row row">
                <div class="me-hl col-12 col-md-6">
                    <h1 class="content-heading"><?= $this->translate('tr_meliscore_platform_scheme') ?></h1>
                    <p><?= $this->translate('tr_meliscore_platform_scheme_subtitle') ?></p>
                </div>
                <div class="me-hr col-12 col-md-6">
                    <a id="resetPlatformScheme" class="btn btn-danger" title="<?= $this->translate('tr_meliscore_platform_scheme_reset_alt') ?>"><i class="fa fa-rotate-left i-space"></i><?= $this->translate('tr_meliscore_platform_scheme_reset_text') ?></a>
                    <a id="savePlatformScheme" class="btn btn-success" title="Save"><i class="fa fa-save i-space"></i><?= $this->translate('tr_meliscore_tool_gen_save') ?></a>
                </div>
            </div>
        </div>
        <div class="spacing-x2 innerAll container-fluid">
            <h3><?= $this->translate('tr_meliscore_platform_color_scheme') ?></h3>
            <?php
            echo $this->form()->openTag($form);
            foreach ($form->getElements() as $elementKey => $element) {
                $el = $element->getValue();
            ?>
                <div class="col-12 col-md-6">
                    <div class="form-group">
                        <label for="" class="d-flex flex-row justify-content-between">
                            <div class="label-text"><?= $element->getLabel(); ?></div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate($tooltips[$element->getName()]); ?>"></i>
                        </label>
                        <div class="input-group platform-scheme osta_color_code">
                            <?= $this->formRow($element->setLabel("")); ?>
                            <span class="input-group-addon">
                                <input type="hidden" class="minicolor" value="<?= $element->getValue(); ?>" />
                            </span>
                        </div>
                    </div>
                </div>
            <?php
            }
            echo $this->form()->closeTag();
            ?>
            <button type="button" class="btn btn-primary open-theme-options mt-2">Open theme options</button>
            <h3 class="mt-4"><?= $this->translate('tr_meliscore_platform_scheme_images'); ?></h3>
            <form method="POST" name="melis_core_platform_scheme_images" id="melis_core_platform_scheme_images" enctype="multipart/form-data">
                <!-- FAVICON -->
                <div class="melis-ptb20">
                    <div class="row">
                        <div class="col-12 col-md-7 col-lg-4">
                            <div class="form-group">
                                <label for="favicon" class="d-flex flex-row justify-content-between">
                                    <div class="label-text"><?= $this->translate('tr_meliscore_platform_scheme_form_favicon') ?></div>
                                    <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate('tr_meliscore_platform_scheme_favicon_tooltip'); ?>"></i>
                                </label>
                                <div class="input-group">
                                    <input type="file" id="favicon" name="favicon" onchange="melisCoreTool.changeImage('#platform-scheme-favicon', this)">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="meliscore-platform-scheme-favicon">
                                <img src="<?= $favicon ?>" class="img-fluid" width="64" height="64" id="platform-scheme-favicon">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /FAVICON -->
                <!-- LOGIN LOGO -->
                <div class="melis-ptb20">
                    <div class="row">
                        <div class="col-12 col-md-7 col-lg-4">
                            <div class="form-group">
                                <label for="login-logo" class="d-flex flex-row justify-content-between">
                                    <div class="label-text"><?= $this->translate('tr_meliscore_platform_scheme_form_login_logo') ?></div>
                                    <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate('tr_meliscore_platform_scheme_login_logo_tooltip'); ?>"></i>
                                </label>
                                <div class="input-group">
                                    <input type="file" id="login_logo" name="login_logo" onchange="melisCoreTool.changeImage('#platform-scheme-login-logo', this)">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="meliscore-platform-scheme-login-logo">
                                <img class="melis-login-logo" src="<?= $loginLogo ?>" id="platform-scheme-login-logo" class="img-fluid">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /LOGIN LOGO -->
                <!-- LOGIN BACKGROUND -->
                <div class="melis-ptb20">
                    <div class="row">
                        <div class="col-12 col-md-7 col-lg-4">
                            <div class="form-group">
                                <label for="login-background" class="d-flex flex-row justify-content-between">
                                    <div class="label-text"><?= $this->translate('tr_meliscore_platform_scheme_form_login_background') ?></div>
                                    <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate('tr_meliscore_platform_scheme_login_background_tooltip'); ?>"></i>
                                </label>
                                <div class="input-group">
                                    <input type="file" id="login_background" name="login_background" onchange="melisCoreTool.changeImage('#platform-scheme-login-background', this)">
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="meliscore-platform-scheme-login-background">
                                <img src="<?= $loginBackground ?>" class="img-fluid" id="platform-scheme-login-background">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /LOGIN BACKGROUND -->

                <!-- SIDEBAR ICON AND TITLE -->
                <div class="melis-ptb20">
                    <div class="row">
                        <div class="col-12 col-md-7 col-lg-4">
                            <div class="form-group">
                                <label for="sidebar-header-logo" class="d-flex flex-row justify-content-between">
                                    <div class="label-text"><?= $this->translate('tr_meliscore_platform_scheme_form_sidebar_header_logo') ?></div>
                                    <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate('tr_meliscore_platform_scheme_sidebar_header_logo_tooltip'); ?>"></i>
                                </label>
                                <div class="input-group">
                                    <input type="file" id="sidebar_header_logo" name="sidebar_header_logo" onchange="melisCoreTool.changeImage('#platform-scheme-sidebar-header-logo', this)">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="sidebar-header-title" class="d-flex flex-row justify-content-between">
                                    <div class="label-text"><?= $this->translate('tr_meliscore_platform_scheme_form_sidebar_header_title') ?></div>
                                    <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate('tr_meliscore_platform_scheme_sidebar_header_title_tooltip'); ?>"></i>
                                </label>
                                <div class="input-group">
                                    <input type="text" id="sidebar_header_text" name="sidebar_header_text" maxlength="45" class="form-control" value="<?= $sidebarHeaderTitle ?>">
                                </div>
                            </div>
                        </div>

                        <div class="col-12 col-md-12 col-lg-6">
                            <div class="melis-core-platform-container">
                                <div class="meliscore-platform-scheme-sidebar-container melis-primary-bg">
                                    <img alt="melis platform" src="<?= $sidebarHeaderLogo ?>" id="platform-scheme-sidebar-header-logo" class="img-fluid" width="30">
                                    <?= $headerTitle ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="platform-theme-options-overlay" style="display: none;"></div>
            <div class="platform-theme-options">
                <a href="#" class="platform-theme-options-toggle in-out">
                    <div class="overlay-loader">
                        <img class="loader-icon spinning-cog" src="/MelisCore/assets/images/cog12.svg" alt="Toggle platform theme options" width="20" height="20" />
                    </div>
                </a>
                <div class="platform-theme-options-title">
                    <h6>Platform Theme Options</h6>
                    <a href="#" class="close-tools"><i class="fa fa-close"></i></a>
                </div>
                <div class="platform-theme-options-detail">
                    <div class="platform-theme-options-block">
                        <div class="platform-theme-options-tools-info">

                            <?php
                            $platformThemeOptionForm = $this->platformThemeOptionForm;
                            echo $this->form()->openTag($platformThemeOptionForm);
                            ?>

                            <div id="theme-options" class="accordion">
                                <div class="accordion-item general-options">
                                    <h3 class="accordion-header active-header">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#general-options" aria-expanded="true" aria-controls="general-options">
                                            General Options
                                        </button>
                                    </h3>
                                    <div id="general-options" class="accordion-collapse collapse show" data-bs-parent="#theme-options">
                                        <div class="accordion-body">
                                            <div id="accordion-sidebar" class="accordion">
                                                <div class="accordion-item top-logo">
                                                    <h6 class="accordion-header">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#top-logo" aria-expanded="false" aria-controls="top-logo">
                                                            Top logo
                                                        </button>
                                                    </h6>
                                                    <div id="top-logo" class="accordion-collapse collapse" data-bs-parent="#accordion-sidebar">
                                                        <div class="accordion-body">
                                                            <?php
                                                            foreach ($platformThemeOptionForm->getElements() as $elementKey => $element) {
                                                                if ($element->getAttribute('category') == 'logo') { ?>
                                                                    <div class="form-group">
                                                                        <label for="<?= $element->getAttribute('id') ?>" class="d-flex flex-row justify-content-between">
                                                                            <div class="label-text"><?= $element->getLabel(); ?></div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate($element->getOptions()['tooltip']); ?>"></i>
                                                                        </label>

                                                                        <?php
                                                                        if (strpos($element->getName(), 'color')) { ?>
                                                                            <div class="input-group platform-scheme osta_color_code">
                                                                                <?= $this->formRow($element->setLabel("")); ?>
                                                                                <span class="input-group-addon">
                                                                                    <input type="hidden" class="minicolor" value="<?= $element->getValue(); ?>" />
                                                                                </span>
                                                                            </div>
                                                                        <?php  } elseif (strpos($element->getName(), 'size')) { ?>
                                                                            <div class="row">
                                                                                <div class="col-9">
                                                                                    <div id="footer-version-font-size-range-slider-min" class="footer-version-font-size-range-slider-min" style="border: 0; color: #f6931f; font-weight: bold;"></div>
                                                                                </div>
                                                                                <div class="col-3">
                                                                                    <?= $this->formRow($element->setLabel("")); ?>
                                                                                </div>
                                                                            </div>
                                                                        <?php } ?>
                                                                    </div>
                                                                <?php    }
                                                                ?>
                                                            <?php
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="accordion-item user-profile">
                                                    <h6 class="accordion-header">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#user-profile" aria-expanded="false" aria-controls="user-profile">
                                                            User profile
                                                        </button>
                                                    </h6>
                                                    <div id="user-profile" class="accordion-collapse collapse" data-bs-parent="#accordion-sidebar">
                                                        <div class="accordion-body">
                                                            <?php
                                                            foreach ($platformThemeOptionForm->getElements() as $elementKey => $element) {
                                                                if ($element->getAttribute('category') == 'user_profile') { ?>
                                                                    <div class="form-group">
                                                                        <label for="<?= $element->getAttribute('id') ?>" class="d-flex flex-row justify-content-between">
                                                                            <div class="label-text"><?= $element->getLabel(); ?></div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate($element->getOptions()['tooltip']); ?>"></i>
                                                                        </label>

                                                                        <?php
                                                                        if (strpos($element->getName(), 'color')) { ?>
                                                                            <div class="input-group platform-scheme osta_color_code">
                                                                                <?= $this->formRow($element->setLabel("")); ?>
                                                                                <span class="input-group-addon">
                                                                                    <input type="hidden" class="minicolor" value="<?= $element->getValue(); ?>" />
                                                                                </span>
                                                                            </div>
                                                                        <?php  } elseif (strpos($element->getName(), 'radius')) { ?>
                                                                            <div class="input-group">
                                                                                <?= $this->formRow($element->setLabel("")); ?>
                                                                                <small>* Need to include the value and unit</small>
                                                                            </div>
                                                                        <?php    } ?>
                                                                    </div>
                                                            <?php    }
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="accordion-item sidebar-menu">
                                                    <h6 class="accordion-header">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#sidebar-menu" aria-expanded="false" aria-controls="sidebar-menu">
                                                            Menu
                                                        </button>
                                                    </h6>
                                                    <div id="sidebar-menu" class="accordion-collapse collapse" data-bs-parent="#accordion-sidebar">
                                                        <div class="accordion-body">
                                                            <?php
                                                            foreach ($platformThemeOptionForm->getElements() as $elementKey => $element) {
                                                                if ($element->getAttribute('category') == 'menu') { ?>
                                                                    <div class="form-group">
                                                                        <label for="<?= $element->getAttribute('id') ?>" class="d-flex flex-row justify-content-between">
                                                                            <div class="label-text"><?= $element->getLabel(); ?></div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate($element->getOptions()['tooltip']); ?>"></i>
                                                                        </label>

                                                                        <?php
                                                                        if (strpos($element->getName(), 'color')) { ?>
                                                                            <div class="input-group platform-scheme osta_color_code">
                                                                                <?= $this->formRow($element->setLabel("")); ?>
                                                                                <span class="input-group-addon">
                                                                                    <input type="hidden" class="minicolor" value="<?= $element->getValue(); ?>" />
                                                                                </span>
                                                                            </div>
                                                                        <?php  } ?>
                                                                    </div>
                                                                <?php    }
                                                                ?>
                                                            <?php
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="accordion-item footer-version">
                                                    <h6 class="accordion-header">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#footer-version" aria-expanded="false" aria-controls="footer-version">
                                                            Footer
                                                        </button>
                                                    </h6>
                                                    <div id="footer-version" class="accordion-collapse collapse" data-bs-parent="#accordion-sidebar">
                                                        <div class="accordion-body">
                                                            <?php
                                                            foreach ($platformThemeOptionForm->getElements() as $elementKey => $element) {
                                                                if ($element->getAttribute('category') == 'footer') { ?>
                                                                    <div class="form-group">
                                                                        <label for="<?= $element->getAttribute('id') ?>" class="d-flex flex-row justify-content-between">
                                                                            <div class="label-text"><?= $element->getLabel(); ?></div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate($element->getOptions()['tooltip']); ?>"></i>
                                                                        </label>

                                                                        <?php
                                                                        if (strpos($element->getName(), 'color')) { ?>
                                                                            <div class="input-group platform-scheme osta_color_code">
                                                                                <?= $this->formRow($element->setLabel("")); ?>
                                                                                <span class="input-group-addon">
                                                                                    <input type="hidden" class="minicolor" value="<?= $element->getValue(); ?>" />
                                                                                </span>
                                                                            </div>
                                                                        <?php  } elseif (strpos($element->getName(), 'size')) { ?>
                                                                            <div class="row">
                                                                                <div class="col-9">
                                                                                    <div id="footer-version-font-size-range-slider-min" class="footer-version-font-size-range-slider-min" style="border: 0; color: #f6931f; font-weight: bold;"></div>
                                                                                </div>
                                                                                <div class="col-3">
                                                                                    <?= $this->formRow($element->setLabel("")); ?>
                                                                                </div>
                                                                            </div>
                                                                        <?php } ?>
                                                                    </div>
                                                                <?php    }
                                                                ?>
                                                            <?php
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="accordion-item header">
                                                    <h6 class="accordion-header">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#header-navigation" aria-expanded="false" aria-controls="header-navigation">
                                                            Header navigation
                                                        </button>
                                                    </h6>
                                                    <div id="header-navigation" class="accordion-collapse collapse" data-bs-parent="#accordion-sidebar">
                                                        <div class="accordion-body">
                                                            <?php
                                                            foreach ($platformThemeOptionForm->getElements() as $elementKey => $element) {
                                                                if ($element->getAttribute('category') == 'header') { ?>
                                                                    <div class="form-group">
                                                                        <label for="<?= $element->getAttribute('id') ?>" class="d-flex flex-row justify-content-between">
                                                                            <div class="label-text"><?= $element->getLabel(); ?></div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate($element->getOptions()['tooltip']); ?>"></i>
                                                                        </label>

                                                                        <?php
                                                                        if (strpos($element->getName(), 'color')) { ?>
                                                                            <div class="input-group platform-scheme osta_color_code">
                                                                                <?= $this->formRow($element->setLabel("")); ?>
                                                                                <span class="input-group-addon">
                                                                                    <input type="hidden" class="minicolor" value="<?= $element->getValue(); ?>" />
                                                                                </span>
                                                                            </div>
                                                                        <?php  } ?>
                                                                    </div>
                                                                <?php    }
                                                                ?>
                                                            <?php
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="accordion-item pto-bubble-plugins">
                                                    <h6 class="accordion-header">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#pto-bubble-plugins" aria-expanded="false" aria-controls="pto-bubble-plugins">
                                                            Bubble plugins
                                                        </button>
                                                    </h6>
                                                    <div id="pto-bubble-plugins" class="accordion-collapse collapse" data-bs-parent="#accordion-sidebar">
                                                        <div class="accordion-body">
                                                            <?php
                                                            foreach ($platformThemeOptionForm->getElements() as $elementKey => $element) {
                                                                if ($element->getAttribute('category') == 'bubble') { ?>
                                                                    <div class="form-group">
                                                                        <label for="<?= $element->getAttribute('id') ?>" class="d-flex flex-row justify-content-between">
                                                                            <div class="label-text"><?= $element->getLabel(); ?></div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate($element->getOptions()['tooltip']); ?>"></i>
                                                                        </label>

                                                                        <?php
                                                                        if (strpos($element->getName(), 'color')) { ?>
                                                                            <div class="input-group platform-scheme osta_color_code">
                                                                                <?= $this->formRow($element->setLabel("")); ?>
                                                                                <span class="input-group-addon">
                                                                                    <input type="hidden" class="minicolor" value="<?= $element->getValue(); ?>" />
                                                                                </span>
                                                                            </div>
                                                                        <?php  } elseif (strpos($element->getName(), 'size')) { ?>
                                                                            <div class="row">
                                                                                <div class="col-9">
                                                                                    <div id="footer-version-font-size-range-slider-min" class="footer-version-font-size-range-slider-min" style="border: 0; color: #f6931f; font-weight: bold;"></div>
                                                                                </div>
                                                                                <div class="col-3">
                                                                                    <?= $this->formRow($element->setLabel("")); ?>
                                                                                </div>
                                                                            </div>
                                                                        <?php } ?>
                                                                    </div>
                                                                <?php    }
                                                                ?>
                                                            <?php
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="accordion-item dashboard-plugins">
                                                    <h6 class="accordion-header">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#dashboard-plugins" aria-expanded="false" aria-controls="dashboard-plugins">
                                                            Dashboard plugins
                                                        </button>
                                                    </h6>
                                                    <div id="dashboard-plugins" class="accordion-collapse collapse" data-bs-parent="#accordion-sidebar">
                                                        <div class="accordion-body">
                                                            <?php
                                                            foreach ($platformThemeOptionForm->getElements() as $elementKey => $element) {
                                                                if ($element->getAttribute('category') == 'dashboard_plugin') { ?>
                                                                    <div class="form-group">
                                                                        <label for="<?= $element->getAttribute('id') ?>" class="d-flex flex-row justify-content-between">
                                                                            <div class="label-text"><?= $element->getLabel(); ?></div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate($element->getOptions()['tooltip']); ?>"></i>
                                                                        </label>

                                                                        <?php
                                                                        if (strpos($element->getName(), 'color')) { ?>
                                                                            <div class="input-group platform-scheme osta_color_code">
                                                                                <?= $this->formRow($element->setLabel("")); ?>
                                                                                <span class="input-group-addon">
                                                                                    <input type="hidden" class="minicolor" value="<?= $element->getValue(); ?>" />
                                                                                </span>
                                                                            </div>
                                                                        <?php  } elseif (strpos($element->getName(), 'size')) { ?>
                                                                            <div class="row">
                                                                                <div class="col-9">
                                                                                    <div id="footer-version-font-size-range-slider-min" class="footer-version-font-size-range-slider-min" style="border: 0; color: #f6931f; font-weight: bold;"></div>
                                                                                </div>
                                                                                <div class="col-3">
                                                                                    <?= $this->formRow($element->setLabel("")); ?>
                                                                                </div>
                                                                            </div>
                                                                        <?php } elseif (strpos($element->getName(), 'style')) { ?>
                                                                            <div class="btn-group btn-group-font-style" role="group" aria-label="Font style checkbox toggle button group">
                                                                                <input type="checkbox" class="btn-check" id="plugins-menu-box-title-bold" autocomplete="off">
                                                                                <label class="btn btn-default" for="plugins-menu-box-title-bold"><strong>B</strong></label>

                                                                                <input type="checkbox" class="btn-check" id="plugins-menu-box-title-italic" autocomplete="off">
                                                                                <label class="btn btn-default" for="plugins-menu-box-title-italic"><em>I</em></label>

                                                                                <input type="checkbox" class="btn-check" id="plugins-menu-box-title-uppercase" autocomplete="off">
                                                                                <label class="btn btn-default" for="plugins-menu-box-title-uppercase" style="text-transform: uppercase;">TT</label>

                                                                                <input type="checkbox" class="btn-check" id="plugins-menu-box-title-underline" autocomplete="off">
                                                                                <label class="btn btn-default" for="plugins-menu-box-title-underline" style="text-decoration: underline;">U</label>
                                                                            </div>
                                                                        <?php   }
                                                                        ?>
                                                                    </div>
                                                                <?php    }
                                                                ?>
                                                            <?php
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="accordion-item dashboard-plugins-menu">
                                                    <h6 class="accordion-header">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#dashboard-plugins-menu" aria-expanded="false" aria-controls="dashboard-plugins-menu">
                                                            Dashboard plugins menu
                                                        </button>
                                                    </h6>
                                                    <div id="dashboard-plugins-menu" class="accordion-collapse collapse" data-bs-parent="#accordion-sidebar">
                                                        <div class="accordion-body">
                                                            <?php
                                                            foreach ($platformThemeOptionForm->getElements() as $elementKey => $element) {
                                                                if ($element->getAttribute('category') == 'dashboard_plugin_menu') { ?>
                                                                    <div class="form-group">
                                                                        <label for="<?= $element->getAttribute('id') ?>" class="d-flex flex-row justify-content-between">
                                                                            <div class="label-text"><?= $element->getLabel(); ?></div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?= $this->translate($element->getOptions()['tooltip']); ?>"></i>
                                                                        </label>

                                                                        <?php
                                                                        if (strpos($element->getName(), 'color')) { ?>
                                                                            <div class="input-group platform-scheme osta_color_code">
                                                                                <?= $this->formRow($element->setLabel("")); ?>
                                                                                <span class="input-group-addon">
                                                                                    <input type="hidden" class="minicolor" value="<?= $element->getValue(); ?>" />
                                                                                </span>
                                                                            </div>
                                                                        <?php  } elseif (strpos($element->getName(), 'size')) { ?>
                                                                            <div class="row">
                                                                                <div class="col-9">
                                                                                    <div id="footer-version-font-size-range-slider-min" class="footer-version-font-size-range-slider-min" style="border: 0; color: #f6931f; font-weight: bold;"></div>
                                                                                </div>
                                                                                <div class="col-3">
                                                                                    <?= $this->formRow($element->setLabel("")); ?>
                                                                                </div>
                                                                            </div>
                                                                        <?php } elseif (strpos($element->getName(), 'style')) { ?>
                                                                            <div class="btn-group btn-group-font-style" role="group" aria-label="Font style checkbox toggle button group">
                                                                                <input type="checkbox" class="btn-check" id="plugins-menu-box-title-bold" autocomplete="off">
                                                                                <label class="btn btn-default" for="plugins-menu-box-title-bold"><strong>B</strong></label>

                                                                                <input type="checkbox" class="btn-check" id="plugins-menu-box-title-italic" autocomplete="off">
                                                                                <label class="btn btn-default" for="plugins-menu-box-title-italic"><em>I</em></label>

                                                                                <input type="checkbox" class="btn-check" id="plugins-menu-box-title-uppercase" autocomplete="off">
                                                                                <label class="btn btn-default" for="plugins-menu-box-title-uppercase" style="text-transform: uppercase;">TT</label>

                                                                                <input type="checkbox" class="btn-check" id="plugins-menu-box-title-underline" autocomplete="off">
                                                                                <label class="btn btn-default" for="plugins-menu-box-title-underline" style="text-decoration: underline;">U</label>
                                                                            </div>
                                                                        <?php   } elseif (strpos($element->getName(), 'radius')) { ?>
                                                                            <div class="input-group">
                                                                                <?= $this->formRow($element->setLabel("")); ?>
                                                                                <small>* Need to include the value and unit</small>
                                                                            </div>
                                                                        <?php    } ?>
                                                                    </div>
                                                                <?php    }
                                                                ?>
                                                            <?php
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- end of #accordion-sidebar -->
                                        </div>
                                    </div>
                                </div>

                                <div class="accordion-item component-options">
                                    <h3 class="accordion-header">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#component-options" aria-expanded="false" aria-controls="component-options">
                                            Component Options
                                        </button>
                                    </h3>
                                    <div id="component-options" class="accordion-collapse collapse" data-bs-parent="#theme-options">
                                        <div class="accordion-body">
                                            <div id="components-accordion" class="accordion">
                                                <div class="accordion-item component-modal">
                                                    <h6 class="accordion-header">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#component-modal" aria-expanded="false" aria-controls="component-modal">
                                                            Modal
                                                        </button>
                                                    </h6>
                                                    <div id="component-modal" class="accordion-collapse collapse show" data-bs-parent="#components-accordion">
                                                        <div class="accordion-body">
                                                            <!-- options_modal_bg_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_bg_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal background color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal background color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_bg_color" id="options_modal_bg_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal background color" value="#fff">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#fff" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_border_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_border_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal background color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal background color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_border_color" id="options_modal_border_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal background color" value="#fff">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#fff" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_border_radius_size -->
                                                            <div class="form-group">
                                                                <label for="options_modal_border_radius_size" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal border radius size</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal border radius size"></i>
                                                                </label>
                                                                <div class="row">
                                                                    <div class="col-9">
                                                                        <div id="modal-border-radius-size-range-slider-min" class="modal-border-radius-size-range-slider-min" style="border: 0; color: #f6931f; font-weight: bold;"></div>
                                                                    </div>
                                                                    <div class="col-3">
                                                                        <input type="text" name="options_modal_border_radius_size" id="options_modal_border_radius_size" class="modal-border-radius-size-range-slider-value range-slider-value form-control" />
                                                                    </div>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_nav_tabs_bg_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_nav_tabs_bg_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal nav tabs background color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal nav tabs background color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_nav_tabs_bg_color" id="options_modal_nav_tabs_bg_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal nav tabs background color" value="#e61c23">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#e61c23" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_nav_tabs_active_bg_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_nav_tabs_active_bg_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal nav tabs active background color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal nav active tab background color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_nav_tabs_active_bg_color" id="options_modal_nav_tabs_active_bg_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal nav active tab background color" value="#fff">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#fff" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_nav_tabs_text_icon_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_nav_tabs_text_icon_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal nav tabs text color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal nav tabs text color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_nav_tabs_text_icon_color" id="options_modal_nav_tabs_text_icon_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal nav tabs text color" value="#fff">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#fff" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_nav_tabs_text_icon_active_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_nav_tabs_text_icon_active_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal nav tabs text hover color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal nav tabs text hover color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_nav_tabs_text_icon_active_color" id="options_modal_nav_tabs_text_icon_active_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal nav tabs text hover color" value="#e61c23">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#e61c23" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_nav_tabs_text_icon_font_size -->
                                                            <div class="form-group">
                                                                <label for="options_modal_nav_tabs_text_icon_font_size" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal nav tabs font size</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal nav tabs font size"></i>
                                                                </label>
                                                                <div class="row">
                                                                    <div class="col-9">
                                                                        <div id="modal-tabs-font-size-range-slider-min" class="modal-tabs-font-size-range-slider-min" style="border: 0; color: #f6931f; font-weight: bold;"></div>
                                                                    </div>
                                                                    <div class="col-3">
                                                                        <input type="text" name="options_modal_nav_tabs_text_icon_font_size" id="options_modal_nav_tabs_text_icon_font_size" class="modal-tabs-font-size-range-slider-value range-slider-value form-control" />
                                                                    </div>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_nav_tabs_border_right_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_nav_tabs_border_right_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal nav tab border right color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal nav tab border right color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_nav_tabs_border_right_color" id="options_modal_nav_tabs_border_right_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal nav tab border right color" value="#ce5459">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#ce5459" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_nav_tabs_border_right_width -->
                                                            <div class="form-group">
                                                                <label for="options_modal_nav_tabs_border_right_width" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal nav tabs border right width</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal nav tabs border right width"></i>
                                                                </label>
                                                                <div class="row">
                                                                    <div class="col-9">
                                                                        <div id="modal-border-right-width-range-slider-min" class="modal-border-right-width-range-slider-min" style="border: 0; color: #f6931f; font-weight: bold;"></div>
                                                                    </div>
                                                                    <div class="col-3">
                                                                        <input type="text" name="options_modal_nav_tabs_border_right_width" id="options_modal_nav_tabs_border_right_width" class="modal-border-right-width-range-slider-value range-slider-value form-control" />
                                                                    </div>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_text_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_text_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal content text color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal content text color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_text_color" id="options_modal_content_text_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal content text color" value="#686868">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#686868" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_text_font_size -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_text_font_size" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal content text font size</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal content text font size"></i>
                                                                </label>
                                                                <div class="row">
                                                                    <div class="col-9">
                                                                        <div id="modal-content-text-font-size-range-slider-min" class="modal-content-text-font-size-range-slider-min" style="border: 0; color: #f6931f; font-weight: bold;"></div>
                                                                    </div>
                                                                    <div class="col-3">
                                                                        <input type="text" name="options_modal_content_text_font_size" id="options_modal_content_text_font_size" class="modal-content-text-font-size-range-slider-value range-slider-value form-control" />
                                                                    </div>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_text_font_styles -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_text_font_styles" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal content text font styles</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal content text font styles"></i>
                                                                </label>
                                                                <div class="btn-group btn-group-font-style" role="group" aria-label="Font style checkbox toggle button group">
                                                                    <input type="checkbox" class="btn-check" id="options-modal-content-text-bold" autocomplete="off">
                                                                    <label class="btn btn-default" for="options-modal-content-text-bold"><strong>B</strong></label>

                                                                    <input type="checkbox" class="btn-check" id="options-modal-content-text-italic" autocomplete="off">
                                                                    <label class="btn btn-default" for="options-modal-content-text-italic"><em>I</em></label>

                                                                    <input type="checkbox" class="btn-check" id="options-modal-content-text-uppercase" autocomplete="off">
                                                                    <label class="btn btn-default" for="options-modal-content-text-uppercase" style="text-transform: uppercase;">TT</label>

                                                                    <input type="checkbox" class="btn-check" id="options-modal-content-text-underline" autocomplete="off">
                                                                    <label class="btn btn-default" for="options-modal-content-text-underline" style="text-decoration: underline;">U</label>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_close_btn_bg_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_close_btn_bg_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal close button background color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal close button background color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_close_btn_bg_color" id="options_modal_content_close_btn_bg_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal close button background color" value="#fff">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#fff" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_close_btn_active_bg_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_close_btn_active_bg_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal close button hover background color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal close button hover background color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_close_btn_active_bg_color" id="options_modal_content_close_btn_active_bg_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal close button hover background color" value="#bd362f">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#bd362f" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_close_btn_border_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_close_btn_border_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal close button border color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal close button border color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_close_btn_border_color" id="options_modal_content_close_btn_border_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal close button border color" value="#bd362f">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#bd362f" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_close_btn_text_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_close_btn_text_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal close button border color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal close button text color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_close_btn_text_color" id="options_modal_content_close_btn_text_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal close button text color" value="#bd362f">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#bd362f" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_close_btn_active_text_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_close_btn_active_text_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal close button hover text color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal close button hover text color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_close_btn_active_text_color" id="options_modal_content_close_btn_active_text_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal close hover text color" value="#fff">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#fff" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_save_btn_bg_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_save_btn_bg_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal save button background color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal save button background color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_save_btn_bg_color" id="options_modal_content_save_btn_bg_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal save button background color" value="#fff">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#fff" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_save_btn_active_bg_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_save_btn_active_bg_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal save button hover background color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal save button hover background color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_save_btn_active_bg_color" id="options_modal_content_save_btn_active_bg_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal save button hover background color" value="#72af46">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#72af46" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_save_btn_border_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_save_btn_border_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal save button border color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal save button border color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_save_btn_border_color" id="options_modal_content_save_btn_border_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal save button border color" value="#72af46">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#72af46" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_save_btn_text_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_save_btn_text_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal save button border color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal save button text color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_save_btn_text_color" id="options_modal_content_save_btn_text_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal save button text color" value="#fff">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#fff" />
                                                                    </span>
                                                                </div>
                                                            </div>

                                                            <!-- options_modal_content_save_btn_active_text_color -->
                                                            <div class="form-group">
                                                                <label for="options_modal_content_save_btn_active_text_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Modal save button hover text color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the modal save button hover text color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_modal_content_save_btn_active_text_color" id="options_modal_content_save_btn_active_text_color" class="form-control minicolor-hex" data-control="hue" placeholder="Modal save hover text color" value="#72af46">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#72af46" />
                                                                    </span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="accordion-item component-form-elements">
                                                    <h6 class="accordion-header">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#component-form-elements" aria-expanded="false" aria-controls="component-form-elements">
                                                            Form elements
                                                        </button>
                                                    </h6>
                                                    <div id="component-form-elements" class="accordion-collapse collapse" data-bs-parent="#components-accordion">
                                                        <div class="accordion-body">
                                                            <!-- options_form_bg_color -->
                                                            <div class="form-group">
                                                                <label for="options_form_bg_color" class="d-flex flex-row justify-content-between">
                                                                    <div class="label-text">Form background color</div> <i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="Change the form background color by typing the hexadecimal color code or by using the color picker"></i>
                                                                </label>
                                                                <div class="input-group platform-scheme osta_color_code">
                                                                    <input type="text" name="options_form_bg_color" id="options_form_bg_color" class="form-control minicolor-hex" data-control="hue" placeholder="Form background color" value="#fff">
                                                                    <span class="input-group-addon">
                                                                        <input type="hidden" class="minicolor" value="#fff" />
                                                                    </span>
                                                                </div>
                                                            </div>


                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end of #general-options -->
                            </div>
                            <?php
                            echo $this->form()->closeTag();
                            ?>

                        </div>
                    </div>
                    <button type="button" class="btn btn-primary mb-5 save-platform-theme-options">Save</button>
                </div>
            </div>
            <!-- end platfome-theme-options -->
        </div>
        <script type="text/javascript">
            (function($) {
                //$(".osta_color_code").colorpicker({format: 'hex',useAlpha: false});
                $(".minicolor").each(function() {
                    var $this = $(this);
                    $this.minicolors({
                        control: $this.attr("data-control") || 'hue',
                        defaultValue: $this.attr("data-defaultValue") || '',
                        format: $this.attr('data-format') || 'hex',
                        keywords: $this.attr('data-keywords') || '',
                        inline: $this.attr('data-inline') === 'true',
                        letterCase: $this.attr('data-letterCase') || 'lowercase',
                        opacity: $this.attr('data-opacity') || true,
                        position: $this.attr('data-position') || 'bottom right',
                        swatches: $this.attr('data-swatches') ? $this.attr('data-swatches').split('|') : [],
                        change: function(hex, opacity) {
                            var log;
                            try {
                                log = hex ? hex : 'transparent';

                                if (opacity)
                                    log += ', ' + opacity;

                                if ($this.closest(".osta_color_code").find(".minicolor-hex").length) {
                                    $this.closest(".osta_color_code").find(".minicolor-hex").val(hex);
                                }
                            } catch (e) {
                                console.error(e);
                            }
                        },
                        theme: 'default'
                    });
                });

                $(".platform-scheme .minicolor-hex").each(function(i, v) {
                    var $this = $(v);
                    $this.on("click", function() {
                        // .minicolors-focus, .minicolors-panel style="display: block;"
                        $this.parent(".input-group").find(".minicolors .minicolors-swatch").trigger("click");
                    });
                });

                $("input:file").filestyle({
                    buttonName: "btn-primary",
                    buttonText: '<?= $this->translate('tr_meliscore_platform_scheme_file_button'); ?>'
                });
                $("input#sidebar_header_logo:file").filestyle({
                    buttonName: "btn-primary",
                    input: false,
                    buttonText: '<?= $this->translate('tr_meliscore_platform_scheme_file_button'); ?>'
                });
            })(jQuery);
        </script>
    <?php
    } else {
        echo '<h4>' . $this->translate('tr_meliscore_tool_user_modal_empty') . '</h4>';
    }
    ?>
</div>