<?php 
    $id = '';
    $name = '';

    if (! empty($this->zoneconfig['conf']['id'])) {
        $id .= $this->zoneconfig['conf']['id'];
    }


    if (! empty($this->zoneconfig['conf']['name'])) {
        $name = $this->zoneconfig['conf']['name'];
    }
?>

<div>
    <div class="npdc-heading">
        <h5><?php echo $this->translate('tr_meliscore_tool_other_config_password_validity_header'); ?></h5>						
    </div>
    <?php
        echo $this->form()->openTag($this->passwordValidityForm);
        echo $this->melisFieldCollection($this->passwordValidityForm);
        echo $this->form()->closeTag();
    ?>
    <br>
</div>

<div>
    <div class="npdc-heading">
        <h5><?php echo $this->translate('tr_meliscore_tool_other_config_password_duplicate_header'); ?></h5>						
    </div>
    <?php
        echo $this->form()->openTag($this->passwordDuplicateForm);
        echo $this->melisFieldCollection($this->passwordDuplicateForm);
        echo $this->form()->closeTag();
    ?>
    <br>
</div>

<div>
    <div class="npdc-heading">
        <h5><?php echo $this->translate('tr_meliscore_tool_other_config_password_complexity_header'); ?></h5>						
    </div>
    <?php
        echo $this->form()->openTag($this->passwordComplexityForm);
        echo $this->melisFieldCollection($this->passwordComplexityForm);
        echo $this->form()->closeTag();
    ?>
    <br>
</div>

<script>
    $(document).ready(function() {
        $(document).on("keydown", "#password-validity-form", function(event) { 
            return event.key != "Enter";
        });
    });
</script>