<?php 
    $id = '';
    $name = '';

    if (! empty($this->zoneconfig['conf']['id'])) {
        $id .= $this->zoneconfig['conf']['id'];
    }


    if (! empty($this->zoneconfig['conf']['name'])) {
        $name = $this->zoneconfig['conf']['name'];
    }
?>

<div>
    <div class="npdc-heading">
        <h5><?php echo $this->translate('tr_meliscore_tool_other_config_password_validity_header'); ?></h5>						
    </div>
    <?php
        echo $this->form()->openTag($this->passwordValidityForm);
        echo $this->melisFieldCollection($this->passwordValidityForm);
        echo $this->form()->closeTag();
    ?>
    <br>
</div>

<div>
    <div class="npdc-heading">
        <h5><?php echo $this->translate('tr_meliscore_tool_other_config_password_duplicate_header'); ?></h5>						
    </div>
    <?php
        echo $this->form()->openTag($this->passwordDuplicateForm);
        echo $this->melisFieldCollection($this->passwordDuplicateForm);
        echo $this->form()->closeTag();
    ?>
    <br>
</div>

<div>
    <div class="npdc-heading">
        <h5><?php echo $this->translate('tr_meliscore_tool_other_config_password_complexity_header'); ?></h5>						
    </div>

    <?php echo $this->form()->openTag($this->passwordComplexityForm); ?>

    <?php foreach ($this->passwordComplexityForm->getElements() as $key => $value)  : ?>
        <?php if ($value->getAttribute('type') == 'text') : ?>
            <div class="form-group">
                <label for="<?php echo $value->getAttribute('id'); ?>"><?php echo $value->getLabel() ?></label><?php echo $this->formElement($value);?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>

    <div class="form-group">
        <div class="row">
            <?php foreach ($this->passwordComplexityForm->getElements() as $key => $value) : ?>
                <?php if ($value->getAttribute('type') == 'checkbox') : ?>
                <div class="col-md-3">
                    <div class="checkbox cb-cont">
                        <label>
                            <span class="cbmask-outer">
                                <span class="cbmask-inner <?php echo $value->getValue() ? 'cb-active': ''; ?>"></span>
                            </span>
                            <input type="checkbox" class="password-complexity" name="<?php echo $value->getName(); ?>" id="<?php echo $value->getName(); ?>" value="<?php echo (empty($value->getValue())) ? '0': '1'; ?>" <?php echo (empty($value->getValue())) ? '': 'checked'; ?>><?php echo $value->getLabel(); ?>
                        </label>
                    </div>
                </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>
    <br>
</div>

<script>
    $(document).ready(function() {
        $(document).on("keydown", "#password-validity-form", function(event) { 
            return event.key != "Enter";
        });

        $(document).on("keydown", "#password-duplicate-form", function(event) { 
            return event.key != "Enter";
        });

        $(document).on("keydown", "#password-complexity-form", function(event) { 
            return event.key != "Enter";
        });
    });
</script>