<?php 
    $id = '';
    $name = '';

    if (! empty($this->zoneconfig['conf']['id'])) {
        $id .= $this->zoneconfig['conf']['id'];
    }


    if (! empty($this->zoneconfig['conf']['name'])) {
        $name = $this->zoneconfig['conf']['name'];
    }
?>

<div class="npdc-heading">
    <h6><?php echo $this->translate('tr_meliscore_tool_other_config_content_tabs_core_subheader'); ?></h6>						
</div>

<!-- <h4 id="<?php echo $id; ?>" data-melisKey="<?php echo $this->melisKey; ?>" style="margin-bottom: inherit"><?php echo $name; ?></h4> -->

<?php
    echo $this->form()->openTag($this->form);
    echo $this->melisFieldCollection($this->form);
    echo $this->form()->closeTag();
?>

<script>
    $(document).ready(function() {
        $(document).on("keydown", "#password-settings-form", function(event) { 
            return event.key != "Enter";
        });
    });
</script>