<?php
    $id = '';
    $name = '';
    if (! empty($this->zoneconfig['conf']['id'])) {
        $id .= $this->zoneconfig['conf']['id'];
    }
    if (! empty($this->zoneconfig['conf']['name'])) {
        $name = $this->zoneconfig['conf']['name'];
    }
?>
<div>
    <div class="npdc-heading">
        <h5><?php echo $this->translate('tr_meliscore_tool_other_config_lock_failed_login_attempts'); ?></h5>						
    </div>
    <?php
        $form = $this->loginAccountLockForm;
        $form->prepare();
        echo $this->form()->openTag($form);
    ?>
    <?php foreach ($form->getElements() as $key => $value) : ?>
        <?php if ($value->getAttribute('name') == 'login_account_type_of_lock') : ?>
            <div class="form-group"> 
                <label class="d-flex flex-row justify-content-between" for = "<?php echo $key; ?>" >
                    <div class = "label-text"><?php echo $value->getLabel(); ?></div>
                    <div class = "slider-open-tooltip">
                        <i class="fa fa-info-circle fa-lg float-right tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?php echo (!empty($value->getOptions()['tooltip'])) ? $this->translate($value->getOptions()['tooltip']) : ""; ?>" data-html="true"></i>
                    </div>
                </label>
                <div class="row">
                    <?php foreach ($value->getValueOptions() as $optKey => $optVal) : ?>
                        <div id = "form-display-radio" class="col-md-2">
                            <label for = "<?php echo $optKey.str_replace(' ', '_', $optVal); ?>" class = "d-flex">
                                <input class = "<?php echo $value->getAttribute('class'); ?>" type="radio" value="<?php echo $optKey; ?>" name="<?php echo $key; ?>" id="<?php echo $optKey.str_replace(' ', '_', $optVal); ?>" <?php echo ($optKey == $value->getValue() || empty($value->getValue())) ? "checked" : ""; ?>/>                             
                                <span><?php echo $optVal; ?></span>
                            </label>             
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php elseif (in_array($value->getAttribute('name'), ['login_account_duration_days', 'login_account_duration_hours', 'login_account_duration_minutes'])) : ?>
            <?php if ($value->getAttribute('name') == 'login_account_duration_days') : ?>
                <div class="form-group"> 
                    <label class="d-flex flex-row justify-content-between" for = "" >
                        <div class = "label-text"><?php echo $this->translate('tr_meliscore_tool_other_config_duration_of_lock'); ?></div>
                        <div class = "slider-open-tooltip">
                            <i class="fa fa-info-circle fa-lg float-right tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="" data-bs-title="<?php echo $this->translate('tr_meliscore_tool_other_config_duration_of_lock_tooltip'); ?>" data-html="true"></i>
                        </div>
                    </label>
                </div>
                <div class="form-group">
                    <div class="row">
            <?php endif; ?>
                    <div class="col-sm-1">
                        <input name="<?php echo $value->getAttribute('name'); ?>" id="<?php echo $value->getAttribute('name'); ?>" class="form-control" type="text" value="<?php echo $value->getValue(); ?>">
                    </div>
                    <label for="<?php echo $value->getAttribute('name'); ?>" class="col-sm-1" style="padding-left: 5px; margin-top: 5px;"><?php echo $value->getLabel(); ?></label>
            <?php if ($value->getAttribute('name') == 'login_account_duration_minutes') : ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php else : ?>
            <?php echo $this->MelisFieldRow($value); ?>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php echo $this->form()->closeTag(); ?>
    <br>
</div>
<div>
    <div class="npdc-heading">
        <h5><?php echo $this->translate('tr_meliscore_tool_other_config_password_validity_header'); ?></h5>						
    </div>
    <?php
        echo $this->form()->openTag($this->passwordValidityForm);
        echo $this->melisFieldCollection($this->passwordValidityForm);
        echo $this->form()->closeTag();
    ?>
    <br>
</div>
<div>
    <div class="npdc-heading">
        <h5><?php echo $this->translate('tr_meliscore_tool_other_config_password_duplicate_header'); ?></h5>						
    </div>
    <?php
        echo $this->form()->openTag($this->passwordDuplicateForm);
        echo $this->melisFieldCollection($this->passwordDuplicateForm);
        echo $this->form()->closeTag();
    ?>
    <br>
</div>
<div>
    <div class="npdc-heading">
        <h5><?php echo $this->translate('tr_meliscore_tool_other_config_password_complexity_header'); ?></h5>						
    </div>
    <?php echo $this->form()->openTag($this->passwordComplexityForm); ?>
    <?php foreach ($this->passwordComplexityForm->getElements() as $key => $value)  : ?>
        <?php if ($value->getAttribute('type') == 'text') : ?>
            <div class="form-group">
                <label class="d-flex flex-row justify-content-between" for="<?php echo $value->getAttribute('id'); ?>">
                    <div class="label-text"><?php echo $value->getLabel() ?></div>
                    <div class="slider-open-tooltip"><i class="fa fa-info-circle fa-lg tip-info" data-bs-toggle="tooltip" data-bs-placement="left" title="<?php echo $this->translate('tr_meliscore_tool_other_config_password_complexity_number_of_characters_tooltip'); ?>" data-bs-title="<?php echo $this->translate('tr_meliscore_tool_other_config_password_complexity_number_of_characters_tooltip'); ?>"></i></div>
                </label>
                <?php echo $this->formElement($value);?>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
    <div class="form-group">
        <div class="row">
            <?php foreach ($this->passwordComplexityForm->getElements() as $key => $value) : ?>
                <?php if ($value->getAttribute('type') == 'checkbox') : ?>
                <div class="col-md-3">
                    <div class="checkbox cb-cont">
                        <label>
                            <span class="cbmask-outer">
                                <span class="cbmask-inner <?php echo $value->getValue() ? 'cb-active': ''; ?>"></span>
                            </span>
                            <input type="checkbox" class="password-complexity" name="<?php echo $value->getName(); ?>" id="<?php echo $value->getName(); ?>" value="<?php echo (empty($value->getValue())) ? '0': '1'; ?>" <?php echo (empty($value->getValue())) ? '': 'checked'; ?>><?php echo $value->getLabel(); ?>
                        </label>
                    </div>
                </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <br>
</div>
<script>
    $(document).ready(function() {
        $(document).on("keydown", "#login-lock-form", function(event) {
            return event.key != "Enter";
        });
        $(document).on("keydown", "#password-validity-form", function(event) {
            return event.key != "Enter";
        });
        $(document).on("keydown", "#password-duplicate-form", function(event) {
            return event.key != "Enter";
        });
        $(document).on("keydown", "#password-complexity-form", function(event) {
            return event.key != "Enter";
        });
    });
</script>