<?php
// 	$form = $this->meliscore_resetpass;
    $form = $this->formFactory->createForm($this->formConfig);
	$success = $this->success === 1 ? 'alert-success' : 'alert-danger';
	$form->prepare();

$schemes   = $this->layout()->schemes;
$loginLogo = $this->login_logo;

if($schemes) {
    if(!empty($schemes->getLoginBackground())) {
        $loginLogo = $schemes->getLoginLogo();
    }
}
?>
<div id="content loginContent">
 	<h4 class="innerAll margin-none border-bottom text-center"><i class="fa fa-pencil"></i> <?= $this->translate('tr_meliscore_forgot_page_header')?></h4>
    <div class="login spacing-x2">
     	<div class="placeholder main-login-page text-center">
         	<div class="business-logo-container">
     			<img class="melis-services-img" alt="melis technologies services" src="<?= $loginLogo ?>">
     		</div>
 		</div>
     	<div class="container">
             <div class="row">
                 <div class="col-sm-6 col-sm-offset-3">
                      <div class="panel panel-default">
                           <div class="panel-body innerAll">
								<div id="resetpassprompt"></div>
                    				<?php 
                    				if($this->hashExists) {
                    				    if(!empty($message)) {
                    				        echo '<div class="alert ' . $success . '">'. $this->message. '</div>';  
                    				    }
                    				    echo $this->form()->openTag($form);
                    				    echo $this->melisFieldCollection($form);
                    				    echo $this->form()->closeTag();
                    				}
                    				else {
                    				    echo '<div class="center">'.$this->translate('tr_meliscore_reset_password_failed').'</div>';
                    				    echo ' <a style="margin-top:10px;display:block;" href="/melis/login">'.$this->translate('tr_meliscore_back_to_login_page').'</a>';
                    				}
                    				?>
                                    
                                   
                           </div>
                      </div>
                 </div>
             </div>
     	</div>
    </div>
</div>