<?php
//     $form = $this->meliscore_forgot;
    $form = $this->formFactory->createForm($this->formConfig);
	$form->prepare();
?>

<div id="content loginContent">
 	<h4 class="innerAll margin-none border-bottom text-center"><i class="fa fa-pencil"></i> <?= $this->translate('tr_meliscore_forgot_page_header')?></h4>
    <div class="login spacing-x2">
     	<div class="placeholder main-login-page text-center">
         	<div class="business-logo-container">
     			<img class="melis-services-img" alt="melis technologies services" src="<?= $this->lost_password_logo ?>">
     		</div>
 		</div>
     	<div class="container">
             <div class="row">
                 <div class="col-sm-6 col-sm-offset-3">
                      <div class="panel panel-default">
                           <div class="panel-body innerAll">
								<div id="lostpassprompt"></div>
                                    <?= $this->form()->openTag($form); ?>
                                    <?= $this->melisFieldCollection($form); ?>
                                    <?= $this->form()->closeTag(); ?>
                                    
                                    
                                    <a style="margin-top:10px;display:block;" href="/melis/login"><?= $this->translate('tr_meliscore_back_to_login_page'); ?></a>
                    
                           </div>
                      </div>
                 </div>
             </div>
     	</div>
    </div>
</div>