<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
$data_melisKey = $this->melisKey;


?>
<div <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>'>
    <div class="widget widget-tabs widget-tabs-double-2 widget-tabs-responsive">
        <div class="widget-head nav">
            <ul class="tabs-label nav-tabs nav">
                <?php foreach($this->zoneconfig['interface'] AS $configKey => $configVal) { ?>
                    <?php if($configKey == "melismessenger_tool") { ?>
                        <?php if(trim($this->$configKey) != ""){ ?>
                            <li class="nav-item" role="presentation" id="melis-messenger-tab">
                                <a class="nav-link glyphicons <?= $configVal['conf']['icon'] ?> cs-fa" data-bs-toggle="tab" data-bs-target="#<?=$configVal['conf']['id']?>" href="#<?=$configVal['conf']['id']?>" aria-expanded="true">
                                    <i></i>
                                    <span><?=$this->translate($configVal['conf']['name']); ?></span>
                                </a>
                            </li>
                        <?php } ?>
                    <?php }else { ?>
                        <li class="nav-item" role="presentation">
                            <a class="nav-link glyphicons <?= $configVal['conf']['icon'] ?> cs-fa" data-bs-toggle="tab" data-bs-target="#<?=$configVal['conf']['id']?>" href="#<?=$configVal['conf']['id']?>" aria-expanded="true">
                                <i></i>
                                <span><?=$this->translate($configVal['conf']['name']); ?></span>
                            </a>
                        </li>
                    <?php } ?>
                <?php } ?>
            </ul>
        </div>
    </div>
    <div class="user-profile-tab-content">
        <div class="tab-content">
     		<?php foreach($this->zoneconfig['interface'] AS $configKey => $configVal) { ?>
             	<?php echo $this->$configKey ?>
     		<?php } ?>
       	</div>
    </div>
</div>
