<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
$data_melisKey = $this->melisKey;


?>
<div<?= $id; ?>  class="tab-pane container-level-a" data-melisKey='<?= $data_melisKey; ?>'>
    <div class="innerAll spacing-x2">

        <!-- Widget -->
        <div class="widget finances_summary widget-inverse">

            <div class="row row-merge">
                <!-- col -->
                <div class="col-sm-12 col-md-3">
                    <!-- Profile Photo -->
                    <div class="text-center">
                        <div class="profile-photo">
                            <img src="/MelisCore/images/profile/22.jpg" alt="" class="img-responsive img-circle" id="meliscore_left_menu_profile_pic">
                            <div class="photo-overlay"></div>
                            <div class="profile-photo-edit">
                                <i class="fa fa-camera"></i>
                            </div>
                        </div>
                        <p class="u-name lead strong margin-none">Bill Jonson</p>
                        <p class="u-username">billjonson</p>
                    </div>
                    <div class="innerAll inner-2x text-center">
                        <!-- <p class="lead">Senior UI Designer</p> -->
                        <span class="u-lists"><i class="fa fa-user"></i>billjonson</span>
                        <span class="u-lists"><i class="fa fa-envelope"></i>email@gmail.com</span>
                    </div>


                </div>
                <!-- // END col -->


                <!-- col -->
                <div class="col-lg-9 col-md-9 col-sm-12">
                    <div class="">
                        <!-- Nav tabs -->
                        <ul class="cs-nav-tabs nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><i class="fa fa-user"></i>Profile</a></li>
                            <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab"><i class="fa fa-comments"></i>Messages</a></li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane" id="profile">
                                <div class="tab-panel-save">
                                    <a data-toggle="modal" id="id_meliscms_tool_site_header_add" href="#modal-cms-tool-site" class="btn btn-success" data-meliskey=""><i class="fa fa-plus"></i> Save</a>
                                </div>
                                <!-- <div class="tab-content-title">Profile</div> -->
                                <form action="" class="form-custom-block">
                                    <!-- Row -->
                                    <div class="row">

                                        <!-- Group -->
                                        <div class="col-md-12">
                                            <div class="form-group clearfix">
                                                <div class="col-md-12"><label class="control-label" for="firstname">First name</label></div>
                                                <div class="col-md-12">
                                                    <input class="form-control" id="firstname" name="firstname" type="text" placeholder="Bill">
                                                </div>
                                            </div>
                                        </div>

                                        <!-- Group -->
                                        <div class="col-md-12">
                                            <div class="form-group clearfix">
                                                <div class="col-md-12"><label class="control-label" for="lastname">Last name</label></div>
                                                <div class="col-md-12">
                                                    <input class="form-control" id="lastname" name="lastname" type="text" placeholder="Jonson">
                                                </div>
                                            </div>
                                        </div>


                                        <!-- Group -->
                                        <div class="col-md-12">
                                            <div class="form-group clearfix">
                                                <div class="col-md-12"><label class="control-label" for="username">Username</label></div>
                                                <div class="col-md-12">
                                                    <input class="form-control" id="username" name="username" type="text" placeholder="billjonson">
                                                </div>
                                            </div>
                                        </div>

                                        <!-- Group -->
                                        <div class="col-md-12">
                                            <div class="form-group clearfix">
                                                <div class="col-md-12"><label class="control-label" for="password">Password</label></div>
                                                <div class="col-md-12">
                                                    <input class="form-control" id="password" name="password" type="password">
                                                </div>
                                            </div>
                                        </div>

                                        <!-- Group -->
                                        <div class="col-md-12">
                                            <div class="form-group clearfix">
                                                <div class="col-md-12"><label class="control-label" for="confirm_password">Confirm Password</label></div>
                                                <div class="col-md-12">
                                                    <input class="form-control" id="confirm_password" name="confirm_password" type="password">
                                                </div>
                                            </div>
                                        </div>

                                        <!-- Group -->
                                        <div class="col-md-12">
                                            <div class="form-group clearfix">
                                                <div class="col-md-12"><label class="control-label" for="email">Email</label></div>
                                                <div class="col-md-12">
                                                    <input class="form-control" id="email" name="email" type="email"  placeholder="billjonson@gmail.com">
                                                </div>
                                            </div>
                                        </div>
                                        <!-- // Group END -->

                                        <!-- Group -->
                                        <div class="col-md-12">
                                            <div class="form-group clearfix">
                                                <div class="col-md-12"><label class="control-label" for="email">Language</label></div>
                                                <div class="col-md-12">
                                                    <select name="usr_lang_id" id="id_usr_lang_id" class="form-control">
                                                        <option value>Choose</option>
                                                        <option value="1">English</option>
                                                        <option value="2">Français</option>
                                                    </select>
                                                    <!-- <input class="form-control" id="email" name="email" type="email"  placeholder="billjonson@gmail.com"> -->
                                                </div>
                                            </div>
                                        </div>
                                        <!-- // Group END -->

                                    </div>
                                    <!-- // Row END -->
                                </form>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="messages">
                                <div class="tab-panel-save">
                                    <a data-toggle="modal" id="id_meliscms_tool_site_header_add" href="#modal-cms-tool-site" class="btn btn-success" data-meliskey=""><i class="fa fa-plus"></i> Save</a>
                                </div>
                                <!-- <div class="tab-content-title">Messages</div> -->
                                <div class="innerAll half heading-buttons border-bottom">
                                    <h4 class="margin-none pull-left">Work History  </h4>

                                    <div class="clearfix"></div>
                                </div>

                                <ul class="timeline-activity list-unstyled">
                                    <li class="active">
                                        <i class="list-icon fa fa-share"></i>
                                        <div class="block block-inline">
                                            <div class="caret"></div>
                                            <div class="box-generic">
                                                <div class="timeline-top-info content-filled border-bottom">
                                                    <i class="fa fa-user"></i> <a href="">Bill</a> got a review for <a href="" class="text-primary">FLAT PLUS UI Interface Design</a> from
                                                    <a href="#"><img src="MelisDesign/images/people/80/8.jpg" alt="photo" width="20">
                                                    </a> <a href="">Andrew M.</a>
                                                    <div class="timeline-bottom">
                                                        <i class="fa fa-clock-o"></i> 2 days ago

                                                    </div>
                                                </div>
                                                <div class="media innerAll margin-none">
                                                    <a class="pull-left" href="#"><img src="MelisDesign/images/people/80/8.jpg" alt="photo" class="media-object" width="35">
                                                    </a>
                                                    <div class="media-body">
                                                        <a href="" class="strong">Andrew</a> Good Job. Congrats and hope to see more admin templates like this in the future.
                                                        <div class="timeline-bottom">
                                                            <i class="fa fa-clock-o"></i> 2 days ago
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>

                                        </div>
                                    </li>

                                    <li>
                                        <i class="list-icon fa fa-share"></i>
                                        <div class="block block-inline">
                                            <div class="caret"></div>
                                            <div class="box-generic">
                                                <div class="timeline-top-info content-filled border-bottom">
                                                    <i class="fa fa-user"></i> <a href="">Bill</a> got a review for <a href="" class="text-primary">Support &amp; Ticket System</a> from
                                                    <a href="#"><img src="MelisDesign/images/people/80/20.jpg" alt="photo" width="20">
                                                    </a> <a href="">Andrew M.</a>
                                                    <div class="timeline-bottom">
                                                        <i class="fa fa-clock-o"></i> 2 days ago

                                                    </div>
                                                </div>
                                                <div class="media innerAll margin-none">
                                                    <a class="pull-left" href="#"><img src="MelisDesign/images/people/80/20.jpg" alt="photo" class="media-object" width="35">
                                                    </a>
                                                    <div class="media-body">
                                                        <a href="" class="strong">Bogdan</a> Good Job. Congrats and hope to see more admin templates like this in the future.
                                                        <div class="timeline-bottom">
                                                            <i class="fa fa-clock-o"></i> 2 days ago
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>

                                        </div>
                                    </li>

                                    <li>
                                        <i class="list-icon fa fa-share"></i>
                                        <div class="block block-inline">
                                            <div class="caret"></div>
                                            <div class="box-generic">
                                                <div class="timeline-top-info content-filled border-bottom">
                                                    <i class="fa fa-user"></i> <a href="">Bill</a> got a review for <a href="" class="text-primary">Project Management</a> from
                                                    <a href="#"><img src="MelisDesign/images/people/80/12.jpg" alt="photo" width="20">
                                                    </a> <a href="">Andrew M.</a>
                                                    <div class="timeline-bottom">
                                                        <i class="fa fa-clock-o"></i> 2 days ago

                                                    </div>
                                                </div>
                                                <div class="media innerAll margin-none">
                                                    <a class="pull-left" href="#"><img src="MelisDesign/images/people/80/12.jpg" alt="photo" class="media-object" width="35">
                                                    </a>
                                                    <div class="media-body">
                                                        <a href="" class="strong">John </a> Good Job. Congrats and hope to see more admin templates like this in the future.
                                                        <div class="timeline-bottom">
                                                            <i class="fa fa-clock-o"></i> 2 days ago
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>

                                        </div>
                                    </li>

                                    <li>
                                        <i class="list-icon fa fa-share"></i>
                                        <div class="block block-inline">
                                            <div class="caret"></div>
                                            <div class="box-generic">
                                                <div class="timeline-top-info content-filled border-bottom">
                                                    <i class="fa fa-user"></i> <a href="">Bill</a> got a review for <a href="" class="text-primary">FLAT PLUS UI Interface Design</a> from
                                                    <a href="#"><img src="MelisDesign/images/people/80/10.jpg" alt="photo" width="20">
                                                    </a> <a href="">Andrew M.</a>
                                                    <div class="timeline-bottom">
                                                        <i class="fa fa-clock-o"></i> 2 days ago

                                                    </div>
                                                </div>
                                                <div class="media innerAll margin-none">
                                                    <a class="pull-left" href="#"><img src="MelisDesign/images/people/80/10.jpg" alt="photo" class="media-object" width="35">
                                                    </a>
                                                    <div class="media-body">
                                                        <a href="" class="strong">Andrew</a> Good Job. Congrats and hope to see more admin templates like this in the future.
                                                        <div class="timeline-bottom">
                                                            <i class="fa fa-clock-o"></i> 2 days ago
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>

                                        </div>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- // END col -->

            </div>

        </div>
        <!-- // END row -->
    </div>
    <!-- // END row-app -->

    <div class="clearfix"></div>
    <!-- // Sidebar menu & content wrapper END -->
</div>
