<div id="newformalert"></div>
<p class="modal-text-info"><?= $this->translate('tr_meliscore_tool_user_modal_description')?></p>
<?php 
    $form = $this->meliscore_tool_user_form_new;
    echo $this->form()->openTag($form);
    echo $this->melisFieldCollection($form);
?>
<br/>
<br/>
<div class="userimage">
    <span class="thumbnail">
      <img id="new-profile-image" width="64" height="64" src="/MelisCore/images/profile/default_picture.jpg" alt="<?= $this->translate('tr_meliscore_tool_user_usr_profile_image'); ?>">
    </span>
</div>
<div class="col-sm-12">
    <a href="#" class="small"  id="btnDelImg">
        <i class="fa fa-times"></i> <?= $this->translate('tr_meliscore_tool_user_col_remove_picture'); ?>
    </a>
</div>
<br/>
<br/>
<button type="submit" class="btn btn-success float-right" id="btnAdd"><i class="fa fa-plus"></i>
    <span class="long-text d-none d-sm-none"><?= $this->translate('tr_meliscore_tool_user_new_btn'); ?></span>
    <span class="short-text d-inline d-sm-inline"><?= $this->translate('tr_meliscore_tool_user_new_btn_short'); ?></span>
</button>
<?php
    echo $this->melisModalInvoker()->render(
        array(
            'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscore_common_close'),
            'class' => 'btn btn-danger float-left'
        ), 'dismiss');
    echo $this->form()->closeTag();
?>