<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
$data_melisKey = $this->melisKey;

?>

<div <?= $id; ?> data-melisKey="<?= $data_melisKey; ?>">
    <div class="spacing-x2 innerAll">
        <?php
        $this->melisGenericTable()->setTable(array(
            'id' => 'tableUserViewDateConnection',
            'class' => 'table table-striped table-primary responsive dt-responsive nowrap',
            'cellspacing' => '0',
            'width' => '100%'
        ));

        $columns = array();
        $columnStyle = array();

        foreach($this->tableColumns as $columnText)
        {
            $columns[] = $columnText['text'];
        }

        // set table columns
        $this->MelisGenericTable()->setColumns($columns);

        echo $this->melisGenericTable()->renderTable();

        ?>
    </div>
</div>