<div id="newformalert"></div>
<p class="modal-text-info"><?= $this->translate('tr_meliscore_tool_user_modal_description')?></p>
<?php 
    $form = $this->meliscore_tool_user_form_new;
    echo $this->form()->openTag($form);
    echo $this->melisFieldCollection($form);
?>
<div class="center-block userimage">
    <span class="thumbnail">
      <img id="new-profile-image" width="64" height="64" src="/MelisCore/images/profile/default_picture.jpg" alt="<?= $this->translate('tr_meliscore_tool_user_usr_profile_image'); ?>">
    </span>
</div>
<script type="text/javascript">
	$('.userimage').detach().insertAfter('fieldset#idnewusermanagement div:last');
</script>
<button type="submit" class="btn btn-success pull-right" id="btnAdd"><i class="fa fa-plus"></i>
    <span class="long-text hidden-xs hidden-sm"><?= $this->translate('tr_meliscore_tool_user_new_btn'); ?></span>
    <span class="short-text visible-xs visible-sm"><?= $this->translate('tr_meliscore_tool_user_new_btn_short'); ?></span>
</button>


<?php
    echo $this->melisModalInvoker()->render(
        array(
            'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscore_common_close'),
            'class' => 'btn btn-danger pull-left'
        ), 'dismiss');
    echo $this->form()->closeTag();
?>