<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="'. $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;

?>

<div class="me-heading bg-white border-bottom" <?= $id; ?> data-melisKey='<?= $data_melisKey; ?>'>
	<div class="row">
		<div class="me-hl col-12 col-md-9">
			<h1 class="content-heading"><?= $this->title; ?></h1>
			<p><?= $this->translate('tr_meliscore_tool_user_description'); ?></p>
		</div>
  		<div class="me-hr col-12 col-md-3">
			<?php 
			if(!empty($this->zoneconfig['interface'])) {
			    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
			        echo $this->$keyConfig;
			    }
			}
			?>
  		</div>	
	</div>
</div> 