<?php 
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;

?>

<div <?= $id; ?> data-melisKey="<?= $data_melisKey; ?>">
	<div class="spacing-x2 innerAll">
		<?php 
		$this->melisGenericTable()->setTable(array(
		    'id' => 'tableToolUserManagement',
		    'class' => 'table table-striped table-primary dt-responsive nowrap',
		    'cellspacing' => '0',
		    'width' => '100%'
		));
		
		$columns = array();
		$columnStyle = array();
		
		foreach($this->tableColumns as $columnText)
		{
		    $columns[] = $columnText['text'];
		}

		// set table columns
		$this->MelisGenericTable()->setColumns($columns);

		echo $this->melisGenericTable()->renderTable();
		
		?>

		<script type="text/javascript">
		// render table to DataTable plugin
		$(document).ready(function() {

			<?= $this->getToolDataTableConfig; ?>
			<?= $this->getToolDataTableConfigForDateConnection; ?>

			// Initialize the rights treeviews --------------------------------------->
			initRightsTree("#rights-fancytree", '/melis/MelisCore/ToolUser/getRightsTreeView');
			initRightsTree("#new-rights-fancytree", '/melis/MelisCore/ToolUser/getRightsTreeView');

		    $("#idusermanagement").on('submit', (function(e) {
		    	toolUserManagement.updateUser(this);
		    	e.preventDefault();
		    }));
		    
		    $("#idnewusermanagement ").on('submit', (function(e) {
		    	toolUserManagement.addNewUser(this);
				e.preventDefault();
		    }));

		    $("#btnEditRights").on('click', function() {
		    	$("#idusermanagement").submit();
		    	return false;
		    });

		    $("#btnAddRights").on('click', function() {
		    	$("#idnewusermanagement").submit();
		    	return false;
		    });
			//melisTool.buttons.refresh("#idToolUserContentRefresh .btnRefresh", toolUserManagement.refreshTable());
		    $("#idusermanagement input:file, #idnewusermanagement input:file").filestyle({buttonBefore: true, input: false, buttonText: '<?= $this->translate('tr_meliscore_tool_user_usr_file_button'); ?>'});

			// if initRetrieveUser fails, then re-execute this one
			$.ajax({
		        type        : 'GET', 
		        url         : '/melis/MelisCore/MelisAuth/getCurrentLoggedInUser',
		        dataType    : 'json',
		        encode		: true,
		     }).success(function(s){
		    	 var btnDelete = $('#tableToolUserManagement td:nth-child(4):contains("'+ s.login +'")').siblings(':last').find(".btnUserDelete");
		    	 btnDelete.hide();
		     });
            $($.fn.dataTable.tables(true)).DataTable().responsive.recalc();
            $("body").on("click", "a[href='#id_meliscore_tool_user_view_date_connection_modal']", function() {
                $("body").find("#id_meliscore_tool_user_view_date_connection_modal").css("opacity", "0");
                setTimeout(function() {
                    $($.fn.dataTable.tables(true)).DataTable().responsive.recalc();
                    $("body").find("#id_meliscore_tool_user_view_date_connection_modal").animate({
                        opacity: 1,
                    }, 350)
                }, 100);
                $($.fn.dataTable.tables(true)).DataTable().responsive.recalc();
            });
		});
		</script>

		
		
		
	</div>
</div>