<p class="modal-text-info"><?= $this->translate('tr_meliscore_tool_user_rights_description') ?></p>
<div id="rights-fancytree">

</div>

<?php 
echo $this->melisModalInvoker()->render(
    array(
        'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscore_common_close'),
        'class' => 'btn btn-danger float-left'
    ), 'dismiss');
?>

<button type="button" class="btn btn-success float-right" id="btnEditRights"><i class="fa fa-save"></i>  <?= $this->translate('tr_meliscore_tool_user_update'); ?></button>