<p class="modal-text-info"><?= $this->translate('tr_meliscore_tool_user_rights_description') ?></p>
<div id="new-rights-fancytree">

</div>

<?php 
echo $this->melisModalInvoker()->render(
    array(
        'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscore_common_close'),
        'class' => 'btn btn-danger float-left rightsBtn'
    ), 'dismiss');
?>
<div class="float-right">
    <button type="button" class="btn btn-success rightsBtn d-none d-sm-block float-right " id="btnAddRights"><i class="fa fa-plus"></i>  <?= $this->translate('tr_meliscore_tool_user_new_btn'); ?></button>
    <button type="button" class="btn btn-success rightsBtn show-xs d-md-none d-block float-right " id="btnAddRights"><i class="fa fa-plus"></i>  <?= $this->translate('tr_meliscore_tool_user_new_btn_short'); ?></button>
    <button type="button" class="btn btn-success rightsBtn float-right d-none d-sm-block" id="btnResetRightsNew"><i class="fa fa-fw icon-refresh-2"></i>  <?= $this->translate('tr_meliscore_tool_user_reset_rights'); ?></button>
    <button type="button" class="btn btn-success rightsBtn float-right show-xs d-md-none d-block" id="btnResetRightsNew"><i class="fa fa-fw icon-refresh-2"></i>  <?= $this->translate('tr_meliscore_tool_user_reset_rights_xs'); ?></button>
</div>
