<p class="modal-text-info"><?= $this->translate('tr_meliscore_tool_user_rights_description') ?></p>
<div id="rights-fancytree">

</div>

<?php 
echo $this->melisModalInvoker()->render(
    array(
        'text' => '<i class="fa fa-times"></i> '.$this->translate('tr_meliscore_common_close'),
        'class' => 'btn btn-danger pull-left rightsBtn'
    ), 'dismiss');
?>

<button type="button" class="btn btn-success rightsBtn pull-right" id="btnEditRights"><i class="fa fa-save"></i>  <?= $this->translate('tr_meliscore_tool_user_update'); ?></button>
<button type="button" class="btn btn-success rightsBtn pull-right hidden-xs" id="btnResetRights"><i class="fa fa-fw icon-refresh-2"></i>  <?= $this->translate('tr_meliscore_tool_user_reset_rights'); ?></button>
<button type="button" class="btn btn-success rightsBtn pull-right show-xs hidden-sm hidden-md hidden-lg" id="btnResetRights"><i class="fa fa-fw icon-refresh-2"></i>  <?= $this->translate('tr_meliscore_tool_user_reset_rights_xs'); ?></button>