<?php

	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
?>


<div data-melisKey='<?= $data_melisKey; ?>'<?= $id; ?> class="tab-pane container-level-a">
	<div class="tab-pane page-loaded include-content-xhr full-width active innerAll spacing-x2" id="id-maintabs-home" style="background: #981a1f21;">
	    <div class="row">
	    	<h1>Dashboard 2</h1>
	    	<p>View : view/melis-core/dashboard/dashboard2.phtml</p>
	    </div>
    </div>
</div>