<?php

	$name = '';
	$id = '';
	if (!empty($this->zoneconfig['conf']['name']))
		$name = $this->zoneconfig['conf']['name'];
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
		
?>
<li class="melis-opentools" data-tool-icon="fa-tachometers" data-tool-name="Dashboard 2" data-tool-id="id_meliscore_leftmenu_dashboard_content_2" data-tool-meliskey="meliscore_leftmenu_dashboard_content_2">
	<a>
		<i class="fa fa-tachometer">
		</i><span><?= $this->translate('Dashboard 2'); ?></span>
	</a>
</li>