<?php

	$name = '';
	$id = '';
	if (!empty($this->zoneconfig['conf']['name']))
		$name = $this->zoneconfig['conf']['name'];
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' . $this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
		
?>
<li<?= $id; ?> data-melisKey='<?= $data_melisKey; ?>' class="melis-opendashboard">
	<a>
		<i class="fa fa-tachometer meliscore-dashboard-icon">
		</i><span><?= $this->translate('tr_meliscore_dashboard'); ?></span>
	</a>
</li>