<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Melis Technology:Warning</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body class="full-padding" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%; background: #e6e3e6;">
    <div class="wrapper" style="min-width: 320px;padding-bottom: 50px;" lang="x-wrapper">
        <div class="header" style="padding-top: 20px; margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 173000px);" id="emb-email-header-container">
            <div class="logo emb-logo-margin-box" style="font-size: 26px;line-height: 32px;margin-top: 10px;margin-bottom: 20px;color: #c3ced9;font-family: Roboto,Tahoma,sans-serif;margin-left: 20px;margin-right: 20px;" align="center">
                <div class="logo-left" style="font-size:0px !important;line-height:0 !important;" align="left" id="emb-email-header">
                    <img style="height: auto;width: 100%;border: 0;max-width: 200px;" src="/img/MelisTech.png" alt="Melis Technology" width="243"/>
                </div>
            </div>
        </div>
        <div class="layout one-col fixed-width" style="margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 173000px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;">
            <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;background-color: #ffffff;">
                <div class="column" style='text-align: left;color: #60666d;font-size: 14px;line-height: 21px;font-family: "Open Sans",sans-serif;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);'>
                    <div style="margin-left: 20px;margin-right: 20px;margin-bottom: 24px;">
                        <p class="size-14" style="margin-top: 16px;margin-bottom: 0;font-size: 14px;line-height: 21px;" lang="x-size-14"><h3><?php echo $this->filePersmissionTitle?></h3></p>
                        <p class="size-14" style="margin-top: 16px;margin-bottom: 0;font-size: 14px;line-height: 21px;" lang="x-size-14"><?php echo $this->content; ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
