<?php 
    $id = '';

    if (! empty($this->zoneconfig['conf']['id'])){
        $id .= $this->zoneconfig['conf']['id'];
    }
?>
<div class="tab-pane " id="<?php echo $id?>" data-melisKey="<?= $this->melisKey;?>">				
	<?php
    	if(! empty($this->zoneconfig['interface'])) {
    	    foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
    	        echo $this->$keyConfig;
    	    }
    	}
    ?>	
</div>