<?php
    $id = '';

    if (!empty($this->zoneconfig['conf']['id']))
        $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';

    $data_melisKey = $this->melisKey;
?>
<div <?php echo $id; ?>  class="tab-pane container-level-a" data-melisKey='<?php echo $data_melisKey; ?>'>
    <?php
    if(empty($this->noAccess))
    {
        if(!empty($this->zoneconfig['interface'])) {
            foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
    }
    else
    {
        echo '<h4>'.$this->noAccess.'</h4>';
    }

    ?>
</div>
