<?php echo $this->doctype(); ?>
<html>
	<head>
        <meta charset="utf-8">
		<?= $this->headTitle('MELIS Platform V2.0 : Error'); ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
	</head>
	<body>
		<img src="/MelisCore/images/dashboard/melis-logo.png" />
		<?= $this->content; ?>
	</body>
</html>