<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	</head>
  	<body class="full-padding" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;">
    	<div class="wrapper" style="min-width: 320px;background-color: #e6e3e6;" lang="x-wrapper">
          <div class="header" style="padding-top: 20px; margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 173000px);" id="emb-email-header-container">
            <div class="logo emb-logo-margin-box" style="font-size: 26px;line-height: 32px;margin-top: 10px;margin-bottom: 20px;color: #c3ced9;font-family: Roboto,Tahoma,sans-serif;margin-left: 20px;margin-right: 20px;" align="center">
              	<div class="logo-left" style="font-size:0px !important;line-height:0 !important;" align="left" id="emb-email-header">
              		<a style="text-decoration: none;transition: opacity 0.1s ease-in;color: #c3ced9;" href="<?php echo $this->headerLogoLink; ?>">
              			<img style="height: auto;width: 100%;border: 0;max-width: 243px;" src="<?php echo $this->headerLogo; ?>" alt="Melis Technology" width="243"/>
          			</a>
          		</div>
            </div>
          </div>
          	<div class="layout one-col fixed-width" style="margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 173000px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;">
            	<div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;background-color: #ffffff;">
                  	<div class="column" style='text-align: left;color: #60666d;font-size: 14px;line-height: 21px;font-family: "Open Sans",sans-serif;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);'>
                    	<div style="margin-left: 20px;margin-right: 20px;margin-bottom: 24px;">
                          	<p class="size-14" style="margin-top: 16px;margin-bottom: 0;font-size: 14px;line-height: 21px;" lang="x-size-14"><?php echo $this->content; ?></p>
                    		<p class="size-14" style="margin-top: 20px;margin-bottom: 0;font-size: 14px;line-height: 21px;" lang="x-size-14"><?php echo $this->fromName; ?></p>
            			</div>
                  	</div>
            	</div>
          	</div>
          	<div class="layout email-footer" style="margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 173000px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;">
                <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;">
                  	<div class="column wide" style='text-align: left;font-size: 12px;line-height: 19px;color: #363636;font-family: "Open Sans",sans-serif;Float: left;max-width: 400px;min-width: 320px; width: 320px;width: calc(8000% - 47600px);'>
                        <div style="margin-left: 20px;margin-right: 20px;margin-top: 10px;margin-bottom: 10px;">
                          	<div>
                            <div>
                                Melis Technology<br/>
                                Address:&nbsp;4 rue du Dahomey, 75011 Paris France<br/>
                                Phone:&nbsp;(+33) 972 386 280<br/>
                                Email:&nbsp;contact@melistechnology.com
                        	</div>
                          	</div>
                        </div>
                  	</div>
                  	<div class="column narrow" style='text-align: left;font-size: 12px;line-height: 19px;color: #b9b9b9;font-family: "Open Sans",sans-serif;Float: left;max-width: 320px;min-width: 200px; width: 320px;width: calc(72200px - 12000%);'>
                    	<div style="margin-left: 20px;margin-right: 20px;margin-top: 10px;margin-bottom: 10px;"></div>
                  	</div>
                </div>
          	</div>
     	</div>
    </body>
</html>
