
<?php  
$loginClas       = (int) $this->isLogin == 1 ? 'login-page' : '';
$schemes         = $this->layout()->schemes;
$loginBackground = $this->login_background;
$favicon         = '/favicon.ico';

if($schemes) {
    if(!empty($schemes->getLoginBackground())) {
        $loginBackground = $schemes->getLoginBackground();
    }

    if(!empty($schemes->getFavicon())) {
        $favicon = $schemes->getFavicon();
    }
}

?>
<?php echo $this->doctype(); ?>
<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9"> <![endif]-->
<!--[if gt IE 8]> <html> <![endif]-->
<!--[if !IE]><!-->
<html <?= $loginClas ? 'style="height: calc(100vh + 60px);"' : null; ?>>
<!-- <![endif]-->
	<head>
        <meta charset="utf-8">
		<?= $this->headTitle('Melis Platform'); ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <link rel="icon" href="<?= $favicon; ?>" type="image/x-icon" />
        <link rel="shortcut icon" href="<?= $favicon; ?>" type="image/x-icon" />
        <script type="text/javascript">
       		var ua = window.navigator.userAgent;
        	var msie = ua.indexOf("MSIE ");
        	if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) {// If Internet Explorer set timeoutHandle
        		// self executing function
        		(function() {
				  	if( window.localStorage ) {
					    if (!localStorage.getItem('firstLoad')) {
					     	localStorage['firstLoad'] = true;
					     	window.location.reload();
					    } else {
					      localStorage.removeItem('firstLoad');
					    }
				  	}
				})();
 			}
		</script>
        <!--[if lt IE 9]>
		<link rel="stylesheet" href="../assets/components/library/bootstrap/css/bootstrap.min.css"/><![endif]-->
		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"> -->
		        
		<!-- fonts -->  
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
        <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700" rel="stylesheet">
		      
        <?php 
            if (!$this->isLogin && !$this->isMelisInstallerRoute)
                $pluginsFiles = $this->MelisCoreHeadPlugin();
            else    
                $pluginsFiles = $this->MelisCoreHeadPlugin('/meliscore_login');
        	
        	foreach ($pluginsFiles['css'] as $cssFile) {
        	    if(strpos($cssFile, 'MelisInstaller') === false) {
        	        $this->headLink()->appendStylesheet($this->basePath($cssFile));
        	    }
        	}
        		
        	echo $this->headLink();
		?>
<!--        <link href="/MelisCore/melis/platform-color-schemes.css" media="screen" rel="stylesheet" type="text/css">-->
        <link href="/melis/platform-color-schemes.css" media="screen" rel="stylesheet" type="text/css">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script><![endif]-->
		<script>
		 var basePath = '',
		 commonPath = '../assets/',
		 rootPath = '../',
		 DEV = false,
		 componentsPath = '../assets/components/';
		
		 var primaryColor = '#cb4040',
		 dangerColor = '#b55151',
		 infoColor = '#466baf',
		 successColor = '#8baf46',
		 warningColor = '#ab7a4b',
		 inverseColor = '#45484d';
		
		 var themerPrimaryColor = primaryColor;

		 
		</script>
		
		<?php
//         	$this->headScript()->prependFile($this->basePath('jquery-1.11.3.js'));
        	foreach ($pluginsFiles['js'] as $jsFile) {
        	    if(strpos($jsFile, 'MelisInstaller') === false) {
        	        $this->headScript()->appendFile($this->basePath($jsFile));
        	    }
        	}
        		
        ?>
        
         <!-- Login page backgroun <style> -->
	     <?php 
	     	echo '
                 <style>
    
    	     	 body.login-page{
    	     	    background: url(' . $loginBackground . ') fixed no-repeat;
    	     	    background-size: cover;
    	     	    height: 100%;
    	     	 }
    
                 </style>' ;
	     ?>
        
	</head>
	<body class="show-breadcrumb show-nav-tabs hide-levelB <?= $loginClas; ?>" <?= $loginClas ? 'style="height: calc(100vh + 60px);"' : null?>>
		
		<?= $this->content; ?>

		<!-- modals container -->
		<div id="melis-modals-container"></div>

        <!--dashboard menu plugins -->
        <div class="melis-core-dashboard-dnd-box">
            <div class="melis-core-dashboard-dnd-fix-menu">
                <div class="melis-core-dashboard-dnd-title">Plugins</div>
                <div class="melis-core-dashboard-plugin-filter-box">
                    <div class="melis-core-dashboard-ps-box">
                        <span class="melis-core-dashboard-filter-btn">Melis Cms <i class="fa fa-angle-down"></i></span>
                        <div class="melis-core-dashboard-plugin-snippets-box">

                            <div class="melis-core-dashboard-category-box">
                                <span class="melis-core-dashboard-category-btn">Tags <i class="fa fa-angle-down"></i></span>
                                <div class="melis-core-dashboard-category-plugins-box">
                                    <div class="melis-core-dashboard-plugin-snippets" data-module-name="melisfront" data-plugin-name="MelisFrontTagHtmlPlugin" data-plugin-site-module="MelisDemoCms" title="The HTML tag plugin provides a wysiwig editable zone for your templates. It comes preconfigured with a wysiwig editor and rich text oriented configuration.">
                                        <img src="/MelisFront/plugins/images/MelisFrontTagHtmlPlugin_thumb.jpg" alt="">
                                        <span class="melis-core-dashboard-plugin-title">Html tag</span>
                                    </div>
                                    <div class="melis-core-dashboard-plugin-snippets" data-module-name="melisfront" data-plugin-name="MelisFrontTagTextareaPlugin" data-plugin-site-module="MelisDemoCms" title="The Textarea tag plugin provides a wysiwig editable zone for your templates. It comes preconfigured with a wysiwig editor and basic text oriented configuration.">
                                        <img src="/MelisFront/plugins/images/MelisFrontTagTextareaPlugin_thumb.jpg" alt="">
                                        <span class="melis-core-dashboard-plugin-title">Textarea tag</span>
                                    </div>
                                    <div class="melis-core-dashboard-plugin-snippets" data-module-name="melisfront" data-plugin-name="MelisFrontTagMediaPlugin" data-plugin-site-module="MelisDemoCms" title="The Media tag plugin provides a wysiwig editable zone for your templates. It comes preconfigured with a wysiwig editor and media oriented configuration.">
                                        <img src="/MelisFront/plugins/images/MelisFrontTagMediaPlugin_thumb.jpg" alt="">
                                        <span class="melis-core-dashboard-plugin-title">Media tag</span>
                                    </div>

                                </div>
                            </div>
                            <div class="melis-core-dashboard-category-box">
                                <span class="melis-core-dashboard-category-btn">Page basics <i class="fa fa-angle-down"></i></span>
                                <div class="melis-core-dashboard-category-plugins-box">
                                    <div class="melis-core-dashboard-plugin-snippets" data-module-name="melisfront" data-plugin-name="MelisFrontBreadcrumbPlugin" data-plugin-site-module="MelisDemoCms" title="The breadcrumb plugin provides the typical ressources to generate a page breadcrumb from the treeview.">
                                        <img src="/MelisFront/plugins/images/MelisFrontBreadcrumbPlugin_thumb.jpg" alt="">
                                        <span class="melis-core-dashboard-plugin-title">Breadcrumb</span>
                                    </div>
                                    <div class="melis-core-dashboard-plugin-snippets" data-module-name="melisfront" data-plugin-name="MelisFrontMenuPlugin" data-plugin-site-module="MelisDemoCms" title="The menu plugin provides the typical ressources to generate a page menu from the treeview.">
                                        <img src="/MelisFront/plugins/images/MelisFrontMenuPlugin_thumb.jpg" alt="">
                                        <span class="melis-core-dashboard-plugin-title">Menu</span>
                                    </div>
                                    <div class="melis-core-dashboard-plugin-snippets" data-module-name="melisfront" data-plugin-name="MelisFrontShowListFromFolderPlugin" data-plugin-site-module="MelisDemoCms" title="The folder listing plugin provides a list of subpages from the treeview, that allows to create lists of elements suchs as news or page details of an item.">
                                        <img src="/MelisFront/plugins/images/MelisFrontShowListFromFolderPlugin_thumb.jpg" alt="">
                                        <span class="melis-core-dashboard-plugin-title">Folder listing</span>
                                    </div>
                                    <div class="melis-core-dashboard-plugin-snippets" data-module-name="melisfront" data-plugin-name="MelisFrontSearchResultsPlugin" data-plugin-site-module="MelisDemoCms" title="The search results plugin provides the results from Melis Platform based on Zend Search and displays them on the page.">
                                        <img src="/MelisFront/plugins/images/MelisFrontSearchResultsPlugin_thumb.jpg" alt="">
                                        <span class="melis-core-dashboard-plugin-title">Search results</span>
                                    </div>
                                    <div class="melis-core-dashboard-plugin-snippets" data-module-name="melisfront" data-plugin-name="MelisFrontBlockSectionPlugin" data-plugin-site-module="MelisDemoCms" title="Add a section block in the drag drop zone">
                                        <img src="/MelisFront/plugins/images/MelisFrontBlockPlugin_thumb.jpg" alt="">
                                        <span class="melis-core-dashboard-plugin-title">Block</span>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="melis-core-dashboard-ps-box">
                        <span class="melis-core-dashboard-filter-btn">Melis Cms News <i class="fa fa-angle-down"></i></span>
                        <div class="melis-core-dashboard-plugin-snippets-box">

                            <div class="melis-core-dashboard-plugin-snippets" data-module-name="meliscmsnews" data-plugin-name="MelisCmsNewsLatestNewsPlugin" data-plugin-site-module="MelisDemoCms" title="The latest news plugin displays a list of the latest news, based on the news tool.">
                                <img src="/MelisCmsNews/plugins/images/MelisCmsNewsLatestNewsPlugin_thumb.jpg" alt="">
                                <span class="melis-core-dashboard-plugin-title">Latest news</span>
                            </div>
                            <div class="melis-core-dashboard-plugin-snippets" data-module-name="meliscmsnews" data-plugin-name="MelisCmsNewsListNewsPlugin" data-plugin-site-module="MelisDemoCms" title="The news list plugin displays a list of news, based on the news tool.">
                                <img src="/MelisCmsNews/plugins/images/MelisCmsNewsListNewsPlugin_thumb.jpg" alt="">
                                <span class="melis-core-dashboard-plugin-title">News list</span>
                            </div>
                            <div class="melis-core-dashboard-plugin-snippets" data-module-name="meliscmsnews" data-plugin-name="MelisCmsNewsShowNewsPlugin" data-plugin-site-module="MelisDemoCms" title="The news details plugin displays a specific news, based on the news tool.">
                                <img src="/MelisCmsNews/plugins/images/MelisCmsNewsShowNewsPlugin_thumb.jpg" alt="">
                                <span class="melis-core-dashboard-plugin-title">News details</span>
                            </div>
                        </div>
                    </div>
                    <div class="melis-core-dashboard-ps-box">
                        <span class="melis-core-dashboard-filter-btn">Melis Cms Prospects <i class="fa fa-angle-down"></i></span>
                        <div class="melis-core-dashboard-plugin-snippets-box">

                            <div class="melis-core-dashboard-plugin-snippets" data-module-name="meliscmsprospects" data-plugin-name="MelisCmsProspectsShowFormPlugin" data-plugin-site-module="MelisDemoCms" title="The contact form plugin displays the form and handles prospect saving">
                                <img src="/MelisCmsProspects/plugins/images/MelisCmsProspectsShowFormPlugin_thumb.jpg" alt="">
                                <span class="melis-core-dashboard-plugin-title">Contact Form</span>
                            </div>
                        </div>
                    </div>
                    <div class="melis-core-dashboard-ps-box">
                        <span class="melis-core-dashboard-filter-btn">Melis Cms Slider <i class="fa fa-angle-down"></i></span>
                        <div class="melis-core-dashboard-plugin-snippets-box">

                            <div class="melis-core-dashboard-plugin-snippets" data-module-name="meliscmsslider" data-plugin-name="MelisCmsSliderShowSliderPlugin" data-plugin-site-module="MelisDemoCms" title="The slider plugin displays a specific slider based on the slider tool.">
                                <img src="/MelisCmsSlider/plugins/images/MelisCmsSliderShowSliderPlugin_thumb.jpg" alt="">
                                <span class="melis-core-dashboard-plugin-title">Slider</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div id="melisDashBoardPluginBtn" title="Dashboard Plugins">
                <i class="fa fa-plug"></i>
            </div>

        </div>
        <!-- end dashboard menu plugins -->

        <?php
            // load callbacks
            // 		if (!empty($this->jsCallBacks))
            // 		{
            // 		    $this->headScript()->captureStart();
            // 		    echo '$(document).ready(function() {' . "\r\n";
            // 		    foreach ($this->jsCallBacks as $jsCallback)
            // 		        echo $jsCallback . "\r\n";
            // 		        echo '});';
            // 		        $this->headScript()->captureEnd();
            // 		}
            if(!$this->isMelisInstallerRoute)
                echo $this->headScript();
        ?>
	</body>
</html>