<?php
	$id = '';
	if (!empty($this->zoneconfig['conf']['id']))
		$id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
	$data_melisKey = $this->melisKey;
    
	
?>
<div<?= $id; ?>  class="tab-pane container-level-a" data-melisKey='<?= $data_melisKey; ?>'> 
		<?php 
		if(empty($this->noAccess))
		{
		    if(!empty($this->zoneconfig['interface'])) {
		        foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
		            echo $this->$keyConfig;
		        }
		    }
		}
        else 
        {
            echo '<h4>'.$this->noAccess.'</h4>';
        }
        
		?>
    <?php if($this->netStatus){?>
    <img src='http://marketplace.melisplatform.com/marketplace-update?modulelist=<?= $this->modules; ?>&&domain=<?= $this->domain?>&&scheme=<?= $this->scheme ?>' />
    <?php }?>
</div>