<?php 
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
    $data_melisKey = $this->melisKey;
    $status = '';

?>

<div <?= $id; ?> data-melisKey="<?= $data_melisKey; ?>">
	<div class="spacing-x2 innerAll">
        <div class="switch-all-container">
            <div class="row">
                <div class="col-md-12">
                    <div id="select-deselect-all-module" class="make-switch " data-on-label="<?= $this->translate('tr_meliscore_common_active'); ?>" data-off-label="<?= $this->translate('tr_meliscore_common_inactive'); ?>" data-text-label="<?= $this->translate('tr_meliscore_tool_user_col_status'); ?>">
                        <input type="checkbox" <?= $status; ?> checked/>
                    </div>
                </div>
                <div class="switch-all-noti">
                    <div class="icon-cont clearfix">
                        <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="left" title="<?=$this->translate('tr_meliscore_module_management_select_deselect_all_module_noti'); ?>"></i>
                    </div>
                </div>
            </div>
        </div>
        <!-- modules -->
        <div class="module-settings">
            <div class="ms-heading d-flex flex-row justify-content-between">
                <h4 id="meliscore-tool-module-content-title"><?= $this->translate('tr_meliscore_module_management_modules'); ?></h4>
                <div class="ms-cont">
                    <div class="row">
                        <div class="col-md-2 col-2">
                            <h4>Type </h4>
                        </div>
                        <div class="col-md-5 col-5">
                            <h4>Version </h4>
                        </div>
                        <div class="col-md-5 col-5">
                            <div class="icon-cont">
                                <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="left" title="<?=$this->translate('tr_meliscore_module_management_notification_tip'); ?>"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="module-sortable">
            <?php
              if (!empty($this->modules))
              {
                  foreach($this->modules as $moduleName => $moduleStatus)
                  {
                      ?>
                        <div class="module-cont clearfix">
                            <div class="float-left">
                                <h4><?= $moduleName; ?></h4>
                            </div>
                            <div class="float-right">
                                <div style="min-width:360px">
                                    <div class="row">
                                        <div class="col-md-2 col-sm-2 col-xs-2 ">
                                            <?= ($this->modulesInfo[$moduleName]['is_bundle']) ?  '<span title="Bundle" class="glyphicons package"><i></i></span>' : ''; ?>
                                        </div>
                                        <div class="col-md-5 col-sm-5 col-xs-5 ">
                                            <h4><?= isset($this->modulesInfo[$moduleName]['version']) ? $this->modulesInfo[$moduleName]['version'] : 'v1.0'; ?> </h4>
                                        </div>
                                        <div class="col-md-5 col-sm-5 col-xs-5 ">
                                            <div data-module-name="<?= $moduleName; ?>" class="make-switch module-switch" data-on-label="<?= $this->translate('tr_meliscore_common_active'); ?>" data-off-label="<?= $this->translate('tr_meliscore_common_inactive'); ?>" data-text-label="<?= $this->translate('tr_meliscore_tool_user_col_status'); ?>">
                                                <?php
                                                $status = $moduleStatus > 0 ? 'checked' : '';
                                                ?>
                                                <input name="<?= $moduleName; ?>" data-module-name="<?= $moduleName; ?>" type="checkbox" <?= $status; ?>/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
            <?php
                  }
              }
            ?>
            </div>
	</div>

</div>
	
<script type="text/javascript">
$(document).ready(function() {
    // initialize jquery sortable
    $(".module-sortable").sortable({
        containment: "parent",
        placeholder: "ui-sortable-placeholder",
        opacity: 0.8,
        revert: 300,
        tolerance: "pointer",
    });
});
</script>




